Flags locales
coralproject/talk pull request #1045
Opened 2017-10-04 16:42 UTC by wyattjoh

## What does this PR do?

- Flags now are all required to pre-define their types in the graph, or at the very least provide their translations in locales.

## How do I test this PR?

1. Create some flags
2. Check out the translated responses in the admin

2017-10-06 15:47 UTC, cvle commented on graph/typeDefs.graphql
> +  reason: FLAG_REASON
Required?

2017-10-06 15:52 UTC, cvle commented
We also need to adapt toxic comment for its TOXIC_COMMENT flag.

2017-10-06 16:22 UTC, wyattjoh commented on graph/typeDefs.graphql
> +  reason: FLAG_REASON
Nope!

2017-10-06 16:41 UTC, alinhle requested changes
![image](https://user-images.githubusercontent.com/14221600/31288532-992b3afc-aac5-11e7-924b-1ff56589c719.png)
The graphql refuses to load any system flags whose reasons are not defined in the `FLAG_REASON` type, e.g. trust, suspect and toxic comment flags

2017-10-26 14:36 UTC, alinhle submitted a review, later dismissed

2017-11-08 20:43 UTC, wyattjoh commented
Future PR will merge this branch in.

2017-11-08 20:43 UTC, closed without merging