Fix Shortcuts help menu doesn't dismiss forever.
coralproject/talk pull request #1091
Opened 2017-10-11 13:51 UTC by Goyapa

## What does this PR do?
Fix #1017

## How do I test this PR?
* Go to Admin
* See the shortcuts help menu in the bottom left
* Click X to dismiss forever
* Refresh page
* Menu has gone forever

2017-10-11 14:14 UTC, kgardnr commented
Thank you @Goyapa! We will review this and send along any feedback for you. In the meantime, looking forward to seeing more from you for hacktoberfest! 🎉

2017-10-12 13:11 UTC, kgardnr approved these changes

2017-10-12 13:11 UTC, kgardnr commented
This works for me! I'll let @okbel and @cvle approve the code before we merge. Thanks @Goyapa!

2017-10-12 14:12 UTC, alinhle requested changes
The root issue is here: 
https://github.com/coralproject/talk/blob/master/client/coral-framework/services/bootstrap.js#L182

You can see that `init` is not called. Can you change it there?

2017-10-12 14:28 UTC, Goyapa commented
Thank you @cvle, I`ll have look!

2017-10-12 14:36 UTC, cvle commented
Thanks @Goyapa ! Remember init could be `undefined ` so maybe also default it to a noop.

2017-10-12 19:17 UTC, Goyapa commented
@cvle could you please review once more. Hope it is now like you mentioned.

2017-10-13 10:56 UTC, cvle commented on client/coral-framework/services/bootstrap.js
>    await Promise.all([init, plugins.executeInit(context)]);
It does work like you did. Like this it first runs and wait for `init` and then runs and wait for plugins init. It'd be more efficient to run both `init` and `plugins.executeInit` in one step and then wait for their promises to resolve.

E.g.

```js
import noop from 'lodash/noop';

export async function createContext({
   [...]
   init = noop,
 } = {}) {
  [...]
  await Promise.all([init(context), plugins.executeInit(context)]);
}
```

2017-10-13 12:21 UTC, Goyapa commented
@cvle I see noop stands for lodash empty function. Next try! ;-)

2017-10-13 13:19 UTC, alinhle approved these changes
@Goyapa lgtm! merci

2017-10-13 13:21 UTC, merged