Email Verification Resend
coralproject/talk pull request #1099
Opened 2017-10-12 21:31 UTC by wyattjoh

## What does this PR do?

Prompts the user to resend their email verification if it has not been received.

Related: https://www.pivotaltracker.com/story/show/151851092

2017-10-23 17:35 UTC, cvle commented on services/limit.js
> +
Some comments for this method would be awesome :-)

2017-10-24 11:18 UTC, kgardnr commented
Nice! This works well:

<img width="496" alt="new_pass" src="https://user-images.githubusercontent.com/1077300/31940248-59d74b22-b8b5-11e7-8fe1-dd7e002e15d6.png">

My only question is I noticed 2 users being generated - shouldn't these be generated in the test db, not the dev db? @cvle @wyattjoh

2017-10-24 11:19 UTC, kgardnr requested changes
Outstanding question

2017-10-24 12:07 UTC, kgardnr approved these changes

2017-10-24 12:08 UTC, kgardnr commented
I think the above is something with my local env, approving! 💯

2017-10-24 16:53 UTC, merged