Fix incorrect email configuration in docs
coralproject/talk pull request #1151
Opened 2017-11-08 12:11 UTC by jtnelson

Change TALK_SMTP_EMAIL to TALK_SMTP_FROM_EMAIL

## What does this PR do?

## How do I test this PR?

- click a button
- view the cat
- see the cat meow

2017-11-08 14:27 UTC, kgardnr submitted a review, later dismissed

2017-11-08 15:49 UTC, wyattjoh requested changes

2017-11-08 15:49 UTC, wyattjoh commented on docs/_docs/02-02-advanced-configuration.md
> +## TALK_SMTP_FROM_EMAIL
Seems it's `TALK_SMTP_FROM_ADDRESS` actually:

https://github.com/coralproject/talk/blob/39a980b22f8bf40c5e2734f906ccf6dfca29914b/config.js#L163

2017-11-09 11:37 UTC, kgardnr commented
@wyattjoh fixed, can you take a look?

2017-11-09 23:23 UTC, wyattjoh approved these changes

2017-11-10 12:02 UTC, merged