Performance enhancements
coralproject/talk pull request #1186
Opened 2017-11-30 21:18 UTC by cvle

## What does this PR do?
- [x] Throttled and batched subscription handling
- [x] Preserve immutability and correctly detect when query data has changes (using custom optimzied version of `graphql-anywhere` (https://github.com/cvle/graphql-anywhere/tree/optimized) (improved overall performance by 30%)
- [ ] Preoptimize graphql documents on production builds
- [ ] Remove death star button

## How do I test this PR?

- Check that everything is still working
- Open moderation panel
- Open stream in another window with another user and click on Death Star button which posts 100 comments in  10 seconds ms.

2017-12-01 12:08 UTC, kgardnr commented
This is looking really great so far @cvle!

2017-12-04 13:39 UTC, kgardnr submitted a review, later dismissed
:100:! Great work Kiwi!!

2017-12-04 17:03 UTC, wyattjoh requested changes

2017-12-04 17:03 UTC, wyattjoh commented on package.json
> +    "graphql-anywhere-optimized": "git+https://git@github.com/cvle/graphql-anywhere#optimized",
Replace with version pin from npm.

2017-12-04 21:32 UTC, wyattjoh submitted a review, later dismissed

2017-12-04 22:16 UTC, wyattjoh approved these changes

2017-12-04 22:16 UTC, merged