Ban user [WIP]
coralproject/talk pull request #121
Opened 2016-12-01 15:22 UTC by gabelula

## What does this PR do?

Work for [Pivotal Ticket 134297437](https://www.pivotaltracker.com/story/show/134297437) .
- Adds a 'status' field to the User that could be 'active' or 'banned'. It is 'active' by default.
- Adds a button to the moderation queue in the Admin to ban the user. It rejects the comment that the user was banned for.
- Adds a column to the community in the Admin to change the status of the user. 

Still working on 
- banning via modal window in the moderation queue
- restricting content for the banned user in the comment stream instead of disable it.

2016-12-05 17:20 UTC, okbel commented
@gabelula Is this one ready to be tested? Could you merge to master?

2016-12-08 19:06 UTC, okbel commented
@gabelula it has some Confict issues, could you solve them? Also, I leave some notes

2016-12-08 19:06 UTC, okbel commented
Code looks awesome, btw. 💯

2016-12-08 19:07 UTC, okbel commented on client/coral-admin/src/translations.json
> +      "role": "Select role...",
Seleccionar rol?

2016-12-08 19:08 UTC, gabelula commented on client/coral-admin/src/translations.json
> +      "role": "Select role...",
ja! Si, lo cambio.

2016-12-08 19:10 UTC, okbel commented on client/coral-admin/src/actions/comments.js
> +export const showBanUserDialog = (userId, userName, commentId) => {
Looks 💯 

This:
```js
export const showBanUserDialog = (userId, userName, commentId) => {
  return dispatch => {
    dispatch({type: 'SHOW_BANUSER_DIALOG', userId, userName, commentId});
  };
};
```
is the same as doing: 

```js
export const showBanUserDialog = (userId, userName, commentId) => dispatch => ({
  dispatch({type: 'SHOW_BANUSER_DIALOG', userId, userName, commentId});
})
```

The () is implicit return `() => (something)`

2016-12-09 03:42 UTC, riley requested changes

2016-12-09 03:42 UTC, riley commented on client/coral-admin/src/actions/comments.js
> +export const showBanUserDialog = (userId, userName, commentId) => {
maybe i'm just dumb, but I like the first approach better. Chaining the function returns like that is as offensive as `fetch('url').then().then().then()` all on one line.

2016-12-09 03:42 UTC, riley commented on client/coral-admin/src/actions/comments.js
> +export const banUser = (status, userId, commentId) => {
this should be moved to the user reducer, as it's affecting users, not comments

2016-12-09 03:42 UTC, riley commented on client/coral-admin/src/components/BanUserDialogContent.js
> +import React from 'react';
remove this per our discussion

2016-12-09 03:42 UTC, riley commented on client/coral-admin/src/components/Comment.js
> +//return props.author.get('status') === 'banned' ? 'disabled' : 'raised';
remove this commented out line

2016-12-09 03:42 UTC, riley commented on client/coral-admin/src/components/BanUserDialog.js
> +const BanUserDialog = ({open, handleClose, onClickBanUser, user}) => {
so I think the lines below are trying to set defaults. You can do this cleanly by changing the line above to 

`const BanUserDialog = ({open, handleClose, onClickBanUser, user = {}}) => {`

this sets `user` as always defined so...

2016-12-09 03:42 UTC, riley commented on client/coral-admin/src/components/BanUserDialog.js
> +  const commentId = (typeof user === 'undefined') ? '' : user['commentId'];
these three lines can become:
`const {userName = '', userId = '', commentId = ''} = user;`
since `user` is always defined

2016-12-09 03:42 UTC, riley commented on client/coral-admin/src/reducers/community.js
> +    commenters[idx].status = action.status;
I this code is modifying a immutable object, not a js object. So I think it should be:

`const commenter = commenters[idx].set('status', action.status);`

and then you have to use maybe `commenters.setIn(idx, commenter)` to update the array

@impronunciable thoughts?

2016-12-09 03:42 UTC, riley commented on client/coral-admin/src/reducers/users.js
> +  ids: List(),
madness. remove this comma

2016-12-09 03:42 UTC, riley commented on routes/api/user/index.js
> +      res.send(status);
should this be `res.json`?

2016-12-09 18:26 UTC, gabelula commented
@riley All the changes were made already.

2016-12-09 20:55 UTC, riley approved these changes

2016-12-09 20:55 UTC, merged