Adds a variable to the possible translations.
coralproject/talk pull request #126
Opened 2016-12-03 00:14 UTC by gabelula

## What does this PR do?

Adds a variable to the strings to be included in the translation.

## How do I test this PR?

Adds a translation with a variable and check that it works.

2016-12-05 17:49 UTC, davidgljay requested changes

2016-12-05 17:49 UTC, davidgljay commented on client/coral-framework/modules/i18n/i18n.js
> +        val = val.replace('/\{0\/g', att);
I tested this line and it didn't seem to work as desired. Should it be:

`val = val.replace(/\{0\}/g, att);`?

2016-12-06 23:46 UTC, gabelula commented on client/coral-framework/modules/i18n/i18n.js
> +        val = val.replace('/\{0\/g', att);
YES!!

2016-12-07 16:44 UTC, davidgljay approved these changes

2016-12-07 16:44 UTC, merged