Asset comment settings
coralproject/talk pull request #129
Opened 2016-12-06 17:30 UTC by okbel

## What does this PR do?

This PR adds

- Coral UI 
  - Checkbox
- Configure Stream Tab Functionality
- UX/UI

Note: 'Pre-Moderate Comments Containing Links' is ready on the frontend, once we have that in the backend, we'll tie that up.

2016-12-08 16:39 UTC, okbel commented
Would you mind taking a look at this one, @davidgljay and @wyattjoh? //cc @kgardnr

2016-12-08 16:59 UTC, wyattjoh requested changes

2016-12-08 16:59 UTC, wyattjoh commented on routes/api/asset/index.js
> +    .then(({settings}) => res.status(200).send({settings}))
Updates can not return a payload, this should be reverted to return 204 without a body.

2016-12-08 17:02 UTC, wyattjoh commented
This should not be using the `Asset.status` field, and instead should defer to what we have in the close-comments (https://github.com/coralproject/talk/tree/close-comments) branch.

2016-12-08 17:51 UTC, okbel commented
@wyattjoh I'll update the PR as soon as `close-comments` branch gets merged

2016-12-08 19:12 UTC, davidgljay requested changes
One change requested around i18n and a few standards questions.

2016-12-08 19:12 UTC, davidgljay commented on client/coral-configure/components/ConfigureCommentStream.js
> +        Apply
This and other text should be handled via i18n.

2016-12-08 19:12 UTC, davidgljay commented on client/coral-configure/components/ConfigureCommentStream.css
> +.container {
Earlier we made a decision to handle all comment stream css in default.css for ease of reconfigurability. I'm open to revisiting that decision (it probably generally makes sense to reexamine our strategy for customizing style), but we should be intentional about it before changing norms.

2016-12-08 19:12 UTC, davidgljay commented on client/coral-framework/reducers/config.js
> +import * as actions from '../constants/config';
This makes sense as a standard, but it's not reflected for items and notifications. Should we make that update here or put it in a separate PR? If we're going to refactor we should make it consistent throughout.

2016-12-08 19:18 UTC, okbel commented on client/coral-configure/components/ConfigureCommentStream.css
> +.container {
I agree. The idea of having the `default.css` was for customizing and creating themes. This idea still remains. But components need to have core styling such as positions, and vertical-aligns. The app must still work regardless of the `default.css`. That being said, shouldn't the work of `default.css` only be for theming and overriding purposes?

2016-12-09 15:53 UTC, okbel commented
@wyattjoh @davidgljay Everything updated. Thanks!

2016-12-09 20:04 UTC, gabelula approved these changes
Ready to merge.

2016-12-09 20:05 UTC, gabelula approved these changes

2016-12-09 20:06 UTC, gabelula approved these changes

2016-12-09 20:09 UTC, merged