Adding suspension and ban support for duration in hours and days
coralproject/talk pull request #1382
Opened 2018-02-19 15:10 UTC by okbel

## What does this PR do?
https://www.pivotaltracker.com/story/show/155259030

## How do I test this PR?

- suspend a user 
- unsuspend the user
- suspend a user (choose a different duration)
- unsuspend the user
- suspend a user  (choose a different duration)
- unsuspend the user
- check the account history

2018-02-19 15:19 UTC, alinhle requested changes
Change  `readaeble` to `readable`. Rest looks good 👍

2018-02-20 15:38 UTC, kgardnr approved these changes

2018-02-20 17:47 UTC, kgardnr commented
@cvle I fixed the typo, if you want to approve now :)

2018-02-20 18:57 UTC, alinhle approved these changes

2018-02-20 20:13 UTC, merged