Terms and conditions
coralproject/talk pull request #1484
Opened 2018-03-26 15:23 UTC by okbel

## What does this PR do?
- Adds the ability to dispatch `enableSubmitSignUpForm` and `disableSubmitSignUpForm` for `talk-plugin-auth`
- Adds `talk-plugin-health-report` that adds one last field to the Sign Up Form

More here: https://www.pivotaltracker.com/n/projects/1863625

Note: The translation service does not support receiving elements I was going to add an update to it but it's not worth it since we are going to upgrade our translation service. And more changes to it 

`talk-plugin-health-report` will be removed from this PR as soon as the review is done :)

2018-03-26 15:29 UTC, wyattjoh commented
`talk-plugin-health-report` should be extracted to another repository @okbel, as it's not a part of the core installation.

2018-03-26 16:02 UTC, okbel commented
👍 I'll leave it for testing and then I'll remove that folder. The PR is needed though, it has updates to the `talk-plugin-auth`

2018-03-29 14:20 UTC, okbel commented
@cvle ready to be checked! Thanks for the `hasBlocker` pattern 😄

2018-03-29 20:56 UTC, alinhle requested changes
I removed `docs/source/_data/introspection.json` from the PR which seems to have been accidently commited and added it to `.gitignore`. I also changed the plugins service to produce a descriptive key which I replaced throughout the codebase where we relied on the talkPluginName instead. This makes sure no matter how many components a plugins adds to a slot, it still works. 

I adapted your blockers API to the above changed and simplified it a little bit. Besides the small review comments, it looks good!

2018-03-29 20:56 UTC, alinhle commented on plugins/talk-plugin-auth-checkbox/client/components/TermsAndConditionsField.js
> +    href={t('talk-plugin-health-report.terms-link')}
Is the name `talk-plugin-health-report` here correct while the plugin name is `talk-plugin-auth-checkbox`?

2018-03-29 20:56 UTC, alinhle commented on plugins/talk-plugin-auth-checkbox/client/index.js
> +    'talkPluginAuth-formField': [TermsAndConditionsField],
It feels a bit odd using the dash in combination with camelCase. What do you think of `talkPluginAuth.formField` instead?

2018-03-30 13:36 UTC, okbel commented on plugins/talk-plugin-auth-checkbox/client/index.js
> +    'talkPluginAuth-formField': [TermsAndConditionsField],
I like it :D

2018-03-30 17:36 UTC, alinhle submitted a review, later dismissed

2018-04-02 16:17 UTC, kgardnr approved these changes

2018-04-02 16:17 UTC, merged