remove cruft by pulling out some immutable.js stuff
coralproject/talk pull request #150
Opened 2016-12-09 21:53 UTC by riley

## What does this PR do?

I'm going to go through the dumb components and removing where we directly access immutable.js objects because it's just noise. I'm starting from the bottom up, so there will be several of these PRs. The goal is to convert the `mapStateToProps` to call `toJS()` at render time so that we don't have to call `comments.get('status')` or whatever every single time.

## How do I test this PR?

- go to the admin
- you should still be able to see the comments in ModerationQueue and interact with them. No functionality change should have happened

2016-12-10 00:18 UTC, jde commented on client/coral-admin/src/containers/ModerationQueue/ModerationQueue.js
> +    const premodIds = c.ids.filter(id => c.byId[id].status === 'premod');
I like the standard of moving logic like this up.

2016-12-10 00:24 UTC, jde requested changes

2016-12-10 00:24 UTC, jde commented on client/coral-admin/src/components/CommentList.js
> +          console.log('inside the map', typeof commentId, commentId, typeof active, active);
Please remove

2016-12-10 00:26 UTC, jde commented on client/coral-admin/src/components/CommentList.js
> +      this.setState({active: head(commentIds)});
I would recommend against using a library method with the native object already has a method that accomplishes the same thing.

2016-12-10 00:27 UTC, jde commented on client/coral-admin/src/components/CommentList.js
> +    } else if (direction === 'up' && active !== head(commentIds)) {
I would recommend against using a library method with the native object already has a method that accomplishes the same thing. Does _.head() provide deeper functionality?

2016-12-10 00:36 UTC, riley commented on client/coral-admin/src/components/CommentList.js
> +    } else if (direction === 'up' && active !== head(commentIds)) {
`[].first()` isn't a method unless you add it, to my knowledge.

2016-12-10 00:37 UTC, riley commented on client/coral-admin/src/components/CommentList.js
> +    } else if (direction === 'up' && active !== head(commentIds)) {
`.first()` is an immutable thing afaik

2016-12-13 18:15 UTC, davidgljay approved these changes
Looks good! Looking through this I've found some weirdness in the action (where we pull state into an action using getState rather than handling it in a reducer, which makes way more sense.) But that's tangential enough to this that it doesn't matter. Approved!

2016-12-13 18:44 UTC, merged