Disable autocomplete on username signup field
coralproject/talk pull request #1512
Opened 2018-04-09 19:28 UTC by okbel

- Disable autocomplete on username signup field
https://www.pivotaltracker.com/story/show/156287975

2018-04-11 17:22 UTC, wyattjoh requested changes
Small change! Otherwise, wonderfully small update 😄

2018-04-11 17:22 UTC, wyattjoh commented on plugins/talk-plugin-auth/client/login/components/SignUp.js
> +                autocomplete="off"
I'd also add:

```js
autocapitalize="none"
```

For the username field.

2018-04-12 15:17 UTC, okbel commented on plugins/talk-plugin-auth/client/login/components/SignUp.js
> +                autocomplete="off"
👍

2018-04-12 16:46 UTC, wyattjoh approved these changes

2018-04-12 16:53 UTC, merged