GDPR Bug - Confirm Email Dialog inputs shouldn't be connected to the save button in the background
coralproject/talk pull request #1616
Opened 2018-05-14 16:32 UTC by okbel

## What does this PR do?
- https://www.pivotaltracker.com/story/show/157322169

2018-05-14 20:32 UTC, kgardnr approved these changes

2018-05-14 20:33 UTC, kgardnr commented
Looks great @okbel! Once @cvle approves we can merge!

2018-05-14 21:38 UTC, cvle commented on plugins/talk-plugin-local-auth/client/components/ChangeEmailContentDialog.js
> +    this.disableEditing();
This does not exists?

2018-05-14 21:40 UTC, alinhle requested changes
See above

2018-05-15 16:10 UTC, cvle commented on plugins/talk-plugin-local-auth/client/components/ChangeEmailContentDialog.js
>                defaultValue=""
Not important now,  but generally we shouldn't use default value

2018-05-15 16:10 UTC, cvle commented on plugins/talk-plugin-local-auth/client/components/ChangeEmailContentDialog.js
> +    this.clearForm();
Clear form does nothing

2018-05-15 16:10 UTC, cvle commented on plugins/talk-plugin-local-auth/client/components/ChangeEmailContentDialog.js
> +  cancel = () => {
Cancel does not close the dialog

2018-05-15 16:11 UTC, cvle commented on plugins/talk-plugin-local-auth/client/components/ChangeEmailContentDialog.js
> +  isSaveEnabled = () => {
This function is not used

2018-05-15 16:12 UTC, cvle commented on plugins/talk-plugin-local-auth/client/components/ChangeEmailContentDialog.js
> +    this.clearForm();
Besides we don't need to clear the form, just close the dialog

2018-05-15 16:14 UTC, cvle commented on plugins/talk-plugin-local-auth/client/components/ChangeEmailContentDialog.js
> +    this.clearForm();
Clearing the state will not clear the form because, you are using uncontrolled input (not recommended)

2018-05-15 16:47 UTC, cvle commented on plugins/talk-plugin-local-auth/client/components/ChangeEmailContentDialog.js
> +  closeDialog: PropTypes.func,
Something I'm going to suggest more in the future and in the arch meetings, that   I'd name these properties `onCloseDialog` instead to emphasis that this is a sort of event just like HTML components does with `onClick`, `onCancel`. Moving away from _I'm passing in a fuction_ to  _I'm reacting to a event_ which puts an emphasis on isolation.

2018-05-15 16:48 UTC, alinhle approved these changes

2018-05-15 16:54 UTC, merged