My comments
coralproject/talk pull request #163
Opened 2016-12-12 18:54 UTC by riley

# WIP

## What does this PR do?

## How do I test this PR?

- click a button
- view the cat
- see the cat meow

2016-12-14 20:43 UTC, wyattjoh requested changes

2016-12-14 20:43 UTC, wyattjoh commented on routes/api/assets/index.js
> +
I thought it we had discussed that the hydration on the user comments endpoint would be better?

2016-12-14 20:43 UTC, wyattjoh commented on routes/api/comments/index.js
> +router.get('/user/:user_id', (req, res, next) => {
This route conflicts with existing routes:

```
/api/v1/comments/:comment_id
/api/v1/comments/user/:user_id
```

It should instead be:

```
/api/v1/comments?user_id=...
```

As you are just listing comments.

2016-12-14 20:44 UTC, okbel requested changes

2016-12-14 20:44 UTC, okbel commented on client/coral-framework/actions/assets.js
> +    dispatch({type: FETCH_MULTIPLE_ASSETS});
We are using `_REQUEST` `_SUCCESS` `_FAILURE` as postfix

Can we change those?

2016-12-14 20:44 UTC, wyattjoh commented on routes/api/comments/index.js
> +router.get('/user/:user_id', (req, res, next) => {
Note that this will also resolve the assets being on the comments for you.

2016-12-14 20:45 UTC, wyattjoh commented on routes/api/comments/index.js
> +router.get('/user/:user_id', (req, res, next) => {
As well as hydrating other data, see https://github.com/coralproject/talk/blob/7ef75fa92c60cf45c6868fbb9a81d77b7f87e506/routes/api/comments/index.js#L12-L63

2016-12-14 20:49 UTC, okbel commented on client/coral-framework/reducers/user.js
> +    return state.set('myAssets', fromJS(action.assets));
`return state.set('myAssets', action.assets);` 
 `action.comments` instead of using fromJS is not working?

2016-12-14 21:01 UTC, riley commented on routes/api/assets/index.js
> +
of course, I forgot. I'll do that in this PR

2016-12-15 17:37 UTC, okbel approved these changes

2016-12-15 17:46 UTC, wyattjoh approved these changes

2016-12-15 19:24 UTC, merged