Global comment stream close setting
coralproject/talk pull request #171
Opened 2016-12-14 17:41 UTC by impronunciable

It adds a global setting for autoclosing comments. It can be configured in the admin.

Also when going to the comment stream as an admin you can see when the stream will close.

2016-12-14 19:42 UTC, wyattjoh commented
Do we have a way to turn on/off auto closing?

2016-12-14 21:55 UTC, gabelula requested changes

2016-12-14 21:55 UTC, gabelula commented on client/coral-admin/src/translations.json
> +      "never": "Nunca",
Is the string "never" missing from the english strings?

2016-12-15 19:25 UTC, impronunciable commented on client/coral-admin/src/translations.json
> +      "never": "Nunca",
we are not using it

2016-12-15 19:25 UTC, impronunciable commented
@wyattjoh you can leave it blank

2016-12-15 20:45 UTC, impronunciable commented
@gabelula removed that translation and merged with master

2016-12-15 20:46 UTC, gabelula approved these changes

2016-12-15 20:50 UTC, merged