Heroku fix
coralproject/talk pull request #1721
Opened 2018-07-02 11:34 UTC by davisshaver

## What does this PR do?
The Deploy to Heroku button had been removed following a bug report https://github.com/coralproject/talk/issues/1685.

This PR makes a few tweaks to the Talk repo to facilitate one-click deployment with Heroku.

- Removes `yarn.lock` which otherwise confuses Heroku. Yarn can now use `package-lock.json` so this might be mergable into master.

- Adds a few packages that seem required in the default plugins. I think these packages should be installed during the normal build process but I'm not sure how to diagnose the issue.

- Silences rewrite env errors, which throws for the Mailgun SMTP password even if one is set through Heroku. Maybe this is due to when the Heroku env is available.

## How do I test this PR?
- Create a new app on Heroku using [this link](https://dashboard.heroku.com/new?template=https%3A%2F%2Fgithub.com%2Fdavisshaver%2Ftalk-heroku&env[TALK_FACEBOOK_APP_ID]=ignore&env[TALK_FACEBOOK_APP_SECRET]=ignore&env[REWRITE_ENV_SILENT]=true).
this link.
- The app should build without error.

2018-07-02 11:38 UTC, davisshaver commented
Netfily CI depends on `yarn.lock` being present to make `yarn` available to the environment. https://www.netlify.com/docs/build-settings/

2018-07-02 11:57 UTC, davisshaver commented
Not sure why Netfily or the integration tests failed.

2018-07-02 15:00 UTC, kgardnr commented
@davisshaver Thanks for this!! The netlify build log is complaining about yarn install. Can you try running yarn install locally and see if you get an error?

2018-07-02 21:15 UTC, davisshaver commented
@kgardnr Netifly is working now, although the integration test is still failing. I don't believe it's related to the changeset though.

2018-07-03 15:03 UTC, wyattjoh requested changes
The `pakage-lock.json` should not be committed to this repository as we're using yarn in this configuration.

As such, it shouldn't be required to add the `.slugignore` file either.

2018-07-03 15:03 UTC, wyattjoh commented on package.json
> +    "archiver": "^2.1.1",
These dependencies are resolved during the build process, and should not be included in the base `package.json`.

2018-07-03 16:00 UTC, davisshaver commented
🤦‍♂️ Thanks @wyattjoh! I'll get this cleaned up.

regarding the packages, do you have any advice on how to debug why they might not be resolved during the build process?

2018-07-03 17:17 UTC, davisshaver commented
Cleaned this up and with Yarn working properly, the compile process work as expected. Build log: https://gist.github.com/davisshaver/d5bbf6c404bfaaa39ab76a1acf5db4b4

2018-07-04 17:08 UTC, wyattjoh commented
Thanks for your patience @davisshaver! As a more permanent solution (that should also be Heroku independent) could you revert the `app.json` and instead replace it with the following?

```diff
﻿﻿diff --git a/services/env.js b/services/env.js
index b40a44a83..b3aaa42b3 100644
--- a/services/env.js
+++ b/services/env.js
@@ -1,3 +1,7 @@
+// Ensure that we always process the rewrites silently, otherwise it may fail in
+// environments like Heroku.
+process.env.REWRITE_ENV_SILENT = 'TRUE';
+
 // Perform rewrites to the runtime environment variables based on the contents
 // of the process.env.REWRITE_ENV if it exists. This is done here as it is the
 // entrypoint for the entire applications configuration.

```

2018-07-05 09:11 UTC, davisshaver commented
@wyattjoh good idea, all set for another look!

2018-07-05 15:06 UTC, wyattjoh approved these changes

2018-07-05 15:06 UTC, merged

2018-07-05 15:07 UTC, wyattjoh commented
Looks great! Thanks!