Initial Passport Integration
coralproject/talk pull request #1743
Opened 2018-07-10 19:14 UTC by wyattjoh

## What does this PR do?

- Adds initial passport integration
- Adds server graph types based off of the graphql schema
- Added `@auth` custom graph directive

## Waiting on

- [ ] https://github.com/auth0/node-jwks-rsa/issues/47

2018-07-11 21:49 UTC, wyattjoh commented
Looks like the test failures are due to the lack of url in the specs @cvle, do you think you could take a look into that?

2018-07-16 15:49 UTC, alinhle requested changes

2018-07-16 15:49 UTC, alinhle commented on src/core/client/tsconfig.json
> +      "talk-locales/*": ["../../locales/*"]
Merge conflict, this line isn't needed

2018-07-16 15:49 UTC, alinhle commented on package.json
> +    "compile:graphql": "node ./scripts/types.js",
Maybe `compile:schema` is more on point?

2018-07-16 15:49 UTC, alinhle commented on scripts/types.js
> +const { Linter, Configuration } = require("tslint");
This file should have a more descriptive name, `generateSchemaTypes` or sth else

2018-07-16 15:49 UTC, alinhle commented on scripts/types.js
> +  );
Why not `path.join(__dirname, "../src/core/server/graph/..")`?

2018-07-16 15:49 UTC, alinhle commented on src/core/server/app/handlers/auth/local.ts
> +// sent.
`to bet set`, `sent` is misleading

2018-07-16 15:49 UTC, alinhle commented on src/core/server/models/user.ts
> +    input.password = await bcrypt.hash(input.password, 10);
I recommend instead of modifying the original `input` causing an side-effect to use a new object or variable instead (side-effect-free / pure)

2018-07-16 15:49 UTC, alinhle commented on src/core/server/app/middleware/passport/oidc.ts
> +      const user = await findOrCreateOIDCUser(this.db, tenant, token);
I assume `verify` to be `side-effect` free, however this is creating a user in case it doesn't find.

2018-07-16 15:49 UTC, alinhle commented on src/core/server/app/middleware/passport/oidc.ts
> +  private keyFunc = (client: jwks.JwksClient): jwt.KeyFunction => (
Maybe  `getSigningKey` is a better name?

2018-07-16 15:49 UTC, alinhle commented on src/core/server/app/middleware/passport/oidc.ts
> +function getEnabledIntegration(tenant: Tenant) {
Maybe better `getEnabledIntegrationOrThrow` ?

2018-07-16 15:49 UTC, cvle commented on src/core/server/app/middleware/passport/oidc.ts
> +  return new OIDCStrategy({ db });
I was just wondering if there is a way to make this better testable.

2018-08-01 15:31 UTC, cvle commented on src/core/server/app/middleware/passport/index.ts
> +export const wrapAuthz = (
I think Authz means Authorizations but this looks like it's about authentication, right?

2018-08-02 07:39 UTC, alinhle approved these changes

2018-08-02 10:41 UTC, merged