Admin asset list
coralproject/talk pull request #182
Opened 2016-12-16 22:20 UTC by davidgljay

## What does this PR do?

Creates a list where admins can review assets with comment streams.

## How do I test this PR?

1. Create a few streams by visiting `http://localhost:300/assets/some-random-string`
2. Visit the admin panel.
3. Click "Streams" tab.
4. You should see a list of streams.
5. Sort, filter and search should work as expected.
6. Pagination should work as expected if more than 25 streams are present.

## Note
There is an unrelated bug causing publication dates to be incorrect.

2016-12-21 19:52 UTC, riley commented
If I close an article in the toggle thing, it doesn't flip over to show "closed" until I reload the page.

2016-12-21 19:53 UTC, riley commented
if I click Sort By any of the filters, the list disappears.

2016-12-21 19:54 UTC, riley commented
typing in the search box makes the articles disappear also

2016-12-21 19:54 UTC, riley commented
clicking Next on the pagination thing at the bottom takes me to the next page (I think?) and I can't get back to see the articles. I'd probably just disable Next if there is no next page

2016-12-21 20:13 UTC, davidgljay commented
Bug fixed and `Next` and `Prev` buttons removed.

2016-12-22 00:02 UTC, riley requested changes
looking great, everything works. just a couple of optimizations if possible

2016-12-22 00:02 UTC, riley commented on client/coral-admin/src/containers/Streams/Streams.js
> +    return `${d.getMonth() + 1}/${d.getDate()}/${d.getFullYear()}`;
is there any way to detect a non-english language and display the dates in non-american style?

2016-12-22 00:02 UTC, riley commented on client/coral-admin/src/containers/Streams/Streams.js
> +    this.setState((prevState) => {
is there anyway to combine these two `this.setState` statements?

2016-12-22 00:02 UTC, riley commented on client/coral-admin/src/containers/Streams/Streams.js
> +    console.log(assets);
remove this log

2016-12-22 00:03 UTC, gabelula commented on client/coral-admin/src/containers/Streams/Streams.js
> +    return `${d.getMonth() + 1}/${d.getDate()}/${d.getFullYear()}`;
In that case date format needs to be saved as part of the Settings.

2016-12-22 00:19 UTC, davidgljay commented on client/coral-admin/src/containers/Streams/Streams.js
> +    return `${d.getMonth() + 1}/${d.getDate()}/${d.getFullYear()}`;
I thought about this, but it seemed out of scope for this story. It involves an unrelated setting and associated UI.

2016-12-22 02:14 UTC, davidgljay commented
Recommended updates implemented.

2016-12-22 17:37 UTC, riley approved these changes
awesome! 💯

2016-12-22 17:38 UTC, merged