fix long urls breaking moderation box
coralproject/talk pull request #1840
Opened 2018-09-03 06:23 UTC by hjanuschka

fixes: https://github.com/coralproject/talk/issues/1835

![bildschirmfoto 2018-09-03 um 08 20 18](https://user-images.githubusercontent.com/2891702/44970554-93ffe400-af52-11e8-8a15-d26e55adcb11.png)

2018-09-04 17:41 UTC, kgardnr commented
Thank you for fixing this @hjanuschka!!

Tagging @clintabrown as he was the one who reported this.

We will review this asap!

2018-09-06 17:50 UTC, alinhle requested changes

2018-09-06 17:50 UTC, cvle commented on client/coral-admin/src/routes/Moderation/components/Comment.css
> +  word-break: break-all;
Hi @hjanuschka, thanks for this PR.

`word-break: break-all;` breaks in the middle of words even if it doesn't have to. Would `word-wrap: break-word;` also do?

2018-09-07 11:13 UTC, hjanuschka commented
feedback adressed 👍

2018-09-07 14:42 UTC, cvle commented on client/coral-admin/src/routes/Moderation/components/Comment.css
> +  word-break: break-word;
Even better break is `overflow-wrap: break-word;` which only breaks word if absolute necessary.

See note in, which explains the contrast to `word-break`.
https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-wrap

2018-09-07 14:43 UTC, alinhle requested changes

2018-09-07 14:43 UTC, cvle commented on client/coral-admin/src/routes/Moderation/components/Comment.css
> +  word-break: break-word;
Even better break is overflow-wrap: break-word; which only breaks word if absolute necessary.

See note in, which explains the contrast to word-break.
https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-wrap

2018-09-07 17:13 UTC, hjanuschka commented
@cvle nice, didnt' know that one, thx, feedback addressed

2018-09-07 20:01 UTC, alinhle approved these changes

2018-09-07 20:01 UTC, merged

2018-09-07 20:01 UTC, cvle commented
Thanks!