Admin
coralproject/talk pull request #1910
Opened 2018-09-25 18:28 UTC by okbel

## What does this PR do?
- First iteration over the Admin Client
- Handles multiple views  -   MODERATE, COMMUNITY, STORIES, CONFIGURE 

## How do I test this PR?
- Go to http://localhost:8080/admin.html

2018-09-26 14:43 UTC, alinhle requested changes
As briefly talked about. In the `admin` target we have full control over the location as we are not in an iframe nor in a popup and so instead of writing our own view router, we can rely on much more powerful libraries that helps us manage the various routes of the admin. One that comes with Relay modern integration would be https://github.com/relay-tools/found-relay

2018-09-26 14:43 UTC, cvle commented on config/watcher.ts
> +        "core/client/admin/**/*.graphql",
Not sure how the `auth` lines got here, but `npm run compile:relay-stream` does not touch these files. We can delete lines 22-27.

2018-09-26 14:43 UTC, cvle commented on src/core/server/app/router.ts
> +  router.get("/admin", adminHandler);
I let @wyattjoh the server part :-)

2018-10-02 21:15 UTC, wyattjoh approved these changes
Server side looks good to me, I cleaned up a few things!

2018-10-02 22:41 UTC, alinhle requested changes

2018-10-02 22:41 UTC, cvle commented on src/types/farce.d.ts
> +declare module "farce" {
Let's add a todo comment here `// TODO: provide better typings.`

2018-10-02 22:41 UTC, cvle commented on src/core/client/admin/components/App.tsx
> +    <HorizontalGutter>
`HorizontalGutter` can be used as root and we would save one unnecessary `div`, e.g. `<HorizontalGutter className={styles.root}>`

2018-10-02 22:41 UTC, cvle commented on src/core/client/admin/components/Community.tsx
> +  <HorizontalGutter>
This container seems obsolete, this is repeated in other files too.

2018-10-02 22:53 UTC, alinhle approved these changes

2018-10-03 00:14 UTC, merged