Adding a draft for models.
coralproject/talk pull request #2
Opened 2016-11-01 20:42 UTC by gabelula

To discuss.

2016-11-01 20:48 UTC, wyattjoh requested changes
Should use `const/let` instead of `var` in ES6. Also don't import raw `mongoose`, instead grab the one from the mongoose file as in the comments listed below.

2016-11-01 20:48 UTC, wyattjoh commented on models/asset.js
> +var mongoose = require('mongoose');
Should import the mongoose that's in the current folder, ie:

``` js
const mongoose = require('../mongoose');
```

Also, should use const wherever possible, never use var.

2016-11-01 20:50 UTC, gabelula commented on models/asset.js
> +var mongoose = require('mongoose');
ok. Done!

2016-11-01 20:50 UTC, wyattjoh approved these changes

2016-11-01 21:05 UTC, wyattjoh requested changes
Foreign keys are not referenced using models. Decided to hold off until resolved.

2016-11-01 21:45 UTC, gabelula commented
I wonder if we should also add "children" to the comment's model (we have parent right now).

2016-11-02 16:38 UTC, gabelula commented
Anything else to be able to merge this one? @wyattjoh @okbel @jde

2016-11-02 18:19 UTC, okbel commented on models/comments.js
> +'use strict';
This file must be `comment.js` instead of `commentS.js`

2016-11-02 18:24 UTC, gabelula commented on models/comments.js
> +'use strict';
Done

2016-11-02 20:48 UTC, riley requested changes
just one little thing I see

2016-11-02 20:48 UTC, riley commented on models/action.js
> +ActionSchema.methods.findById = function(id) {
this should be a static e.g. `ActionSchema.statics.findById = function (id) {`

2016-11-02 21:18 UTC, riley approved these changes

2016-11-02 22:42 UTC, wyattjoh approved these changes

2016-11-02 22:43 UTC, merged