[CORL 133] API Review
coralproject/talk pull request #2197
Opened 2019-02-14 00:49 UTC by wyattjoh

## What does this PR do?

- Removed Management API
- Simplified Tenant APIs

2019-03-08 23:21 UTC, alinhle requested changes
Looks good, just a view comments

2019-03-08 23:21 UTC, alinhle commented on src/core/client/stream/test/comments/postLocalReply.spec.tsx
> +      createCommentReply: createSinonStub(
This looks like a merge error, the removed side looks like the newer one.

2019-03-08 23:21 UTC, alinhle commented on src/core/client/stream/test/comments/postLocalReply.spec.tsx
> +      createCommentReply: createSinonStub(
Except replacing `cursor: null` with `cursor: ""`

2019-03-08 23:21 UTC, alinhle commented on src/core/server/app/router/api/auth.ts
> -    options.passport.authenticate("jwt", { session: false }),
Just checking, this line is not required anymore?

2019-03-08 23:21 UTC, alinhle commented on src/core/server/graph/tenant/context.ts
> +  scraper: ScraperQueue;
Should these be `mailerQueue` and `scraperQueue`?

2019-03-11 17:45 UTC, wyattjoh commented on src/core/client/stream/test/comments/postLocalReply.spec.tsx
> +      createCommentReply: createSinonStub(
I'm still a bit unclear, can you take a stab at resolving this one?

2019-03-11 21:37 UTC, wyattjoh commented on src/core/server/app/router/api/auth.ts
> -    options.passport.authenticate("jwt", { session: false }),
It's replaced with this one:

https://github.com/coralproject/talk/blob/792778818fdf4f7da8d58393040fd20fb5e441c6/src/core/server/app/router/api/index.ts#L46-L48

2019-03-12 09:20 UTC, cvle commented on src/core/client/stream/test/comments/postLocalReply.spec.tsx
> +      createCommentReply: createSinonStub(
Sure!

2019-03-12 13:46 UTC, alinhle approved these changes

2019-03-12 14:12 UTC, merged