Design Pass Admin
coralproject/talk pull request #242
Opened 2017-01-17 16:09 UTC by okbel

# Design Pass Admin

Consider: 
- `react-mdl` is hard to override
- Avoid using `react-mdl`. Use `coral-ui` instead. 
- If that component doesn’t exist, let’s create it! :)

## New UI components
- List
  - Item
- Card
- Pager

Old Code without using `coral-ui` and overriding `react-mdl`
```js
            <List>
              <ListItem className={`${styles.settingOption} ${activeSection === 'comments' ? styles.active : ''}`}>
                <ListItemContent
                  onClick={this.changeSection('comments')}
                  icon='settings'>{lang.t('configure.comment-settings')}</ListItemContent>
              </ListItem>
              <ListItem className={`${styles.settingOption} ${activeSection === 'embed' ? styles.active : ''}`}>
                <ListItemContent
                  onClick={this.changeSection('embed')}
                  icon='code'>{lang.t('configure.embed-comment-stream')}</ListItemContent>
              </ListItem>
              <ListItem className={`${styles.settingOption} ${activeSection === 'wordlist' ? styles.active : ''}`}>
                <ListItemContent
                  onClick={this.changeSection('wordlist')}
                  icon='settings'>{lang.t('configure.wordlist')}</ListItemContent>
              </ListItem>
            </List>

```

Beautiful usage of `coral-ui`

```js
            <List onChange={this.changeSection}>
              <Item itemId='comments' icon="settings">
                {lang.t('configure.comment-settings')}
              </Item>
              <Item itemId='embed' icon='code'>
                {lang.t('configure.embed-comment-stream')}
              </Item>
              <Item itemId='wordlist' icon='settings'>
                  {lang.t('configure.wordlist')}
              </Item>
            </List>
```

## How to test this?

- Fetch: `git fetch`
- Switch to `design-pass-adm` branch `git checkout design-pass-adm`
- Log in as Admin
- Go to `/admin`
- Check the functionality 

### Note:
After merging this, @IAmSamHankins and @egrdina can take a look and give feedback

2017-01-17 18:09 UTC, kgardnr approved these changes
Love it! Beautiful!

2017-01-17 19:05 UTC, riley requested changes
nice! I left a few ideas/suggestions

2017-01-17 19:05 UTC, riley commented on client/coral-admin/src/components/CommentList.css
> +  &:hover {
should we be using `.sass` or `.scss` file extensions if we're using Sass syntax? I had no idea I could do this.

2017-01-17 19:05 UTC, riley commented on client/coral-admin/src/components/ui/Logo.js
> +      <CoralLogo stroke="#E5E5E5" height="35px" width="35px" />
could we put this into a class?

2017-01-17 19:05 UTC, riley commented on client/coral-admin/src/containers/Community/Community.css
> +  display: flex;
I thought that our postcss plugin would do these cross-browser things for us?

2017-01-17 19:05 UTC, riley commented on client/coral-admin/src/containers/Configure/Configure.css
> +  color: #00796b;
can we make these sass variables? or can we use the css variables syntax with postcss?

2017-01-17 19:10 UTC, okbel commented on client/coral-admin/src/components/CommentList.css
> +  &:hover {
Me either, I saw one of @impronunciable and I was like woah.

2017-01-17 19:11 UTC, okbel commented on client/coral-admin/src/components/ui/Logo.js
> +      <CoralLogo stroke="#E5E5E5" height="35px" width="35px" />
It loses the magic. But yes we can. I'll add it in a sec

2017-01-17 19:11 UTC, okbel commented on client/coral-admin/src/containers/Community/Community.css
> +  display: flex;
Not sure. Deleting.

2017-01-17 19:12 UTC, okbel commented on client/coral-admin/src/containers/Configure/Configure.css
> +  color: #00796b;
Yes, we will add a file with all of our CSS Vars but this will not enter in this PR.

2017-01-17 19:22 UTC, okbel commented on client/coral-admin/src/components/CommentList.css
> +  &:hover {
Let me dive deeper about this concept before renaming all the files. We can do that in another PR.

2017-01-17 19:55 UTC, okbel commented
Ready to be tested! Thanks @riley /cc @kgardnr

2017-01-19 17:20 UTC, riley commented
Just two quick fixes:
the Streams dropdowns look weird in Firefox
![Uploading Screen Shot 2017-01-19 at 10.17.32 AM.png…]()

there's a missing key error in the console in the Pending comments tab in the mod queue
![screen shot 2017-01-19 at 10 19 50 am](https://cloud.githubusercontent.com/assets/282503/22117343/d9022878-de30-11e6-87dc-3e4ac71fd5af.png)

2017-01-19 17:21 UTC, kgardnr commented
@riley / @okbel let's leave the FF bug for now, and just fix the Pending key issue ^, so we can get this merged, please. Thanks!

2017-01-19 17:31 UTC, kgardnr commented
We will address those 2 issues in another PR. I'm merging.

2017-01-19 17:31 UTC, riley approved these changes

2017-01-19 17:31 UTC, merged