[CORL-220] Change email address
coralproject/talk pull request #2461
Opened 2019-08-12 16:38 UTC by tessalt

## What does this PR do?
- allows user to change their own email address provided they correctly enter their password
- sets `emailVerified` to false and sends out a new email verification email
- gives user the option to re-send email verification if their email address is unverified.

## How do I test this PR?
- visit profile tab
- click "edit" next to email 
- fill out a new email address and enter password
- you should see a notice about email verification

Very similar to change username PR, with additional step on the backend of updating the user profile ID for local profiles.

2019-08-14 21:00 UTC, wyattjoh requested changes
Some feedback for you!

2019-08-14 21:00 UTC, wyattjoh commented on src/core/client/stream/tabs/Profile/ChangeEmail/ChangeEmailContainer.tsx
> +                          variant="outlined"
I would also most suggest instead embedding the:

```pristine || hasValidationErrors || (hasSubmitErrors && !dirtySinceLastSubmit)```

Into a function that can be used to switch the variant/color on the button instead of switching the button itself.

2019-08-14 21:00 UTC, wyattjoh commented on src/core/server/models/user/user.ts
> +  const existingUser = await retrieveUserWithProfile(mongo, tenantID, {
This would be considered business logic that should instead live in the `services/users`.

2019-08-14 21:00 UTC, wyattjoh commented on src/core/server/models/user/user.ts
> +  const result = await collection(mongo).findOneAndUpdate(
You should wrap this in a `try/catch` that checks the error like:

https://github.com/coralproject/talk/blob/next/src/core/server/models/user/user.ts#L500

2019-08-14 21:02 UTC, wyattjoh commented on src/core/server/graph/tenant/mutators/Users.ts
> +      input.email,
```suggestion
      input.email.toLowerCase(),
```

2019-08-14 21:02 UTC, wyattjoh commented on src/core/server/graph/tenant/mutators/Users.ts
> +    updateEmailByID(ctx.mongo, ctx.tenant, input.userID, input.email),
```suggestion
    updateEmailByID(ctx.mongo, ctx.tenant, input.userID, input.email.toLowerCase()),
```

2019-08-15 21:47 UTC, wyattjoh commented on src/core/server/models/user/user.ts
> +      if (err.errmsg && err.errmsg.includes("tenantID_1_email_1")) {
This is a different index (unfortunately, I don't know the correct one), but the only reason a `11000` could be thrown in this context is a uniqueness violation on the email, so I'd just throw the `DuplicateEmailError` for any error with code `11000`.

2019-08-15 21:50 UTC, wyattjoh commented on src/core/server/errors/index.ts
> +export class CannotUpdateLocalProfile extends CoralError {
I wouldn't bother throwing a new `CoralError` for this, as it's only going to occur if a user tries to call this API directly. Throwing `new Error("cannot update profile, settings disallowed")` or something should be fine.

2019-08-15 21:50 UTC, wyattjoh commented on src/core/server/models/user/user.ts
> +      if (err.errmsg && err.errmsg.includes("tenantID_1_email_1")) {
Reference above mentioned comment on the error message.

2019-08-16 15:52 UTC, tessalt commented on src/core/client/stream/tabs/Profile/ChangeUsername/ChangeUsernameContainer.tsx
> +function enabledAuthenticationIntegrations(tenant: SettingsData): string[] {
ok so I have this function on both components (change email and change username) and I'm not sure how to share this logic without things getting fairly tangled with types and imports. The function needs to know what a tenant is, but `SettingsData` is specific to the fragment requested in each component, so I'm not sure how to abstract this out. On the server side there are generic types shared across the codebase but on the client the types are all defined based on the fragments, and these two components don't have the same fragments. I was thinking that I'd need to have a separate component that just does the show/not show logic that requests the specific fragment it needs? but then it seems like overkill to have to pass that fragment and its type around between this component and the next one up. Any thoughts?

2019-08-20 15:23 UTC, wyattjoh requested changes

2019-08-20 15:23 UTC, wyattjoh commented on src/core/server/locales/en-US/errors.ftl
> -error-rawQueryNotAuthorized = You are not authorized to execute this query.
This looks like a merge error.

2019-08-20 16:06 UTC, wyattjoh approved these changes

2019-08-20 16:28 UTC, merged