[CORL-572] Filter rejected comments from reply counts on user comment history
coralproject/talk pull request #2516
Opened 2019-09-03 14:28 UTC by nick-funk

## What does this PR do?

Updated the resolver for replyCount on comments to only include comments that fit the criteria for published comments (filters out rejected and pre-mod status comments).

## How do I test this PR?

- Create a comment using a commenter account
- Have another user reply at least twice
- Have a moderator account reject one of the replying comments
- Head back to the original, root commenter account, check their My Profile > My Comments > Comment History
- Reply count under the comment should not include the rejected comment

2019-09-03 15:00 UTC, kgardnr commented
Fixes #2512

2019-09-03 15:29 UTC, wyattjoh requested changes

2019-09-03 15:29 UTC, wyattjoh commented on src/core/server/models/comment/comment.ts
> +    .count();
Unfortunately, `.count()` can never be used in MongoDB for performance reasons. We'll have to find an alternative solution.

2019-09-04 16:12 UTC, wyattjoh approved these changes

2019-09-04 16:43 UTC, merged