[CORL 581] toggleable timestamp
coralproject/talk pull request #2561
Opened 2019-09-12 15:22 UTC by tessalt

Adds a new Timestamp component in ui/components that wraps the relative timestamp in a button which toggles between absolute and relative time. Removed now unused Timestamp component from admin. updated a loooot of specs. 
![timestamp](https://user-images.githubusercontent.com/1789029/64797568-96c2eb00-d54f-11e9-8e20-97cf5cb03004.gif)

2019-09-12 16:35 UTC, wyattjoh requested changes

2019-09-12 16:35 UTC, wyattjoh commented on src/core/client/admin/components/Timestamp.tsx
> +export default Timestamp;
Why does this component exist here and `src/core/client/ui/components/Timestamp/Timestamp.tsx`?

2019-09-12 16:37 UTC, tessalt commented on src/core/client/admin/components/Timestamp.tsx
> +export default Timestamp;
🤦‍♀ i meant to delete the one in /admin

2019-09-17 21:03 UTC, wyattjoh approved these changes

2019-09-17 21:11 UTC, merged