[CORL-90] moderator notes
coralproject/talk pull request #2601
Opened 2019-09-30 13:10 UTC by tessalt

Adds a `moderatorNotes` field to `User` and interface for creating and deleting notes in user drawer. 

<img width="611" alt="Screen Shot 2019-09-30 at 9 05 57 AM" src="https://user-images.githubusercontent.com/1789029/65881859-10394680-e362-11e9-8aeb-51f63cac3d6c.png">
<img width="616" alt="Screen Shot 2019-09-30 at 9 08 56 AM" src="https://user-images.githubusercontent.com/1789029/65881873-17605480-e362-11e9-9ef0-89d782ca6ac1.png">

2019-10-01 15:48 UTC, nick-funk reviewed
Went through and code changes look good.

Looks like a migration is needed, assuming that was held off as we need @wyattjoh 's migration PR to be merged in first. Will hold off further testing until then.

2019-10-01 16:59 UTC, tessalt commented
@nick-funk @wyattjoh added migration

2019-10-01 22:53 UTC, wyattjoh requested changes

2019-10-01 22:53 UTC, wyattjoh commented on src/core/client/admin/components/UserHistoryDrawer/UserDrawerNotesContainer.tsx
> +    [createNote, user]
You can omit the `createNote` here.

2019-10-01 22:53 UTC, wyattjoh commented on src/core/server/models/user/user.ts
> +  );
Probably good to add the guard clause from the `createModeratorNote` function that returns the `UserNotFoundError` on the falsy response of `findOneAndUpdate`.

2019-10-01 22:53 UTC, wyattjoh commented on src/core/server/services/migrate/migrations/1569947670260_add_moderator_notes_to_user.ts
> +        $exists: "moderatorNotes",
The syntax for the `$exists` operator is actually:

```suggestion
        moderatorNotes: { $exists: true },
```

2019-10-02 12:25 UTC, tessalt commented
updated

2019-10-02 16:33 UTC, wyattjoh commented on src/core/client/admin/components/UserHistoryDrawer/UserDrawerNotesContainer.css
> +  color: var(--palette-text-primary);
Firefox adds a `border-width: 2px;` when unspecified, perhaps add a `border-width: 1px;` to have it match chrome?

2019-10-02 18:19 UTC, wyattjoh approved these changes

2019-10-02 18:41 UTC, merged