[CORL-8] prevent repeat comments
coralproject/talk pull request #2632
Opened 2019-10-10 12:39 UTC by tessalt

- stores ID of user's most recent comment in redis for 6 hours 
- adds moderation step to check the body of that comment and compare it against the new comment
- throws an error if we're nudging, flags comment and witholds if not
- display "Duplicate comment" flag on comments marked as duplicates

**Question:** the expiration of the last id in redis... it makes sense in this context but I'm wondering if we might want this to be more general-purpose and have the ID _not_ expire and instead compare the createdAt in the moderation step? But then we're storing one entry indefinitely per user in redis and that could be a lot? 

How to test: 
1. log in as commenter on non-premod stream
2. post a comment
3. attempt to post the same comment
4. observe nudge, post comment anyways
5. observe message that comment will be held for moderation
6. log in as admin, comment should be marked "Duplicate comment"

2019-10-15 18:15 UTC, wyattjoh requested changes

2019-10-15 18:15 UTC, wyattjoh commented on src/core/server/services/comments/pipeline/phases/repeatPost.ts
> +  }
Not required as `req` isn't used in this phase

2019-10-15 18:15 UTC, wyattjoh commented on src/core/server/services/users/users.ts
> +  Comment as CommentModel,
You should be able to import this as `Comment` instead of aliasing it to `CommentModel`.

2019-10-15 18:15 UTC, wyattjoh commented on src/core/server/services/users/users.ts
> +    .exec();
As you aren't depending on the different results, you can instead use:

```js
await redis.set(key, commentID, "EX", COMMENT_REPEAT_POST_TIMESPAN);
```

2019-10-15 18:15 UTC, wyattjoh commented on src/core/server/services/comments/pipeline/phases/repeatPost.ts
> +    const isRepeatComment = revision.body === comment.body;
Maybe worth it for us to add a `TODO` to possibly use a package that can compare similarity for the future: https://www.npmjs.com/package/damerau-levenshtein

2019-10-15 18:15 UTC, wyattjoh commented on src/core/common/errors.ts
> +  REPEAT_POST = "REPEAT_POST",
Should add a small comment above the constant similar to the other entries in this object.

2019-10-15 18:15 UTC, wyattjoh commented on src/core/common/constants.ts
> +export const COMMENT_REPEAT_POST_TIMESPAN = 21600;
Should include comment

2019-10-15 18:33 UTC, tessalt commented on src/core/server/services/comments/pipeline/phases/repeatPost.ts
> +    const isRepeatComment = revision.body === comment.body;
the body should be processed by an earlier step in the moderation pipeline at this point so it should match with what was saved previously?

2019-10-15 20:20 UTC, wyattjoh commented on src/core/server/services/comments/pipeline/phases/repeatPost.ts
> +    const isRepeatComment = revision.body === comment.body;
That's right, mine was more of a feature suggestion/wish to support catching: "Yes" versus "yes" possibly in the future.

2019-10-16 13:16 UTC, tessalt commented
updated, the "re-request" button isn't showing up

2019-10-16 15:51 UTC, wyattjoh approved these changes

2019-10-16 15:51 UTC, merged