[CORL-575] allow line breaks in stream tabs
coralproject/talk pull request #2726
Opened 2019-11-21 15:32 UTC by tessalt

Allows line breaks in the stream tabs so that longer text (for example, in spanish) does not get cut off 
<img width="763" alt="Screen Shot 2019-11-21 at 10 29 29 AM" src="https://user-images.githubusercontent.com/1789029/69352060-3c7a9080-0c4a-11ea-8b39-0c25509686dc.png">
@IAmSamHankins

2019-11-21 21:57 UTC, nick-funk approved these changes

2019-11-22 18:37 UTC, wyattjoh requested changes
Looks a bit odd with the line breaking too early, and the filter button popping up earlier now?

![Screen Shot 2019-11-22 at 11 36 17 AM](https://user-images.githubusercontent.com/633002/69451368-17277880-0d57-11ea-8fc7-f49224e00a60.png)
![Screen Shot 2019-11-22 at 11 35 51 AM](https://user-images.githubusercontent.com/633002/69451369-17277880-0d57-11ea-88b7-22f20dd4c6a1.png)

2019-11-25 17:09 UTC, tessalt commented
@wyattjoh ok i've come up with a slightly different solution that keeps the sort options bottom-aligned and prevents the tab from breaking lines if it has space not to

2019-11-25 23:59 UTC, wyattjoh approved these changes

2019-11-26 15:01 UTC, merged