Verify Email upon signup
coralproject/talk pull request #274
Opened 2017-01-31 19:11 UTC by riley

## What does this PR do?

- adds a setting in the admin to enable email verification for new users
- email is sent to new users upon sign up
- clicking the link will confirm your account
- if the user got distracted upon signing up the first time, or lost the email, they can request a new one after trying to sign in with the right credentials

## How do I test this PR?

- turn on Require Email Confirmation in the admin
- create a new user
- click the confirm link in your email
- try to log in again. it should work.

2017-01-31 19:48 UTC, davidgljay commented
After verifying my e-mail I'm redirected to 'http://localhost:3000/admin/undefined'. Is this intentional?

2017-01-31 19:59 UTC, davidgljay requested changes
Remove a console.log and address issue with resent confirmation e-mail dialog not closing.

2017-01-31 19:59 UTC, davidgljay commented on client/coral-sign-in/containers/SignInContainer.js
> +    console.log('handleChangeEmail', value);
This should be removed.

2017-01-31 19:59 UTC, davidgljay commented on client/coral-sign-in/containers/SignInContainer.js
> +    this.props.requestConfirmEmail(this.state.emailToBeResent);
This doesn't seem to give the user a confirmation or close the dialog. It should probably do one or both.

2017-01-31 19:59 UTC, wyattjoh reviewed
Should handle the state where the referer isn't defined or isn't a url first, possibly create a validateReferer method to the SettingsService and call out to it?

2017-01-31 20:32 UTC, wyattjoh requested changes

2017-01-31 20:32 UTC, wyattjoh commented on services/users.js
> +  static createEmailConfirmToken(userID = null, email, referer) {
Should default to something here if referer isn't provided.

2017-01-31 20:32 UTC, wyattjoh commented on routes/api/users/index.js
> +    redirectUri,
Should source this from the `Referrer` header, not a payload option.

2017-01-31 20:40 UTC, riley commented on routes/api/users/index.js
> +    redirectUri,
whoops, good catch. I removed that from somewhere else when I was moving things around and forgot to re-add it here.

2017-01-31 21:53 UTC, wyattjoh approved these changes

2017-02-01 17:09 UTC, davidgljay approved these changes

2017-02-01 17:13 UTC, merged