[CORL-758] Show new comments in stream when sorting by oldest
coralproject/talk pull request #2740
Opened 2019-12-02 23:39 UTC by nick-funk

## What does this PR do?

Push approved/new comments to the end of the stream when sorting by oldest.

## How do I test this PR?

1. Go to an non-pre-modded stream
2. Select Sort By: Oldest
3. Create a new comment that won't get flagged for toxicity
4. See the comment at bottom of stream above the "Load More" button

2019-12-02 23:41 UTC, nick-funk commented on src/core/client/stream/tabs/Comments/Stream/PostCommentForm/CreateCommentMutation.ts
> +  if (input.commentsOrderBy === "CREATED_AT_ASC") {
`commentsOrderBy` can be null, so we only do this if it's an exact match.

Hence the duplicate `getConnection(...)` rigamarole.

2019-12-03 17:40 UTC, wyattjoh requested changes

2019-12-03 17:40 UTC, wyattjoh commented on src/core/server/graph/tenant/schema/schema.graphql
> +
This should not be passed to the server, this is purely a client side parameter.

2019-12-03 21:13 UTC, wyattjoh approved these changes

2019-12-03 21:57 UTC, merged