Adds a screen to create username after facebook signup
coralproject/talk pull request #277
Opened 2017-01-31 22:07 UTC by gabelula

## What does this PR do?

- Adds a dialog window after singup to create/modify display Name.

## How do I test this PR?

- Signup with facebook
- Check that the dialog is there
- Change your display name
- Check that it was changed.

Story: https://www.pivotaltracker.com/story/show/134624635

2017-02-01 19:13 UTC, riley requested changes
you have to show the error for when a username has profanity in it.

![screen shot 2017-02-01 at 12 12 13 pm](https://cloud.githubusercontent.com/assets/282503/22522153/d597f37e-e877-11e6-83c9-a59862ed9b68.png)

Also have to show the error when there are special characters in the displayName

![screen shot 2017-02-01 at 12 13 52 pm](https://cloud.githubusercontent.com/assets/282503/22522196/fe8eb826-e877-11e6-89f6-afbeada7033f.png)

2017-02-01 21:21 UTC, gabelula commented
Done. Ready to review.

2017-02-01 21:32 UTC, riley requested changes
the code looks good, just some organizational stuff requested

2017-02-01 21:32 UTC, riley commented on client/coral-framework/actions/auth.js
> +const createDisplayNameSuccess = () => ({type: actions.CREATEDISPLAYNAME_SUCCESS});
would you mind moving these two actions up to line 12 so that they're grouped in the code with the other fetch actions?

2017-02-01 21:32 UTC, riley commented on client/coral-framework/components/CreateDisplayNameDialog.js
> +import React from 'react';
These components probably make more sense to live in the `coral-plugin-sign-in` folder since that's where a lot of similar code is from.

2017-02-01 21:32 UTC, riley commented on client/coral-framework/components/FormField.js
> +const FormField = ({className, showErrors = false, errorMsg, label, ...props}) => (
Is it possible to use the `FormField` from `coral-ui`?

2017-02-01 21:32 UTC, riley commented on client/coral-framework/containers/ChangeDisplayNameContainer.js
> +import React, {Component} from 'react';
This could move to `coral-plugin-sign-in` along with the styles too

2017-02-01 21:33 UTC, riley commented on client/coral-framework/components/FormField.js
> +const FormField = ({className, showErrors = false, errorMsg, label, ...props}) => (
you could probably get away with deleting this altogether if you used the `coral-ui` one

2017-02-02 17:21 UTC, davidgljay commented
Language question: is it a username or a display name? We should choose one and stick to it.

2017-02-03 00:10 UTC, riley approved these changes
lgtm 💯

2017-02-03 18:55 UTC, merged