[CORL-882] option to reject all a user's comments when banning
coralproject/talk pull request #2827
Opened 2020-02-06 17:51 UTC by tessalt

## What does this PR do?
- Adds a checkbox to the "ban user" modal to enable the option
- if checked, a job is queued to reject all the user's existing comments  

## How do I test this PR?
- create a user with one or more comments
- ban this user, selecting "reject all this users comments"
- check "rejected" queue to ensure comments are rejected

2020-02-18 20:12 UTC, nick-funk approved these changes

2020-02-18 20:12 UTC, nick-funk commented
Looks great and works like a charm!

2020-02-20 22:12 UTC, wyattjoh requested changes

2020-02-20 22:12 UTC, wyattjoh commented on src/core/server/graph/schema/schema.graphql
> +  rejectExistingComments: Boolean!
Documentation is needed for this parameter. This could also me made nullable if desired:

```suggestion
  rejectExistingComments: Boolean
```

2020-02-20 22:12 UTC, wyattjoh commented on src/core/server/queue/index.ts
> +  redis: AugmentedRedis;
Change not needed, see below.

2020-02-20 22:12 UTC, wyattjoh commented on src/core/server/queue/tasks/rejector.ts
> +  redis: AugmentedRedis;
Use instead:

```suggestion
  redis: Redis;
```

2020-02-20 22:12 UTC, wyattjoh commented on src/core/server/queue/tasks/rejector.ts
> +  log.debug("starting to reject author comments");
Double log.

2020-02-20 22:12 UTC, wyattjoh commented on src/core/server/queue/tasks/rejector.ts
> +// import { Publisher } from "coral-server/graph/subscriptions/publisher";
Removed commented out import.

2020-02-20 22:12 UTC, wyattjoh commented on src/core/server/queue/tasks/rejector.ts
> +  return retrieveStatusCommentConnection(
You can use `retrieveAllCommentsUserConnection` instead of having to filter for specific statuses.

2020-02-20 22:12 UTC, wyattjoh commented on src/core/server/stacks/rejectComment.ts
> +  }
Should add a `TODO` about why this was added, because the broker is too complex now. Include a reference to CORL-935.

2020-02-21 16:36 UTC, tessalt commented on src/core/server/queue/index.ts
> +  redis: AugmentedRedis;
the `rejectComment` stack requires augmented redis

2020-02-21 17:20 UTC, wyattjoh approved these changes

2020-02-21 17:38 UTC, merged