[WIP] [CORL-1108] embeds
coralproject/talk pull request #3010
Opened 2020-07-06 17:01 UTC by tessalt

## What does this PR do?

## What changes to the GraphQL/Database Schema does this PR introduce?

## How do I test this PR?

2020-07-10 21:24 UTC, nick-funk commented
I'm getting an infinite spinner when trying to load the General page under Admin > Config

<img width="685" alt="image" src="https://user-images.githubusercontent.com/5751504/87204188-7378e180-c2c1-11ea-893f-52fd4633b5a5.png">

2020-07-10 21:33 UTC, nick-funk commented
<img width="673" alt="image" src="https://user-images.githubusercontent.com/5751504/87204678-a2438780-c2c2-11ea-96db-62b85287cb73.png">

If you forget to set an API key for GIPHY and a user tries to search for a GIF, the stream will crash.

```
[2020-07-10T21:32:22.408Z] ERROR: coral/14599 on MacBook-Pro.localdomain(/Users/nickfunk/code/talk/src/core/server/app/middleware/logging.ts:41 in exports.errorLogger): http error (context=http, contextID=d70e5170-c2f4-11ea-a249-ed1dc95cdada, tenantID=561ee745-3d24-4049-bfa7-2dd02bda5ca8, url=/api/remote-media/gifs?query=enterpris&offset=0, method=GET, statusCode=200, host=localhost, ip=::ffff:127.0.0.1)
    userAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:78.0) Gecko/20100101 Firefox/78.0
    --
    err: {
      "message": "Must configure API key",
      "name": "Error",
      "stack": "exports.gifSearchHandler (src/core/server/app/handlers/api/remoteMedia/index.ts:24:17)\nLayer.handle [as handle_request] (node_modules/express/lib/router/layer.js:95:5)\nnext (node_modules/express/lib/router/route.js:137:13)\nRoute.dispatch (node_modules/express/lib/router/route.js:112:3)\nLayer.handle [as handle_request] (node_modules/express/lib/router/layer.js:95:5)\nnode_modules/express/lib/router/index.js:281:22\nFunction.process_params (node_modules/express/lib/router/index.js:335:12)\nnext (node_modules/express/lib/router/index.js:275:10)\nexports.noCacheMiddleware (src/core/server/app/middleware/cacheHeaders.ts:13:3)\nLayer.handle [as handle_request] (node_modules/express/lib/router/layer.js:95:5)\ntrim_prefix (node_modules/express/lib/router/index.js:317:13)\nnode_modules/express/lib/router/index.js:284:7\nFunction.process_params (node_modules/express/lib/router/index.js:335:12)\nnext (node_modules/express/lib/router/index.js:275:10)\nFunction.handle (node_modules/express/lib/router/index.js:174:3)\nrouter (node_modules/express/lib/router/index.js:47:12)\n"
    }
```

2020-07-10 21:39 UTC, nick-funk commented
I've set my content rating for gifs to `G` and yet I seem to still find a lot of gif's with swear words and other nastiness. Not sure if this is the content rating search not working properly or just bad filters on Giphy's end.

<img width="699" alt="image" src="https://user-images.githubusercontent.com/5751504/87204928-62c96b00-c2c3-11ea-99b0-892718322321.png">
<img width="715" alt="image" src="https://user-images.githubusercontent.com/5751504/87204948-6bba3c80-c2c3-11ea-8494-b1ec9d9bacab.png">

2020-07-10 21:48 UTC, nick-funk commented
Youtube embeds don't seem to show when I click `+ Show Video`

<img width="694" alt="image" src="https://user-images.githubusercontent.com/5751504/87205439-affa0c80-c2c4-11ea-9674-2ea75fe9f8b6.png">

2020-07-10 22:00 UTC, nick-funk requested changes

2020-07-10 22:00 UTC, nick-funk commented on src/core/client/admin/components/ModerateCard/Embed.tsx
> +              <source src={video} type="video/mp4" />
Whoo!

2020-07-10 22:00 UTC, nick-funk commented on src/core/client/stream/tabs/Comments/GifSelector/GifPreview.css
> +.image {
Might be able to remove this if you have time

2020-07-10 22:00 UTC, nick-funk commented on src/core/client/stream/tabs/Comments/Stream/PostCommentForm/CreateCommentMutation.ts
> +            body: input.body || "",
Have we changed the back-end to treat empty strings the way we used to treat `undefined`?

Is this part of removing the `<br/>` at the end of comments?

2020-07-10 22:00 UTC, nick-funk commented on src/core/client/stream/tabs/Comments/helpers/getCommentBodyValidators.ts
> +  return v !== "" && v !== null && v !== undefined;
👍

2020-07-10 22:00 UTC, nick-funk commented on src/core/client/stream/tabs/Profile/MyComments/DownloadCommentsContainer.css
> +.content {
Maybe remove this if you have time

2020-07-10 22:00 UTC, nick-funk commented on src/core/server/services/comments/pipeline/helpers.ts
> +  if (!isUndefined(result.body)) {
💯

2020-07-10 22:00 UTC, nick-funk commented on src/core/server/services/giphy/giphy.ts
> +    }
👍

2020-07-10 22:01 UTC, nick-funk commented on src/core/client/stream/tabs/Comments/Stream/PostCommentForm/CreateCommentMutation.ts
> +            body: input.body || "",
I think I found the solution to this, there's new checks on the `getCommentBodyValidators` now

2020-07-13 12:33 UTC, tessalt commented
> I'm getting an infinite spinner when trying to load the General page under Admin > Config
> 
> <img alt="image" width="685" src="https://user-images.githubusercontent.com/5751504/87204188-7378e180-c2c1-11ea-893f-52fd4633b5a5.png">
> 
> ```
> [2020-07-10T21:25:55.312Z] ERROR: coral/11553 on MacBook-Pro.localdomain(/Users/nickfunk/code/talk/src/core/server/graph/extensions/LoggerExtension.ts:15 in logError): graphql query error (context=graph, contextID=f04f6d00-c2f3-11ea-9cc1-19199095a44f, tenantID=561ee745-3d24-4049-bfa7-2dd02bda5ca8)
>     err: {
>       "message": "Cannot return null for non-nullable field EmbedConfiguration.giphyMaxRating.",
>       "name": "GraphQLError",
>       "originalError": {
>         "message": "Cannot return null for non-nullable field EmbedConfiguration.giphyMaxRating.",
>         "name": "Error",
>         "stack": "completeValue (node_modules/graphql/execution/execute.js:560:13)\ncompleteValueCatchingError (node_modules/graphql/execution/execute.js:495:19)\nresolveField (node_modules/graphql/execution/execute.js:435:10)\nexecuteFields (node_modules/graphql/execution/execute.js:275:18)\ncollectAndExecuteSubfields (node_modules/graphql/execution/execute.js:713:10)\ncompleteObjectValue (node_modules/graphql/execution/execute.js:703:10)\ncompleteValue (node_modules/graphql/execution/execute.js:591:12)\ncompleteValue (node_modules/graphql/execution/execute.js:557:21)\ncompleteValueCatchingError (node_modules/graphql/execution/execute.js:495:19)\nresolveField (node_modules/graphql/execution/execute.js:435:10)\nexecuteFields (node_modules/graphql/execution/execute.js:275:18)\ncollectAndExecuteSubfields (node_modules/graphql/execution/execute.js:713:10)\ncompleteObjectValue (node_modules/graphql/execution/execute.js:703:10)\ncompleteValue (node_modules/graphql/execution/execute.js:591:12)\ncompleteValue (node_modules/graphql/execution/execute.js:557:21)\ncompleteValueCatchingError (node_modules/graphql/execution/execute.js:495:19)\n"
>       }
>     }
> ```

2020-07-13 16:32 UTC, nick-funk approved these changes
This appears to all be working with the recent fixes! Approved!

2020-07-13 17:00 UTC, wyattjoh commented on src/core/server/app/handlers/api/remoteMedia/index.ts
> +  }
Duplicate.

2020-07-13 17:00 UTC, wyattjoh commented on src/core/server/services/giphy/giphy.ts
> +  locale: LanguageCode
Services in the `server/services` folder can accept the whole `tenant: Tenant` instead of field splitting here, I'd suggest swapping that out to make it easier to call.

2020-07-13 17:00 UTC, wyattjoh commented on src/core/client/framework/helpers/findEmbedLinks.ts
> +  const twitterRegex = /(https?:\/\/)?(www\.)?(twitter\.com\/[a-zA-z0-9]+\/status\/[0-9]+)/g;
Move RegExp construction above the function.

2020-07-13 17:00 UTC, wyattjoh commented on src/core/server/app/helpers/findEmbedLinks.ts
> +}
Remove in favour of putting in `src/core/common`.

2020-07-13 17:00 UTC, wyattjoh commented on src/core/client/framework/helpers/findEmbedLinks.ts
> +export function findEmbedLinks(body: string): EmbedLink[] {
Move to `src/core/common`.

2020-07-13 17:00 UTC, wyattjoh commented on src/core/server/app/router/api/index.ts
> +  router.get("/oembed", oembedHandler());
Capitalization must be consistent throughout the filename/exports. Rename files/folders down from `api/oEmbed/oEmbed` to `api/oembed/oembed`.

2020-07-13 17:00 UTC, wyattjoh commented on src/core/server/graph/mutators/Comments.ts
> +          embeds: comment.embed ? [comment.embed] : [],
Might want to standardize this transform.

2020-07-13 17:00 UTC, wyattjoh commented on src/core/server/graph/schema/schema.graphql
> +  giphyAPIKey: String
I would suggest breaking these out to `TwitterEmbedConfiguration`, `YouTubeEmbedConfiguration`, and `GiphyEmbedConfiguration` to standardize the `enabled: Boolean!` and fixing the `giphy*` prefixing.

2020-07-13 17:00 UTC, wyattjoh commented on src/core/server/graph/schema/schema.graphql
> +  GIPHY
Comments are required.

2020-07-13 17:00 UTC, wyattjoh commented on src/core/server/graph/schema/schema.graphql
> +  remote_id: String
CamelCase is required for all field names across the schema.

2020-07-13 17:00 UTC, wyattjoh commented on src/core/server/graph/schema/schema.graphql
> +}
We should adjust the types here. We can chat about this one.

2020-07-13 17:00 UTC, wyattjoh commented on src/core/server/graph/schema/schema.graphql
> +}
These should be stored as `Int` and not `String`'s.

2020-07-13 17:00 UTC, wyattjoh commented on src/core/server/graph/schema/schema.graphql
> +  remote_id: String
CamelCase is required on the schema.

2020-07-13 17:00 UTC, wyattjoh commented on src/core/server/graph/schema/schema.graphql
> +  giphyMaxRating: GIPHY_RATING!
We can store this as a string for now (we don't typically create enums for external properties).

2020-07-13 17:00 UTC, wyattjoh commented on src/core/server/models/comment/revision.ts
> +}
This looks pretty identical to the Graph generated interface, prefer that over this one.

2020-07-13 17:00 UTC, wyattjoh commented on src/core/server/services/comments/pipeline/phases/commentLength.ts
> +    }
Must still check for maximum length if Giphy is enabled.

2020-07-13 17:00 UTC, wyattjoh commented on src/core/server/services/comments/pipeline/phases/embed.ts
> +        throw new Error("Cannot attach gif");
Should instead throw a `WrappedInternalError` to wrap the other error.

2020-07-13 17:00 UTC, wyattjoh commented on src/core/server/services/comments/pipeline/phases/linkify.ts
> +  body: bodyText.trim().length > 0 ? linkifyjs(comment.body, config) : "",
Wrap in function `{}` instead of object return with ternary.

2020-07-13 17:00 UTC, wyattjoh commented on src/core/server/services/comments/pipeline/phases/repeatPost.ts
> +  if (!bodyText && (!embeds || embeds.length === 0)) {
Suggest adding `bodyText.trim()` when it is created.

2020-07-13 17:00 UTC, wyattjoh commented on src/core/server/services/comments/pipeline/phases/repeatPost.ts
> +    if (!lastComment || action === "EDIT") {
Double check what this is for.

2020-07-13 17:00 UTC, wyattjoh commented on src/core/server/services/comments/pipeline/phases/repeatPost.ts
> +    if (bodyText && compareTo.length > 0) {
Double check this.

2020-07-13 17:00 UTC, wyattjoh commented on src/core/server/services/comments/pipeline/phases/repeatPost.ts
> +      similarity =
You don't need to return a similarity if it's easier.

2020-07-13 17:00 UTC, wyattjoh commented on src/core/server/services/giphy/giphy.ts
> +  ];
Move outside function.

2020-07-13 17:00 UTC, wyattjoh commented on src/core/server/services/giphy/giphy.ts
> +    const data = await res.json();
Should set a specific type for the returned data and validate the shape with `Joi.validate`.

2020-07-13 17:00 UTC, wyattjoh commented on src/core/server/services/giphy/giphy.ts
> +export async function fetchFromGiphy(id: string, apiKey: string) {
```suggestion
export async function retrieveFromGiphy(id: string, apiKey: string) {
```

2020-07-13 17:00 UTC, wyattjoh commented on src/core/server/services/giphy/giphy.ts
> +    const result = await res.json();
Validate data and return specific type.

2020-07-13 17:00 UTC, wyattjoh commented on src/core/server/services/migrate/migrations/1594643064750_add_embeds_config.ts
> +}
Remove in favour of making the `embeds` config optional.

2020-07-13 17:00 UTC, wyattjoh commented on src/core/server/services/oembed/oembed.ts
> +    )}&maxWidth=240`;
Check what this is for.

2020-07-13 17:00 UTC, wyattjoh commented on src/core/server/services/oembed/oembed.ts
> +const fetchURL = (url: string, type: string) => {
```suggestion
const fetchURL = (url: string, type: "twitter" | "youtube") => {
```

2020-07-13 17:00 UTC, wyattjoh commented on src/core/server/services/oembed/oembed.ts
> +  const fetch = createFetch({ name: "oembed-fetch" });
Move outside function.

2020-07-13 19:42 UTC, nick-funk commented on src/core/client/framework/helpers/findEmbedLinks.ts
> +  const twitterRegex = /(https?:\/\/)?(www\.)?(twitter\.com\/[a-zA-z0-9]+\/status\/[0-9]+)/g;
@wyattjoh, just for the record, pretty sure this was me that put this in the wrong place. @tessalt just inherited my mess.

2020-07-15 00:33 UTC, wyattjoh approved these changes

2020-07-15 02:16 UTC, merged