[CORL-1155] Fix theming for rebranded stream/admin
coralproject/talk pull request #3012
Opened 2020-07-09 22:03 UTC by nick-funk

## What does this PR do?

Fixes multiple issues with css variables and component duplication to allow theming within the stream.

## What changes to the GraphQL/Database Schema does this PR introduce?

None

## How do I test this PR?

2020-07-10 17:53 UTC, tessalt approved these changes

2020-07-10 17:53 UTC, tessalt commented on src/core/client/admin/routes/ForgotPassword/ForgotPasswordForm.tsx
> +                    variant="regular"
"regular" is the default for size/variant/color.

2020-07-15 00:32 UTC, wyattjoh requested changes

2020-07-15 00:32 UTC, wyattjoh commented on CSS_VARIABLES.md
> +`--palette-negative-100: #FCE5D9;  /* Before 6.3.0: --palette-error-lightest */`
The use of `negative` and `positive` is inconsistent with existing verbiage around colours. The proximity to numbers is especially confusing (i.e.`negative 100`).

Please revert to `error`/`success` naming.

2020-07-15 16:53 UTC, wyattjoh approved these changes

2020-07-15 18:20 UTC, merged