Load more comments
coralproject/talk pull request #306
Opened 2017-02-13 18:42 UTC by davidgljay

## What does this PR do?

Loads only 10 comments initially and adds a "load more" button to load more in batches of 10.

## How do I test this PR?

1. Go to a comment stream with less than 10 comments.
2. Load More button should not be visible.
3. Comment until there are > 10 comments.
4. Load more button should be visible.
5. Clicking the button should load more comments.

2017-02-14 22:44 UTC, riley commented
the big thing that I noticed was if there are 10 comments on an article and you make the 11th, it hides the first comment, and you can only get it back when you click View more. I spoke with the designers and it seems more intuitive to just add them to the stack instead of hitting the server for a comment that was visible only a second ago.

2017-02-14 23:43 UTC, davidgljay commented
@riley PropTypes don't do anything on stateless components (though we could keep them there purely for devleoper reference.)

2017-02-14 23:46 UTC, davidgljay commented
@riley I'd like to fix the issue you mentioned in a seperate PR. Right now we refetch after posting a comment, we should inject that comment directly through updateQuery. That'll avoid a number of cases where post a comment or reply makes things disappear.

2017-02-14 23:47 UTC, davidgljay commented
Closed on accident!

2017-02-14 23:56 UTC, riley commented
@davidgljay `propTypes` work on stateless components. Try setting one to `isRequired` and then not including it. It doesn't break, but it'll give a warning.

2017-02-14 23:57 UTC, davidgljay commented
@riley Really?? That's fantastic. I remember researching it earlier and that wasn't the case. Good to know.

2017-02-15 00:10 UTC, riley commented
I think earlier versions of React didn't when they first rolled out
stateless components.

On Tue, Feb 14, 2017 at 4:57 PM David Jay <notifications@github.com> wrote:

> @riley <https://github.com/riley> Really?? That's fantastic. I remember
> researching it earlier and that wasn't the case. Good to know.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/coralproject/talk/pull/306#issuecomment-279875354>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AARPh4OnrvDFNuqshGOT1jX-tyVUd9Bdks5rcj9VgaJpZM4L_keb>
> .
>
-- 
Sorry for typos; on my phone

2017-02-15 01:30 UTC, riley commented on scripts/pree2e.sh
> +mongo test --eval "db.dropDatabase()"
💯 oonz oonz oonz

2017-02-15 13:22 UTC, okbel requested changes

2017-02-15 13:22 UTC, okbel commented on client/coral-embed-stream/src/Embed.js
> +            asset_id={asset.id}
We are using CamelCase convention. This would be `assetId`.

2017-02-15 13:22 UTC, okbel commented on test/e2e/tests/EmbedStreamTests.js
> +  // Commenting out this test, it fails if the notification is below the fold, which
We will get back and review how to approach to this test after the Test Meeting

2017-02-15 13:22 UTC, okbel commented on client/coral-embed-stream/src/Embed.js
> +            moreComments={asset.commentCount > asset.comments.length}
Isn't the `commentCount` the total comment count? This will be always greater than the length of the comments array if the limit is 5.

2017-02-15 15:30 UTC, jde commented on client/coral-embed-stream/src/Embed.js
> +            moreComments={asset.commentCount > asset.comments.length}
This is a bit confusing, but stems from a product decision. The call was only to include top level comments in the commentCount we show in the tab and not count children.

So, the variable name is misleading, but the confusion stems from our comment counting methodology.

2017-02-15 15:35 UTC, okbel commented on client/coral-embed-stream/src/Embed.js
> +            moreComments={asset.commentCount > asset.comments.length}
👍

2017-02-15 18:25 UTC, davidgljay commented on test/e2e/tests/EmbedStreamTests.js
> +  // Commenting out this test, it fails if the notification is below the fold, which
Once we are clearing the DB between tests this wont't be an issue.

2017-02-15 18:29 UTC, davidgljay commented on client/coral-embed-stream/src/Embed.js
> +            moreComments={asset.commentCount > asset.comments.length}
@okbel Once you hit "load more" the coments array can be greater than 5, so this is essentially saying "is the commentCount greater than the number of comments currently loaded?"

2017-02-15 19:02 UTC, okbel approved these changes

2017-02-15 19:11 UTC, merged