[CORL-1227] Disable background scrolling on site moderators modal
coralproject/talk pull request #3069
Opened 2020-08-03 19:49 UTC by nick-funk

## What does this PR do?

Adds a `disableScroll` option onto modals and uses it for the `SiteModeratorModal`.

The site moderator modal already has a scroll bar inside it and its height is less than 480px. We don't need a scrollbar on the modal background since the modal window will always be fully visible on even the smallest screens.

This eliminates the bug of the modal sliding away when there are enough sites in the org to cause the background scroll to be activated.

## What changes to the GraphQL/Database Schema does this PR introduce?

None

## How do I test this PR?

- Enable the `SITE_MODERATOR` feature flag
- Create a lot of sites under your org (10-20 should do)
- Shrink the height of your window to roughly 600px
- Go to the community page
- Go to change a user's role to site moderator
- Scroll down through your massive list of sites
- See that the modal background does not have a scroll bar
- See that the modal does not scroll up and away through the top of the screen

2020-08-04 00:12 UTC, wyattjoh commented
This still seems like an issue on Google Chrome when selecting a site that's further than the first page.

![Screen Shot 2020-08-03 at 6 11 26 PM](https://user-images.githubusercontent.com/633002/89238896-d9047900-d5b4-11ea-9229-30be429e009c.png)

2020-08-04 00:13 UTC, wyattjoh requested changes
This still seems to be an issue on Google Chrome:

![Screen Shot 2020-08-03 at 6 11 26 PM](https://user-images.githubusercontent.com/633002/89238931-f46f8400-d5b4-11ea-9faa-bda4aeaee1c7.png)

2020-08-05 14:12 UTC, tessalt approved these changes
this makes sense to me

2020-08-05 15:23 UTC, wyattjoh approved these changes

2020-08-05 15:49 UTC, merged