Counts on Mod Queues
coralproject/talk pull request #321
Opened 2017-02-16 19:51 UTC by riley

## What does this PR do?

- adds a badge to the moderation queue tabs showing the count (will have to be updated when pagination lands in mod queue)
- makes the first tab Dashboard, per @IAmSamHankins 

## How do I test this PR?

- view the moderation queue
- there should be numbers next to the names of the queues

2017-02-16 20:00 UTC, okbel requested changes

2017-02-16 20:00 UTC, okbel commented on client/coral-admin/src/containers/ModerationQueue/ModerationContainer.js
> +          premodCount={data.premod.length}
Not this kind of count. This needs to come back from the server. Otherwise this will mess up the pagination.

2017-02-16 20:07 UTC, jde commented on client/coral-admin/src/containers/ModerationQueue/ModerationContainer.js
> +          premodCount={data.premod.length}
+1, the front end isn't going to hold all of the things in the queue so we can't base the count on fe data.

2017-02-16 20:20 UTC, riley commented on client/coral-admin/src/containers/ModerationQueue/ModerationContainer.js
> +          premodCount={data.premod.length}
i know, but this pr is just UI. we'll pass different ints here when pagination is added.

2017-02-16 23:54 UTC, wyattjoh commented on client/coral-admin/src/containers/ModerationQueue/ModerationContainer.js
> +          premodCount={data.premod.length}
The data is now available via the commentCount edge, observe:

```graphql
commentCount(query: {statuses: [NONE, PREMOD], action_type: FLAG})
```

2017-02-17 17:42 UTC, okbel approved these changes

2017-02-17 18:00 UTC, merged