polish translations updates
coralproject/talk pull request #3227
Opened 2020-10-19 20:46 UTC by janslu

## What does this PR do?

Updated polish translation

## What changes to the GraphQL/Database Schema does this PR introduce?

N/A

## How do I test this PR?

N/A

2020-10-20 21:16 UTC, michalnicp requested changes

2020-10-20 21:16 UTC, michalnicp commented on src/core/server/locales/pl/errors.ftl
> +error-userBioTooLong = Biogram jest zbyt długi.
```suggestion
error-userBioTooLong = Biogram jest za długi.
```

2020-10-20 21:16 UTC, michalnicp commented on src/locales/pl/stream.ftl
> +profile-changeUsername-heading-changeYourUsername = Change your username
Remove english translations.

2020-10-21 21:05 UTC, janslu commented
I have tried to push a commit with amended translation (with a fix and proposed change). I've done it for the first time and I hope I didn't screw up. Cheers

2020-10-21 21:34 UTC, wyattjoh approved these changes

2020-10-21 21:43 UTC, merged