fixed some typos and errors
coralproject/talk pull request #3296
Opened 2020-11-20 16:47 UTC by Emptyfruit

fixed some typos
added some of the missing translations (important ones)
organized stream.ttl to match the EN version in lines and sections (mostly) for future edits convenience.

## What does this PR do?

## What changes to the GraphQL/Database Schema does this PR introduce?

## How do I test this PR?

2020-11-25 13:52 UTC, Emptyfruit commented
If you don't mind me asking, where 6.6.0 can be expected to be released? This PR is vital for usage, some very basic things were messed up, including submit button. Is possible, may be this can be moved to 6.4.* minor or at least 6.5 ? I did not dare to make a PR to master, but really need these fixes asap..

2020-11-25 21:08 UTC, wyattjoh commented
Are you referring to the localization changes specifically? There's a chance we can release this change directly if it's all that's blocking you!

2020-11-26 08:10 UTC, Emptyfruit commented
Exactly, only these changes to localization. Appreciate it.

2020-11-26 16:26 UTC, wyattjoh requested changes

2020-11-26 16:26 UTC, wyattjoh commented on src/locales/ru/stream.ftl
> +  }
You should not include english text.

2020-11-26 16:26 UTC, wyattjoh commented on src/locales/ru/stream.ftl
> +profile-bio-title = Bio
Other english text.

2020-11-26 17:13 UTC, wyattjoh commented on src/locales/ru/stream.ftl
> +  .alt = Powered by giphy
English should be removed here as well.

2020-12-07 18:59 UTC, kgardnr approved these changes

2020-12-07 19:43 UTC, wyattjoh approved these changes

2020-12-07 20:17 UTC, merged

2020-12-09 06:50 UTC, Emptyfruit commented
If you don't mind ill raise the question again: can these changes be released really soon? 6.6.0 has no release date yet, but we really need it soon.

2020-12-14 15:56 UTC, Emptyfruit commented
Sorry, guys, once again, our deadline is in a week. I see that 6.6.0 is almost done but has no release date. May be my changes can be merged into 6.5.1 ?

2020-12-14 17:35 UTC, wyattjoh commented
We're making a release this week with all these in it! Expect the release to go out by Wednesday!