[CORL-1616/18/28] Fix typo-ed or missing translation keys in admin/stream.ftl
coralproject/talk pull request #3414
Opened 2021-01-29 16:26 UTC by nick-funk

## What does this PR do?

Fix typo-ed or missing translation keys in admin/stream.ftl

## What changes to the GraphQL/Database Schema does this PR introduce?

None

## How do I test this PR?

Ctrl + F for the key changes in this PR and confirm they match their use in the stream/admin codebase

2021-01-29 16:55 UTC, tessalt approved these changes

2021-01-29 18:33 UTC, wyattjoh requested changes

2021-01-29 18:33 UTC, wyattjoh commented on src/locales/en-US/stream.ftl
> +comments-postCommentForm-gifSeach =
The key should be deleted

2021-01-29 18:33 UTC, wyattjoh commented on src/locales/en-US/admin.ftl
> +  Moderate story
These should be on the same line

2021-02-01 17:40 UTC, wyattjoh approved these changes

2021-02-02 14:10 UTC, merged