[CORL-1643] Subscribe to and insert new questions on unanswered tab
coralproject/talk pull request #3430
Opened 2021-02-04 15:28 UTC by nick-funk

## What does this PR do?

Allow "View new comments" and newly posted comments to show when using the "Unanswered" tab in a Q&A conversation.

## What changes to the GraphQL/Database Schema does this PR introduce?

None

## How do I test this PR?

- Enable Q&A
- Set stream to Q&A mode
- Set yourself as an expert
- Switch to Unanswered stream tab with expert user
- Open another browser tab as commenter
- Go to Unanswered with commenter
- Post a question while viewing the Unanswered tab in commenter browser tab
- See that the comment is inserted into the Unanswered stream on commenter browser tab
- Switch to the expert's browser tab
- See that there is a view new comments button available, click it and ensure the new unanswered comment shows up in the Unanswered tab

2021-02-04 15:29 UTC, nick-funk commented
Just realized the unanswered tab count is double incrementing, one sec, will get a quick fix in for that.

2021-02-04 23:29 UTC, cvle requested changes
I need to investigate a bit more, but I already got the following:
- Two parts of the code is doing count incrementing, there should be only one.
- Some of the tag handling should take into account what tags the server responses back.
- We should probably utilise optimistic response more in some cases.

I need to take a look at the whole tag handling. Will get report next week.

2021-02-11 15:09 UTC, cvle requested changes
Finished the Code Review. Let's work this out together next week. Also take a look at  `UnansweredCommentsTabViewNewMutation` and `AllCommentsTabViewNewMutation`. They are responsible for handling counts of incoming comments.

2021-02-11 15:09 UTC, alinhle commented on src/core/client/stream/tabs/Comments/Stream/Subscriptions/CommentEnteredSubscription.ts
> +          variables.tag !== GQLTAG.UNANSWERED &&
What's this line for?

2021-02-11 15:09 UTC, cvle commented on src/core/client/stream/tabs/Comments/Stream/PostCommentForm/PostCommentFormContainer.tsx
> +      }
This is incomplete, and would only work for this particular tab.
Look at how R&R is determining its tag inside the `CreateCommentMutation`. I think we should follow the same patern.

2021-02-11 15:09 UTC, cvle commented on src/core/client/stream/tabs/Comments/Stream/PostCommentForm/CreateCommentMutation.ts
> +  connectionKey?: string;
I'd remove both of these. `tag` is never used except by the code you added in this PR. We can infer both from current state.

2021-02-11 15:09 UTC, cvle commented on src/core/client/stream/tabs/Comments/Stream/PostCommentForm/CreateCommentMutation.ts
> +  }
Instead of taking `connectionKey` here we cold infer from current story mode.

2021-02-11 15:09 UTC, cvle commented on src/core/client/stream/tabs/Comments/Stream/PostCommentForm/CreateCommentMutation.ts
> +  if (local.commentsTab !== "UNANSWERED_COMMENTS") {
We don't the whole count logic here. Wyatt already manages counts in `incrementTagCommentCounts`, it just needs the right input.

2021-02-11 15:09 UTC, cvle commented on src/core/client/stream/tabs/Comments/Stream/PostCommentForm/CreateCommentMutation.ts
> +            }
If we remove `tag` from `input` then we don't need this change here anymore.

2021-02-11 15:14 UTC, cvle commented on src/core/client/stream/tabs/Comments/Stream/PostCommentForm/CreateCommentMutation.ts
> +            }
To be correct, the `sharedUpdater` should actually use the `tags` that comes from the `response` instead.

2021-05-20 15:58 UTC, cvle commented
Superseded by https://github.com/coralproject/talk/pull/3430

2021-05-20 15:58 UTC, closed without merging