Live Chat
coralproject/talk pull request #3449
Opened 2021-02-11 15:37 UTC by nick-funk

## What does this PR do?

## What changes to the GraphQL/Database Schema does this PR introduce?

## How do I test this PR?

2021-02-11 17:00 UTC, cvle requested changes

2021-02-11 17:00 UTC, alinhle commented on src/core/client/stream/tabs/Live/AfterComments.tsx
> +        flattenReplies: true,
Some of these are not used?

2021-02-11 17:00 UTC, alinhle commented on src/core/client/stream/tabs/Live/LiveStream.tsx
> +          const id = `comment-${beforeComments[0].__id}`;
Request `id` explicitly and use that.

2021-02-11 17:00 UTC, alinhle commented on src/core/client/stream/tabs/Live/LiveStream.tsx
> +    setTimeout(() => {
clear timeout

2021-02-11 17:00 UTC, alinhle commented on src/core/server/graph/schema/schema.graphql
> +  CHAT
ENABLE_CHAT?

2021-02-25 17:44 UTC, cvle commented on src/core/client/stream/tabs/Live/LiveChatContainer.tsx
> +      {replyVisible && focusedComment && storyID && viewer && (
```suggestion
      {replyVisible && focusedComment && viewer && (
```

2021-03-11 16:23 UTC, cvle commented on src/core/client/stream/tabs/Live/LiveCreateCommentMutation.tsx
> +
What is this for?

2021-03-11 16:23 UTC, cvle commented on src/core/client/stream/tabs/Live/LiveChatContainer.tsx
> +    window.setTimeout(scrollToComment, 300);
I think you forgot to set the timeout ref:
`scrollToCommentTimeout.current = window.clearTimeout(scrollToCommentTimeout.current);`

2021-03-11 17:22 UTC, cvle commented
Noting this here so we don't forget:
- When story is closed and comments are empty, we would still encourage user to write comments even when it's not possible.
![image](https://user-images.githubusercontent.com/14221600/110827746-a9c69080-8296-11eb-960c-cdf8dd3c95ea.png)

2021-03-11 20:45 UTC, cvle commented on src/core/client/stream/tabs/Live/LiveTabQuery.tsx
> +  useHeartbeat(reloadOnIdle, heartbeatIntervalMs);
This looks a bit hardcore 👀

2021-03-12 16:07 UTC, cvle commented on src/core/client/stream/tabs/Live/LiveCreateCommentMutation.tsx
> +  commentEdge.setValue(new Date().toISOString(), "cursor");
`commentEdge.setValue(new Date().toISOString(), "cursor");`

2021-03-28 00:13 UTC, edoarso approved these changes

2021-04-15 16:41 UTC, nick-funk commented
Closing this PR because we have created an epic branch for live chat here:
https://github.com/coralproject/talk/pull/3504

2021-04-15 16:41 UTC, closed without merging