[CORL-1658] AMP Configuration
coralproject/talk pull request #3466
Opened 2021-02-24 14:45 UTC by cvle

## What does this PR do?
- Allow AMP support to be enabled inside of `Admin` -> `Config` -> `Advanced`

## How do I test this PR?
- `npm run start:development`
- goto `http://localhost:3000/embed/stream/amp` 
- Check if AMP is really turned on/off
  - It's on when:  `Content-Security-Policy: frame-ancestors` is not sent in the response headers
  - It's off when:  `Content-Security-Policy: frame-ancestors` are sent

2021-03-31 20:14 UTC, nick-funk commented
I ran this and tried it with and without AMP enabled. Not seeing `Content-Security-Policy: frame-ancestors` be sent back in the response headers for either option.

2021-03-31 20:16 UTC, nick-funk requested changes
I ran this and tried it with and without AMP enabled. Not seeing `Content-Security-Policy: frame-ancestors` be sent back in the response headers for either option.

2021-04-01 17:05 UTC, nick-funk approved these changes

2021-07-13 22:41 UTC, wyattjoh commented on src/core/server/models/tenant/tenant.ts
> +  featureFlags?: (GQLFEATURE_FLAG | LEGACY_FEATURE_FLAGS)[];
Maybe this might read cleaner?

```suggestion
  featureFlags?: Array<GQLFEATURE_FLAG | LEGACY_FEATURE_FLAGS>;
```

2021-07-13 22:41 UTC, wyattjoh commented on src/core/server/models/tenant/helpers.ts
> +  }
Maybe this reads a bit cleaner?

```suggestion
  if (typeof tenant.amp === "boolean") {
    return tenant.amp;
  }
```

2021-07-20 13:32 UTC, merged