[CORL-1700] Live Chat: reply notifications + reply tweaks
coralproject/talk pull request #3521
Opened 2021-04-26 17:36 UTC by nick-funk

## What does this PR do?

- Highlight replies to the viewer's comments in the live chat
- Swap "reply" for "view conversation" on the reply comments in the main live chat stream
- When a user selects a reply comment and clicks "view conversation" the conversation thread opens and does the following:
   - jumps to the reply comment they clicked on to open the conversation
   - highlights the reply comment so they have context and focus based on the thread reply they clicked on

## What changes to the GraphQL/Database Schema does this PR introduce?

None

## How do I test this PR?

- Go to live chat
- Create a comment (original commenter)
- Use another account (replier) to reply to that comment
- See that the reply is highlighted with an emphasized dark grey L-bracket when it comes in on the original commenter account
- Create some more replies to the original comment
- Click on the replies new "view conversation" button and see that the conversation view shows the comment you came from as well as highlights it

2021-04-28 15:41 UTC, cvle requested changes
When the highlighted comment ends up in the `beforeComments` due to cursor changes like `JumpToX`, the styling is incorrect:
![image](https://user-images.githubusercontent.com/14221600/116431230-e26ef900-a847-11eb-8550-ef6034a2a07a.png)

Good first draft.

2021-04-28 15:41 UTC, alinhle commented on src/core/client/stream/tabs/Live/LiveComment/LiveCommentContainer.tsx
> +    comment.parent.author.id === viewer.id;
Could be replaced with:
`const isReplyToViewer = comment.parent?.author?.id === viewer?.id;`

2021-04-28 15:41 UTC, alinhle commented on src/core/client/stream/tabs/Live/LiveChatContainer.tsx
>        showConversation(parent, "replyToParent");
It would be great to refactor all of the conversation stuff into a hook:
```ts
const [showConversation, hideConversation, conversationState] = useConversation();
showConversation(comment, { highlight: commentToHighlight });
```

2021-04-28 15:41 UTC, cvle commented on src/core/client/stream/tabs/Live/LiveComment/LiveCommentActionsContainer.tsx
> +        {comment.parent && onReply && (
Line 226 has the same implementation of the `button` with just a different handler. It should be possible to combine the two.

2021-04-28 15:41 UTC, cvle commented on src/core/client/stream/tabs/Live/LiveConversation/LiveConversationQuery.tsx
> +          new Date(highlightedCommentState.cursor).getTime() - 10
Don't substract by `- 10` it's a hack. Instead fix what's wrong with the query. In the Convo View the Before Container should always set `inclusive: false` and the After Container to `inclusive: true`. At the moment this is flipped around which is wrong.

2021-04-28 15:41 UTC, cvle commented on src/core/client/stream/tabs/Live/LiveComment/LiveCommentContainer.css
> +  margin-right: 12px;
Should use `var(--spacing-x)`

2021-04-28 15:41 UTC, cvle commented on src/core/client/stream/tabs/Live/LiveComment/LiveCommentContainer.css
> +  height: 20px;
Don't use `height: 20px` here on this typography element. Did you mean `line-height` instead?

2021-04-28 15:41 UTC, cvle commented on src/core/client/stream/tabs/Live/LiveComment/LiveCommentContainer.css
> +  height: 20px;
Don't use `height: 20px` here on this typography element. Did you mean `line-height` instead?

2021-04-28 16:17 UTC, nick-funk commented
> When the highlighted comment ends up in the `beforeComments` due to cursor changes like `JumpToX`, the styling is incorrect:
> ![image](https://user-images.githubusercontent.com/14221600/116431230-e26ef900-a847-11eb-8550-ef6034a2a07a.png)
> 
> Good first draft.

Fixed, was just me forgetting to set the highlight flag on the `LiveReplyContainer`

2021-04-28 21:07 UTC, cvle requested changes
According to design, there is no whitespace/padding on the left of the comment when highlighted.
![image](https://user-images.githubusercontent.com/14221600/116472595-5fb16280-a876-11eb-906b-466e6f1fb14c.png)

2021-04-28 21:49 UTC, nick-funk commented
> According to design, there is no whitespace/padding on the left of the comment when highlighted.
> ![image](https://user-images.githubusercontent.com/14221600/116472595-5fb16280-a876-11eb-906b-466e6f1fb14c.png)

<img width="291" alt="image" src="https://user-images.githubusercontent.com/5751504/116477054-53f37b00-a839-11eb-8c04-5f834156817e.png">

Designs show this, I'm confused, what are we referring to here?

2021-04-28 22:06 UTC, nick-funk commented
> According to design, there is no whitespace/padding on the left of the comment when highlighted.
> ![image](https://user-images.githubusercontent.com/14221600/116472595-5fb16280-a876-11eb-906b-466e6f1fb14c.png)

Fixed

2021-04-29 17:16 UTC, cvle approved these changes

2021-04-29 18:03 UTC, merged