[CORL-2147] Track queue sort change events into metrics
coralproject/talk pull request #3594
Opened 2021-06-23 19:26 UTC by nick-funk

## What does this PR do?

When the user changes the sortedBy in the moderation queues, we fire an event with the eventEmitter that can be collected into our metrics.

## What changes to the GraphQL/Database Schema does this PR introduce?

None

## How do I test this PR?

- Start up app
- Go to mod queues
- Change sort by back and forth
- See event emitter logs in the Coral CLI output

2021-06-24 12:32 UTC, cvle requested changes

2021-06-24 12:32 UTC, cvle commented on src/core/client/stream/events.ts
> +}>("queueSortChangedEvent");
use `createViewerEvent` instead of `createViewerNetworkEvent` as this action does not cause a network request.

2021-06-29 14:03 UTC, cvle requested changes
`createViewerEvent` and `createViewerNetworkEvent` has a different API, code need to adapt.

2021-07-08 21:12 UTC, cvle reviewed
We don't have a way to collect metrics on the admin yet.

2021-07-13 16:14 UTC, nick-funk commented
Closing this as we don't have metrics Admin side and we don't have a need to remove the sorting. Instead, we need to make the DB handle this gracefully.

2021-07-13 16:14 UTC, closed without merging