Feat/corl 2164 link to original commenter
coralproject/talk pull request #3648
Opened 2021-07-27 21:20 UTC by marcushaddon

## What does this PR do?
This PR will address https://vmproduct.atlassian.net/browse/CORL-2164 by causing the "In reply to..." text on replies to link the user back to the original comment. So far, this is successfully happening when the reply's parent is visible on the page (after Vinh's work on unread comments is merged, it will also cause the parent comment to be highlighted). 

An known edge case that is yet to be handled is when the reply's parent comment has not been loaded due to a long conversation thread being collapsed.

I *believe* that when this happens, the reply's parent comment is always the most immediate comment to not have been fetched, and that issuing a `ConversationThreadContainerPaginationQuery` that includes the parent's id and and count = 1 should cause it to be loaded without loading any unnecessary comments.

This makes me think that navigating to the parent shouldn't be the responsibility of the `<InReplyTo>` component because we would need to prop drill to get it access to the necessary pagination props, and that maybe it should just accept an `onClick` handler as a prop, so I'm very open to reworking that.

What I know I don't know is:
1. Are there any other edge cases that could cause a comments parent to not be loaded on the main stream view? For instance, if the comments are sorted in a certain order? (I gave one deeply nested reply 100 interactions and then sorted by interaction count, and it seemed to load all the ancestors of that comment, but I don't feel certain that will always be the case).
2. How to cause the Pagination query to be submitted, and if the results will be merged with the existing comments automatically (this is mostly just me looking at other places where I know this query is triggered, and reading up on Relay).

## What changes to the GraphQL/Database Schema does this PR introduce?
None.

## How do I test this PR?
Find a comment that is a reply to another comment and click "In Reply to...". The page should snap to the parent comment (currently only if its on the page).
 
 
## How do we deploy this PR?
No special actions should be required.

2021-08-04 13:35 UTC, cvle commented
I think we don't need to provide the jump to functionality inside of ConversationThread in the ancestor tree. The parent comment is right there (or sometimes after clicking on reveal) just above the comment.

2021-08-04 13:37 UTC, cvle commented
There is also some overlap here with the work I'm doing on the Comment Seen feature as you already pointed out.

2021-08-09 22:19 UTC, nick-funk requested changes

2021-08-09 22:19 UTC, nick-funk commented on src/core/client/stream/tabs/Comments/Comment/InReplyTo.tsx
> +    console.log(elem);
Might want to remove the eslint disables and console.log's

2021-08-09 22:19 UTC, nick-funk commented on src/core/client/stream/tabs/Comments/Comment/InReplyTo.tsx
> +      console.log("TODO: its not on the page~");
More es-lint and console.log's that should probably be removed

2021-08-09 22:19 UTC, nick-funk commented on src/core/client/stream/tabs/Comments/Comment/InReplyTo.tsx
> +      (elem as any).style["border"] = "5px solid green";
Thank you for using pym! This is one of the main things I was looking for! 💯

2021-08-09 22:24 UTC, nick-funk commented on src/core/client/stream/tabs/Comments/Comment/InReplyTo.tsx
> +      (elem as any).style["border"] = "5px solid green";
Make sure to run this border thing by design to check this is what they want. Super helpful for testing though!

2021-08-24 14:55 UTC, cvle commented on src/core/client/stream/tabs/Comments/Comment/CommentContainer.tsx
> +  parentLoaded?: boolean;
I suggest renaming the property to _what it does_, e.g. `enableJumpToParent`

2021-08-24 15:08 UTC, cvle requested changes

2021-08-24 15:08 UTC, alinhle commented on src/core/client/stream/tabs/Comments/Comment/CommentContainer.tsx
> +  parentLoaded?: boolean;
I suggest renaming the property to _what it does_, e.g. `enableJumpToParent`. In your case because the `default` is `true`, I would actually call it `disableJumpToParent`.

2021-08-24 15:08 UTC, cvle commented on src/core/client/stream/tabs/Comments/Comment/InReplyTo.tsx
> +  };
Should use `useCallback` here and it also seems unnecessary to pass in the `id` because you already got this from `parent.id`.

2021-08-24 15:08 UTC, cvle commented on src/core/client/stream/tabs/Comments/Comment/InReplyTo.tsx
> +  isLink: boolean;
I suggest here as well to rename the property to what it does like before: e.g. `enableJumpToParent` or `disableJumpToParent` depending on how you want the default to be.

2021-08-24 15:08 UTC, cvle commented on src/core/client/stream/tabs/Comments/PermalinkView/ConversationThreadContainer.tsx
> +                    parentLoaded={false}
this shouldn't be `false`, but in this case with the `parentLoaded` property: `remaining === 0`

2021-09-07 17:23 UTC, nick-funk approved these changes
Works well, I think this should be good to merge if we rebase after `commentSeen` stuff is merged into develop!

2021-09-07 17:23 UTC, nick-funk commented on src/core/client/stream/tabs/Comments/Comment/InReplyTo.tsx
> +      elem.focus();
ah, yes, that's what I forgot in my previous comment, to use pym to facilitate scrolling. Good job here!

2021-09-07 19:55 UTC, cvle approved these changes

2021-09-07 19:58 UTC, cvle requested changes

2021-09-07 19:58 UTC, cvle commented on src/core/client/stream/tabs/Comments/Comment/InReplyTo.css
> +
That's global css, which we shouldn't be using here.

2021-09-07 21:38 UTC, cvle approved these changes

2021-09-07 22:17 UTC, alinhle approved these changes

2021-09-08 14:43 UTC, merged