Feat/CORL-2213 remove story live update config
coralproject/talk pull request #3670
Opened 2021-08-17 13:40 UTC by marcushaddon

## What does this PR do?
This PR removes the option to toggle live updates via the config panel in the stream.

## What changes to the GraphQL/Database Schema does this PR introduce?
None.

## How do I test this PR?
While logged in as an admin, navigate to a stream's Configure tab, and see that there is no longer the option to toggle live updates for that particular story (they can still be toggled site wide).

## How do we deploy this PR?
This shouldn't require any special considerations.

2021-08-17 13:41 UTC, marcushaddon commented
@nick-funk @tessalt I just removed LiveUpdateConfig component from the stream config component, without deleting source for for LiveUpdateConfig. Let me know if I should delete all of it or if we have some way of identifying dead code.

2021-09-10 15:24 UTC, nick-funk requested changes

2021-09-10 15:24 UTC, nick-funk commented on src/core/client/stream/tabs/Configure/Configure.tsx
> -      <HorizontalRule />
Are there translations that might need to be removed from `stream.ftl` as well?

2021-09-15 19:24 UTC, cvle requested changes
Hey @marcushaddon, you can remove the files entirely. We can almost take it back from this PR. Also there are quite a few unused translations. Can you find and remove them? Unfortunately we have do this all by hand at the moment.

2021-09-15 23:14 UTC, nick-funk approved these changes

2021-09-16 22:36 UTC, cvle commented on src/locales/en-US/stream.ftl
>  configure-disableLiveUpdates-description =
Here is one left to be removed :-)

2021-09-16 22:46 UTC, cvle commented on src/core/client/stream/tabs/Configure/LiveUpdatesConfig/LiveUpdatesConfigContainer.tsx
> -    }
The fragment `LiveUpdatesConfigContainer_story` is still being used, that's why we got all the build errors.

2021-10-19 17:42 UTC, alinhle approved these changes

2021-10-19 20:07 UTC, nick-funk approved these changes
Approving again

2021-10-21 21:52 UTC, merged