chore | CORL-2160 add client faq info and hide full page search tool
coralproject/talk pull request #3673
Opened 2021-08-20 18:39 UTC by nbachman-vox

## What changes to the GraphQL/Database Schema does this PR introduce?

no changes

## How do I test this PR?

- view updated docs pages to evaluate
- test that using the search box on any page does NOT show a link to more results at the bottom of the popup results
 
## How do we deploy this PR?

no special action needed

## jira ref

 https://vmproduct.atlassian.net/browse/CORL-2160

2021-08-27 18:59 UTC, immber commented on docs/docs/events.md
> +_Note: only actions on the embedded comments are trackable. Actions taken in the Coral Admin tool are not currently trackable events._
Let's change this language a bit... 

> Note: only events that occur on the comment embed stream will be emitted. No events are emitted from Coral's Moderation/Admin interface.

2021-08-27 19:06 UTC, immber commented on docs/docs/cms.md
Can you add a note here about how to rescrape from the Story list if metadata is not showing up there?

2021-08-27 19:11 UTC, immber commented on docs/docs/troubleshooting.md
> +## An Admin user logged in via SSO is not automatically logged in to Coral Admin from comments MODERATE button
Let's make this a bullet point and not a new header

2021-08-27 19:16 UTC, immber commented on docs/docs/troubleshooting.md
> +An admin-authorized user logged in to comments via SSO can only be logged in to the Coral Admin tool automatically if “Coral Admin” is checked under "Configure" -> "Authentication" -> “Login with Sin
let's change this copy to:
> Make sure you've enabled the option for “Coral Admin” under the "Configure" -> "Authentication" -> “Login with Single Sign On“ settings. This box must be checked to allow users with the MODERATOR or ADMIN roles to access the Moderation/Admin interface using the MODERATE button.

2021-08-27 19:19 UTC, immber commented on docs/docs/troubleshooting.md
> +## A user on my site has a new SSO 'user.id' but they cannot log in anymore (Duplicate Email error)
again let's make this a bullet point under `My commenters are reporting that they cannot login to Coral` instead of a new header

2021-08-27 19:34 UTC, immber commented on docs/docs/troubleshooting.md
> +If you have changed the SSO `user.id` associated with the users email address, Coral will attempt to add the new user, but will fail because the user's email address is already in the system.  The si
Let's tweak the wording on this one to:
>Coral does not support changing a User's `user.id`. If you attempt to pass an SSO token with a new `user.id` but an existing `user.email` address, Coral will throw a `DUPLICATE_USER_ERROR`. To correct this, you need to "detach" the user's email address from their _original_ `user.id` by sending an API request to Coral's `updateUserEmail` mutation, and set the `user.email` for the _original_ `user.id` to some other value. After that you will be able to pass an SSO token with the new `user.id` and existing `user.email` combination.  The user will lose access to their existing comment history, because according to Coral, they are a new and different user.

2021-08-27 19:34 UTC, immber requested changes
I've added some inline notes with changes

2021-08-30 17:47 UTC, nbachman-vox commented on docs/docs/events.md
> +_Note: only actions on the embedded comments are trackable. Actions taken in the Coral Admin tool are not currently trackable events._
fixed in fd1b8b2ca

2021-08-30 20:56 UTC, immber approved these changes
👍 changes look good, this is ready for merge

2021-09-14 17:01 UTC, merged