Story 138187767  - Moderate Flag User Names
coralproject/talk pull request #370
Opened 2017-03-02 17:36 UTC by gabelula

Story 138187767

## What does this PR do?

Adds a moderation queue for the flagging of usernames in the community section of the admin. 

## What is still missing

- Suspending a user brings back the dialog but when we confirm the suspension we are getting an error. It needs to update the mutation to suspend a user (status banned AND canEditUsername true).
- The UX is still missing some stuff

## How do I test this PR?

- flag a username
- go to the admin and look at the queue
- try reject, approve, ban

2017-03-02 17:54 UTC, wyattjoh requested changes

2017-03-02 17:54 UTC, wyattjoh commented on graph/loaders/users.js
> +  users = users.find();
This extra `.find()` is redundant.

2017-03-02 17:54 UTC, wyattjoh commented on graph/loaders/users.js
> +  }
This should be handled at the resolver layer, not the loader.

2017-03-02 17:54 UTC, wyattjoh commented on graph/resolvers/root_query.js
> +      });
This should not be so specific, instead we should provide a generic edge:

```graphql
input UserQueryInput {
  action_type: ACTION_TYPE

  # Limit the number of results to be returned.
  limit: Int = 10
 
  # Skip results from the last created_at timestamp.
  cursor: Date
 
  # Sort the results by created_at.
  sort: SORT_ORDER = REVERSE_CHRONOLOGICAL
}
...

users(query: UserQueryInput): [User]
```

2017-03-02 17:54 UTC, wyattjoh commented on graph/typeDefs.graphql
> +  actions: [FlagAction]
This should be reverted, it breaks the composability that we had with the previous layout.

2017-03-02 17:54 UTC, wyattjoh commented on graph/typeDefs.graphql
> +  usersFlagged(query: UsersQuery): [User]
Change to `users`.

2017-03-02 17:54 UTC, wyattjoh commented on graph/resolvers/root_query.js
> +      });
See https://github.com/coralproject/talk/blob/2c98aa20977155d09b08e927c574be1221d2d707/graph/resolvers/root_query.js#L30-L37 for how comments are currently handled.

2017-03-03 03:23 UTC, gabelula commented on graph/loaders/users.js
> +  }
Yes. I'm changing it.

2017-03-03 03:23 UTC, gabelula commented on graph/loaders/users.js
> +  users = users.find();
ok

2017-03-03 03:23 UTC, gabelula commented on graph/resolvers/root_query.js
> +      });
Yes. I started working it that way and had a lot of issues. I will give it other try.

2017-03-03 03:23 UTC, gabelula commented on graph/typeDefs.graphql
> +  actions: [FlagAction]
ok

2017-03-03 03:24 UTC, gabelula commented on graph/typeDefs.graphql
> +  usersFlagged(query: UsersQuery): [User]
I don't only want the users but the users that have been flagged.

2017-03-03 05:39 UTC, wyattjoh commented on graph/resolvers/root_query.js
> +      });
Please let me know if you have any questions, I'd be happy to jump on a conference call to help things out.

2017-03-03 05:40 UTC, wyattjoh commented on graph/typeDefs.graphql
> +  usersFlagged(query: UsersQuery): [User]
Hence adding the `action_type` field to the `UsersQuery`, it would function in a similar fashion to the `comments` edge in that manner.

2017-03-07 15:53 UTC, wyattjoh requested changes

2017-03-07 15:53 UTC, wyattjoh commented on graph/resolvers/user.js
> +    return null;
There is no need for a users edge on a User, this shouldn't be here.

2017-03-08 16:45 UTC, wyattjoh approved these changes

2017-03-09 17:10 UTC, riley requested changes
here's a couple things I noticed

2017-03-09 17:10 UTC, riley commented on client/coral-admin/src/containers/Community/CommunityContainer.js
> +          {...this}
would it be a lot of trouble to be more explicit here?

2017-03-09 17:10 UTC, riley commented on client/coral-admin/src/containers/Community/CommunityContainer.js
> +          {...this}
also here

2017-03-09 17:10 UTC, riley commented on client/coral-admin/src/containers/Community/FlaggedAccounts.js
> +
could we get some `propTypes` here? :D

2017-03-09 17:10 UTC, riley commented on client/coral-admin/src/containers/Community/components/SuspendUserDialog.js
> +import translations from '../../../translations.json';
not necessary to change now, but you can point directly at the files instead of relative pathing => `coral-admin/src/translations`

2017-03-22 19:10 UTC, riley approved these changes

2017-03-22 19:10 UTC, merged

2017-03-22 19:48 UTC, wyattjoh commented on services/users.js
> +    return UserModel.update({
Can use a `findAndModify` instead of `update` to perform both the `update/find` at the same time.