Feat/corl 2230 configurable flatten replies
coralproject/talk pull request #3704
Opened 2021-09-08 21:29 UTC by marcushaddon

## What does this PR do?
This PR addresses https://vmproduct.atlassian.net/browse/CORL-2230 and makes "Flatten Replies" configurable via the admin UI, as opposed to a feature flag.

## What changes to the GraphQL/Database Schema does this PR introduce?
FLATTEN_REPLIES is no longer a valid feature flag.

## How do I test this PR?
1. Create a reply chain that is long enough to be hidden behind a "Show more of this conversation" button. 
2. Under admin > configure > general, navigate to Flatten Replies and check "Yes"
3. back in the stream, refresh and confirm that all replies are shown.
 
## How do we deploy this PR?
No special actions should be necessary to deploy this change NOTE: Need to confirm this wont break tenants/instances where flatten replies are enabled as a feature flag / if we need some sort of migration.

2021-09-15 20:10 UTC, cvle requested changes
Looks good overall. I've added some review comments.

There is also one missing change:
- The `settings.flattenReplies` resolver should default to the former feature flag `FLATTEN_REPLIES`
  - Look at the `amp` resolver in `src/core/server/graph/resolvers/Settings.ts` for an example

2021-09-15 20:10 UTC, alinhle commented on src/core/client/admin/routes/Configure/sections/General/FlattenRepliesConfig.tsx
> +      <FormFieldDescription> TODO: Get copy!</FormFieldDescription>
It still says, TODO here.

2021-09-15 20:10 UTC, alinhle commented on src/core/server/graph/schema/schema.graphql
> +  flattenReplies: Boolean
Maybe reuse the old comment?

``` 
"""
  flattenReplies when enabled, will cause all replies that would normally be
  hidden by a "Show more of this conversation" button to be displayed linearly
  sorted by date.
"""
```

2021-09-15 20:10 UTC, alinhle commented on src/core/client/stream/local/initLocalState.ts
> +  })
Leftover from development?

2021-09-15 20:10 UTC, cvle commented on src/core/server/graph/schema/schema.graphql
> +  flattenReplies: Boolean
I think the type should be `Boolean!`, there is no need to keep the `null` state.

2021-09-15 23:11 UTC, nick-funk requested changes, later dismissed
This feature works rather well. Nicely done. Fix up the small comments @cvle mentioned and this will be good to go!

2021-09-21 15:35 UTC, alinhle requested changes
Nearly done! Just one comment, and a remaining comment from the previous review.

2021-09-21 15:35 UTC, cvle commented on src/core/server/models/tenant/tenant.ts
> +
I think we should add to this file instead: `src/core/server/models/settings/settings.ts` where the `Settings` type is exported. There you find all the other settings as well.

2021-09-21 15:35 UTC, cvle commented on src/core/server/graph/schema/schema.graphql
>    flattenReplies: Boolean
https://github.com/coralproject/talk/pull/3704#discussion_r709537504

2021-10-19 22:02 UTC, alinhle requested changes
Last thing and we're done!

2021-10-19 22:02 UTC, alinhle commented on src/core/client/admin/routes/Configure/sections/General/FlattenRepliesConfig.tsx
> +      strong={<strong />}
Just remove this and we are done!

This one makes the `strong` tag available in the translation string, but it is not being used.
```suggestion
```

2021-10-20 16:13 UTC, alinhle approved these changes

2021-10-20 16:13 UTC, alinhle commented
Just linting errors left.

2021-10-21 21:39 UTC, merged