Fix nb-NO translation
coralproject/talk pull request #3745
Opened 2021-10-05 13:17 UTC by ingriddraagen

## What does this PR do?
Fix a translation-isuue

## What changes to the GraphQL/Database Schema does this PR introduce?

## How do I test this PR?

 
 
## How do we deploy this PR?

2021-10-05 17:29 UTC, cvle requested changes
The original English translation is:
```
comments-userPopover-ignore = Ignore
```
Which is only the verb ignore. 
I think line 255-256 should be removed and
line 254 should be something like: `comments-userPopover-ignore = Ignorer`

Wdyt?

2021-10-11 07:40 UTC, ingriddraagen commented
> The original English translation is:
> 
> ```
> comments-userPopover-ignore = Ignore
> ```
> 
> Which is only the verb ignore. I think line 255-256 should be removed and line 254 should be something like: `comments-userPopover-ignore = Ignorer`
> 
> Wdyt?

Great catch! I was sick last week, so sorry for the late reply. I'll push the changes asap

2021-10-14 14:01 UTC, tessalt approved these changes

2021-10-14 19:54 UTC, alinhle approved these changes

2021-10-14 20:07 UTC, merged