[CORL-2312]: Add option to provide another domain for comment downloads
coralproject/talk pull request #3752
Opened 2021-10-18 14:57 UTC by kabeaty

## What does this PR do?
This PR adds an optional server config env var for the domain to be used in the download GDPR comments link that's sent out in emails. If set to its default empty string, the tenant domain will still be used. If set to a domain, then this domain will be used in the download link sent out.

I am interested in any feedback on what to do in `constructDownloadLinkUrl` regarding the domain in the case of working in `development`. I opted to include the link domain override in that url even though it means the url won't work in that case, so that the link could be inspected for testing that the override is working.

## What changes to the GraphQL/Database Schema does this PR introduce?
None

## How do I test this PR?
You can test this PR by
1. Setting the new env var (`DOWNLOAD_GDPR_COMMENTS_LINK_DOMAIN`) to a domain. (Can also test with it not set to make sure still working as expected in that case.)
1. Configuring Coral to allow users to download their comment history.
1. You'll need your local dev set up to mock email sending.
1. Request your comment history from your profile in the stream.
1. View the email you receive at localhost:9000. You should see when you hover over `Download my comment archive` that the link is using the domain you set.
 
## How do we deploy this PR?
This adds a new env var to the server config, but it doesn't need to be set to anything.

2021-10-18 21:32 UTC, nick-funk requested changes
Just a couple small things to fix here, but otherwise, this PR is great!

2021-10-18 21:32 UTC, nick-funk commented on src/core/server/config.ts
> +});
This created a cool learning moment for me, I thought we already had a url type for our config validation, but this is for a doman and not an `"optional-trailing-url"` like the `static-uri`. Nice add!

2021-10-18 21:32 UTC, nick-funk commented on src/core/server/services/users/download/token.ts
> +    downloadLinkDomainOverride
How is the `downloadLinkDomainOverride` bringing in the download token here? I see it being added for the regular `path` var, maybe I'm missing something, because I think it might be missing for the override var?

2021-10-19 15:01 UTC, kabeaty commented on src/core/server/services/users/download/token.ts
> +    downloadLinkDomainOverride
You got it--the download token is still being sent through via the token in the path and then combined with the override (which is just for the domain) when the url is constructed.

2021-10-19 15:23 UTC, nick-funk commented on src/core/server/services/users/download/token.ts
> +    downloadLinkDomainOverride
ah, nevermind, I missed that, this is good to go then!

2021-10-19 15:25 UTC, nick-funk approved these changes
This looks good to go!

2021-10-19 20:36 UTC, alinhle approved these changes
Very well done! Good work @kabeaty!

2021-10-21 21:24 UTC, merged