[CORL-2316]: Add moderator messaging option
coralproject/talk pull request #3757
Opened 2021-10-22 12:57 UTC by kabeaty

## What does this PR do?

This PR adds in the option to send a commenter a message if you are a moderator without changing their status (i.e. without a warning attached). This is for https://vmproduct.atlassian.net/browse/CORL-2316. 

Mod messaging is very similar to sending a warning message except that it doesn't change the user's status in any way.

## What changes to the GraphQL/Database Schema does this PR introduce?

To the GraphQL schema, these changes add `ModMessageStatus` and `ModMessageStatusHistory`, as well as adds these under `modMessage` to the `UserStatus`. These include the current status of moderation messages (is there currently an active mod message?) as well as the history of past moderation messages and their acknowledgment. In addition, these changes add `ModMessageUserInput`, `ModMessageUserPayload`, `AcknowledgeModMessageInput`, and `AcknowledgeModMessagePayload`. They also add `modMessageUser` and `acknowledgeModMessage`.

To the database schema, these changes add `ModMessageStatus` and `ModMessageStatusHistory`, as well as adds these under `modMessage` to the `UserStatus`. These changes add `modMessageUser` and `acknowledgeModMessage`. They also add `ConsolidatedModMessageStatus` and `consolidateUserModMessageStatus` to grab the message from the latest active moderation message.

## How do I test this PR?

 To test this, you can create at least one user that is a commenter. Then
 1. Logged in as admin/moderator, navigate to `Community` in the admin. 
 1. Find the user to whom you want to send a moderation message in the user table and click their status. Select `Message` at the bottom of the options.
 1. You should see a modal open with an area for entering a message to the user. Enter a message and click `Message User`. You should see a success modal confirming that a message was sent to the user.
 1. Now log in as the user to whom you sent the message. At the top of the stream, you should see the moderation message that you sent displayed with an option to acknowledge the message. See that you are still able to comment on the story.
 
 Other things to test with this flow include:
 - As the admin/moderator, visit the user's account history throughout the process and confirm that the message and message acknowledgment history is visible there.
 - If multiple messages have been sent by the moderator and unacknowledged, only the latest active moderation message is displayed at the top of the stream for acknowledgment.
 - A user sees both a warning and a moderation message to acknowledge if they have both.
 
## How do we deploy this PR?

I don't think there's anything that needs to be done on deploy.

2021-10-28 15:47 UTC, alinhle requested changes
Some remarks, but this is excellent work @kabeaty!

2021-10-28 15:47 UTC, alinhle commented on src/core/client/admin/components/UserStatus/ModMessageForm.tsx
> +                  <Textarea id="modMessageModal-message" {...input} fullwidth />
As this is only used for testing, we usually use `data-testid="modMessageModal-message" and `getByTestID` instead. But you can leave it as is.

2021-10-28 15:47 UTC, alinhle commented on src/core/client/admin/components/UserStatus/ModMessageUserMutation.ts
> +          ...input,
We do have a lot of bugs coming from spreading input like this in mutations, because Typescript allows passing in an `input` that contains more props than the type defines. That's why I recommend picking or passing the props individually here instead.

2021-10-28 15:47 UTC, alinhle commented on src/core/client/admin/components/UserStatus/UserStatusChange.tsx
> +                }}
As a good practice I usually recommend using `useCallback` which memoizes the callback instead of generating a new callback every render. Keeping the same reference when the data/object has not changed is a prerequisite for any performance optimisation in React.

This is not not important, just a reminder for a good practise.

2021-10-28 15:47 UTC, alinhle commented on src/core/server/models/user/user.ts
> +export async function modMessageUser(
I would start a method with a verb like `sendModMessage`

2021-10-28 15:47 UTC, alinhle commented on src/core/server/services/users/users.ts
> +export async function modMessage(
Same here, would start method with a verb.

2021-10-28 15:47 UTC, alinhle commented on src/core/server/models/user/user.ts
> +export function consolidateUserModMessageStatus(
How do you think about putting a comment here to explain what `consolidate` means?

2021-10-28 15:47 UTC, alinhle commented on src/core/server/models/user/user.ts
> +        },
Interesting, what's this second condition for?

2021-10-28 15:47 UTC, alinhle commented on src/core/server/models/user/user.ts
> +  modMessage: ModMessageStatus;
Should be `modMessage?: ModMessageStatus;` I believe, because `modMessage` is undefined for users that are already in the db before this lands.

2021-10-28 15:47 UTC, alinhle commented on src/core/client/stream/tabs/Comments/Stream/StreamContainer.tsx
>              </section>
Can you make the section into a `HoriziontalGutter`? Like this:

```tsx
            <HorizontalGutter
              id={VIEWER_STATUS_CONTAINER_ID}
              aria-label="Account Status"
              container="section"
            >
```

2021-10-28 15:47 UTC, alinhle commented on src/core/server/graph/schema/schema.graphql
> +  modMessageUser(input: ModMessageUserInput!): ModMessageUserPayload!
Is `modMessage` a verb 🤔 otherwise let's find a verb to start the name of this mutation.

2021-10-28 15:47 UTC, alinhle commented on src/core/server/graph/schema/schema.graphql
>    ): AcknowledgeWarningPayload @auth(permit: [WARNED])
Amazing work! Can you also adapt this line to have the same permission as your `acknowledgeModMessage` 
`@auth(permit: [SUSPENDED, BANNED, PENDING_DELETION, WARNED])`. 

I know it's not part of your story, but while you're here.. :-D

2021-10-28 16:59 UTC, alinhle commented on src/core/server/models/user/user.ts
> +            $ne: false,
Maybe true?

2021-10-29 18:24 UTC, kabeaty commented on src/core/server/graph/schema/schema.graphql
> +  modMessageUser(input: ModMessageUserInput!): ModMessageUserPayload!
As discussed, was thinking of `modMessage` as a verb, but will update to `sendModMessage` throughout for clarity 👍

2021-10-29 18:30 UTC, kabeaty commented on src/core/server/models/user/user.ts
> +            $ne: false,
Updated to `$eq: true` here and in `acknowledgeOwnWarning` 👍

2021-10-29 18:30 UTC, kabeaty commented on src/core/server/models/user/user.ts
> +        },
Removed this second condition both here and in `acknowledgeOwnWarning` 👍

2021-11-02 17:32 UTC, cvle commented on src/core/client/stream/test/comments/stream/modMessaged.spec.tsx
> +  expect(within(tabPane).queryByTestID("comment-edit-button")).toBeDefined();
`getByX` commands will automatically fail when element was not found, while `queryBy` does not and return either null or the element it found.

2021-11-04 17:47 UTC, cvle approved these changes

2021-11-04 18:03 UTC, merged