CORL-2358 gracefully close connections
coralproject/talk pull request #3775
Opened 2021-11-05 15:56 UTC by marcushaddon

## What does this PR do?
This PR addresses https://vmproduct.atlassian.net/browse/CORL-2348 by closing connections on the express server on SIGTERM, as well as setting up a method in which any other resources can be cleaned up if need be.

## What changes to the GraphQL/Database Schema does this PR introduce?
None.

## How do I test this PR?
TODO
 
## How do we deploy this PR?
No special considerations should be required.

2021-11-05 15:57 UTC, marcushaddon commented on src/core/server/index.ts
> +    // Do we need additional cleanup here?
ie mongo/redis connections?

2021-11-10 13:36 UTC, cvle requested changes
<img width="599" alt="Screenshot 2021-11-10 at 14 34 25" src="https://user-images.githubusercontent.com/14221600/141122636-eadf7cb7-7855-497e-ae76-9c00927c9665.png">

Unfortunately only closing the `httpServer` is not enough, because all of our connections are long living (keep-alive) tcp connections. 

Try finding a library that helps closing these connections as well.

2021-11-10 13:36 UTC, cvle commented on src/core/server/index.ts
> +    // Do we need additional cleanup here?
That won't be necessary.

2022-05-12 18:18 UTC, tessalt commented
closing until we can re-evaluate options.

2022-05-12 18:18 UTC, closed without merging