Fix/corl 2327 user ban bug
coralproject/talk pull request #3798
Opened 2021-11-29 22:34 UTC by marcushaddon

## What does this PR do?
This PR should address https://vmproduct.atlassian.net/browse/CORL-2327 by making user ban management more fine grained.

## What changes to the GraphQL/Database Schema does this PR introduce?
This introduces the `UpdateUserBanInput` input and `UpdateUserBanPayload` type, as well as the `updateUserBan(...)` mutation

## How do I test this PR?
- a "Manage User Ban" modal should now be accessible regardless of a user's status (unblocking site mods from adding additional bans to a user already banned on other sites)
- unscoped moderators should be able to add and remove bans to individual sites for a user (within the same form submission), as well as ban a user across the entire organization, and unban a user across the entire organization
- scoped moderators should be able to add additional single-site bans to users even if that user is already banned on other sites
- scoped mods will see an "All sites" option for banning, which should ban the user from all sites within that moderators scope
- scoped mods will not see a "No Sites" option (as they are not able to remove bans)
- when managing user bans on individual sites, scoped mods should be able to see all sites that a user is banned on, but not be able to unban users on any sites
 
 
## How do we deploy this PR?
I don't think any special considerations should be needed.

2021-11-30 18:38 UTC, kabeaty requested changes
Looks good overall! One issue that I noticed during manual testing was that I got an error when a user was banned on specific sites and then I tried to ban them on all sites. I got an error in this case that the user was already banned.

I'm also wondering if the text and email message should change in the `No sites` case? It still asks if the viewer is sure that they want to ban the user instead of remove bans for the user. Since it's possible to remove bans with the Specific sites option too, maybe the text should also be updated in this case too to include adding and removing bans?

2021-11-30 18:38 UTC, kabeaty commented on src/core/client/admin/components/ModerateCard/ModerateCardContainer.tsx
> +      updateType: string,
It doesn't look like `updateType` and `unbanSiteIDs` are used anywhere here. Can they be removed?

2021-11-30 18:38 UTC, kabeaty commented on src/core/client/admin/components/UserStatus/BanModal.tsx
> +  banStatus?: UserStatusChangeContainer_user["status"]["ban"];
I think ban sites are already coming through with `userScopes` so it should be possible to just get the sites that way instead of passing through again?

2021-11-30 18:38 UTC, kabeaty commented on src/core/client/admin/components/UserStatus/UserStatusSitesList.tsx
> +      if (on) {
What do you think about using a ternary operator here instead for readability? Also, what do you think about using `siteID` here and below as well for consistency?

2021-11-30 18:38 UTC, kabeaty commented on src/core/client/admin/components/UserStatus/UserStatusSitesList.tsx
> +                    checked={updateType.value === "ALL_SITES"}
What do you think about making these updateTypes into an enum somewhere?

2021-11-30 18:38 UTC, kabeaty commented on src/core/client/admin/test/community/community.spec.tsx
> +it.only("manages bans on individual sites", async () => {
Looks like you still need to remove the `only` here :)

2021-11-30 18:38 UTC, kabeaty commented on src/core/client/admin/test/community/community.spec.tsx
> +it.skip("ban user across specific sites", async () => {
Did you mean to keep this test skipped? Also, this seems very similar to the test for individual sites above. Could they be combined into one test instead?

2021-11-30 18:38 UTC, kabeaty commented on src/core/server/graph/schema/schema.graphql
> +  userID is the id of the user whos ban status should be updated
typo: `whos` --> `whose`

2021-11-30 18:38 UTC, kabeaty commented on src/core/server/graph/schema/schema.graphql
> +  updateUserBan will ban a specified user from specified sites (if
`updateUserBan` is adding and removing bans, right? Can you update the comment here to clarify?

2021-11-30 18:38 UTC, kabeaty commented on src/core/server/services/users/users.spec.ts
> +    ).rejects.toThrow(); // TODO: assert correct error
Are these still TODOs you're looking into to assert correct errors?

2021-11-30 18:38 UTC, kabeaty commented on src/core/server/services/users/users.spec.ts
> +    const commentor = createUserFixture({
nit: can you make this `commenter`?

2021-11-30 18:38 UTC, kabeaty commented on src/core/client/admin/components/UserStatus/BanModal.tsx
> +          !viewerScopes?.sites?.length ||
Would it work to just check for `!isSiteMod` in place of lines 79 & 80 here?

2021-11-30 18:38 UTC, kabeaty commented on src/core/client/admin/test/community/community.spec.tsx
> +  const statusMenu = within(userRow).getByLabelText(
Can you update this to be `dropdown` as well, as you did in the other tests, for consistency?

2021-11-30 18:38 UTC, kabeaty commented on src/core/server/services/users/users.ts
> + * ban will ban a specific user from interacting with Coral.
I think this comment should say `updateUserBan`. Also, it's possible to ban and unban with `updateUserBan`, right? I think it would be good to update to clarify that as well.

2021-11-30 18:38 UTC, kabeaty commented on src/core/server/services/users/users.ts
> +    throw new Error("User not authorized to peform UpdateUserBan"); // Look for specific error
It looks like there's still a TODO here around the specific error?

2021-11-30 18:38 UTC, kabeaty commented on src/core/client/admin/components/UserStatus/BanModal.tsx
> +        const filteredBans = banSiteIDs?.filter((siteID: string) =>
To me, something like `inScopeFilteredBans` would be clearer than just `filteredBans` regarding how the bans are filtered when I'm reading through. What do you think?

2021-11-30 18:38 UTC, kabeaty commented on src/core/client/admin/components/UserStatus/BanModal.tsx
> +                        data-testid="save-ban-status"
Is this `data-testid` used anywhere?

2021-11-30 18:38 UTC, kabeaty commented on src/core/client/admin/components/UserStatus/UserStatusChange.tsx
> +                  // disabled={banned && viewerIsScoped} MARCUS: When can banned be true?
This can just be removed now, right, since the `Manage Ban` is always an option?

2021-11-30 18:38 UTC, kabeaty commented on src/core/client/admin/components/UserStatus/UserStatusChange.tsx
> +                  data-testid="manage-ban"
Is this `data-testid` used anywhere?

2021-11-30 18:38 UTC, kabeaty commented on src/core/server/services/users/users.ts
> +      moderatorID: banner.id, // MARCUS: is this going to reject them across all sites?
Is this resolved?

2021-11-30 18:38 UTC, kabeaty commented on src/core/client/admin/components/UserStatus/UserStatus.tsx
> +  // MARCUS: possibly create bug ticket
Is this resolved?

2021-11-30 19:38 UTC, marcushaddon commented on src/core/client/admin/components/UserStatus/BanModal.tsx
> +  banStatus?: UserStatusChangeContainer_user["status"]["ban"];
Doesn't the `Scope` type of `userScopes` refer to a moderation scope for a moderator, and `banStatus` refer to the ban status of a commenter?

2021-11-30 19:40 UTC, marcushaddon commented on src/core/client/admin/components/UserStatus/BanModal.tsx
> +          !viewerScopes?.sites?.length ||
oh thats much better!

2021-11-30 20:09 UTC, kabeaty commented on src/core/client/admin/components/UserStatus/BanModal.tsx
> +  banStatus?: UserStatusChangeContainer_user["status"]["ban"];
Ah, so in`UserStatusChangeContainer`, what is passed in for `userScopes.sites` is `user.status.ban.sites`. I believe only the viewer has `moderationScopes`, as they are the ones viewing the modal and banning/unbanning in this case, and then the user is the commenter who does/doesn't have a ban status and ban sites.

2021-12-09 15:22 UTC, kabeaty requested changes
Thanks for making the updates to this! Looking good. I just have a few comments/questions on some of the changes.

Also, it looks like the ban modal is no longer preserving the selection of rejecting existing comments / custom ban message when switching between radio buttons. Can you take a look at this?

2021-12-09 15:22 UTC, kabeaty commented on src/core/client/admin/components/UserStatus/BanModal.tsx
> +import { UserStatusChangeContainer_user } from "coral-admin/__generated__/UserStatusChangeContainer_user.graphql";
Can you move this import down below all the coral imports but above the `ModalHeader` for consistency with where it's imported in other files?

2021-12-09 15:22 UTC, kabeaty commented on src/core/client/admin/components/UserStatus/BanModal.tsx
> +                    visible={
What do you think about just doing a check here in `BanModal` for whether to show `UserStatusSitesList` or null instead of passing it through here to check? I think that will be more readable to understand when it is/isn't shown, and more consistent with the other checks we're doing in this modal for when to show things.

2021-12-09 15:22 UTC, kabeaty commented on src/core/client/admin/components/UserStatus/UserStatusSitesList.tsx
> +  readonly banActive?: Readonly<boolean>;
What do you think about just passing `banActive` and `bannedSites` through here as `userBanStatus`, too? I think it would be more readable to keep this consistent.

2021-12-09 15:22 UTC, kabeaty commented on src/core/server/services/users/users.ts
> +      "User not authorized to peform UpdateUserBan",
typo `peform` --> `perform`. Also wondering if it would be friendlier to make the error something more like `User not authorized to manage user bans.`

2021-12-09 15:22 UTC, kabeaty commented on src/core/client/admin/components/UserStatus/UpdateUserBanMutation.ts
> +          ...input,
Can you please update to explicitly define the expected `input` here, so that we know exactly what this mutation expects?

2021-12-09 15:22 UTC, kabeaty commented on src/core/client/admin/components/UserStatus/BanModal.tsx
> +              <Localized id="specificSitesSelect-validation">
The error message here doesn't seem to match what's in the localization file. Do we want to update the error message to this there too? 

Also, I'm seeing this error when `All sites` and `No sites` are selected if the error was already triggered on `Specific sites` and then you navigate to them. For this reason, I think it makes sense to include the error only when `Specific sites` is selected instead of as a form error here (when you merge in my changes from PR 3804, you should be able to use something similar to how I set it up there, and it should hopefully just resolve this issue).

2021-12-09 15:22 UTC, kabeaty commented on src/core/client/admin/components/UserStatus/BanModal.tsx
> +        const inScopeFilteredBans = banSiteIDs?.filter((siteID: string) =>
Are these checks just to be sure that ban/unban siteIDs aren't included that are out of a moderator's scope? Since they shouldn't be able to select anything out of their scope. I think that a comment could be helpful here.

2021-12-09 15:22 UTC, kabeaty commented on src/core/client/admin/components/UserStatus/BanModal.tsx
> +  const banIDsState = useState<string[]>([]);
I'm wondering if it would work better to use `useField` in `UserStatusSitesList` in this case instead of `useState` here. That's kind of how it's being used, right? Then we could just check the input for `banIDs`/`unbanIDs` on form submit, and it wouldn't be needed to pass this state down through to `UserStatusSitesList`.

2021-12-09 15:22 UTC, kabeaty commented on src/core/client/admin/components/ModerateCard/ModerateCardContainer.tsx
> +          userBanStatus={comment.author.status.ban}
Nice renaming to better clarify what's getting passed through here!

2021-12-09 15:22 UTC, kabeaty commented on src/core/server/models/user/user.ts
> +      $set: {
Why are we setting this to false here if they are being banned?

2021-12-09 15:22 UTC, kabeaty commented on src/locales/en-US/admin.ftl
> +community-banModal-specificSites-title = Are you sure you want to manage ban status of <username></username>?
Maybe adding a `the` to make this `...to manage the ban status of...` would flow better?

2021-12-13 17:42 UTC, kabeaty reviewed
Looking good, and thanks for making changes! I have just a few more small comments on the updates.

2021-12-13 17:42 UTC, kabeaty commented on src/core/client/admin/components/UserStatus/BanModal.tsx
> +            submitError,
Is this being used anywhere, or can it be removed?

2021-12-13 17:42 UTC, kabeaty commented on src/core/client/admin/components/UserStatus/BanModal.tsx
> +      sendCustomMessage,
Is this being used anywhere, or can it be removed?

2021-12-13 17:42 UTC, kabeaty commented on src/core/client/admin/components/UserStatus/UserStatusChangeContainer.tsx
> +        case "ALL_SITES":
What about using the enum here as well?

2021-12-13 17:42 UTC, kabeaty commented on src/core/client/admin/components/UserStatus/BanModal.tsx
> +                          disabled={
With the `Save` button disabled this way, if a viewer bans a user across specific sites, then all sites, and then wants to ban across the same specific sites again, they won't be able to do so, as the `Save` button will be disabled in this case. I'm not sure how often this would happen, but it would create an odd state if it does...

2021-12-13 17:42 UTC, kabeaty commented on src/core/client/admin/components/UserStatus/UserStatusSitesList.css
>  .validationMessage {
Are you still using this, or should it be removed?

2021-12-13 22:49 UTC, marcushaddon commented
@kabeaty re: https://github.com/coralproject/talk/pull/3798#discussion_r767861411
To enable submit in this case would require that every checked site in the site ban list be submitted, which they are not. only sites  actively added by the user after selecting Specific Sites are sent with the mutation to allow for showing what sites a user is banned on, without having a site moderator submit updates to site bans for sites that are out of their scope. It's not ideal but I think it would be wiser to see how actual users interact with this component before doing more non-trivial reworking based on speculation.

2021-12-14 19:45 UTC, kabeaty commented
re: https://github.com/coralproject/talk/pull/3798#issuecomment-992982273 I'm replying here for future reference that this was resolved by ensuring general bans remove site bans.

2021-12-14 19:46 UTC, kabeaty approved these changes
Looks and works great! Thanks for making the changes.

2021-12-15 00:11 UTC, merged