[CORL-2381] Persist seen comments in the back-end
coralproject/talk pull request #3811
Opened 2021-12-14 19:41 UTC by nick-funk

## What does this PR do?

Persists seen comment state in the back-end so it can be a shared state between devices/logins for the same user.

## What changes to the GraphQL/Database Schema does this PR introduce?

- Adds a `seen` flag to the `Comment` type
- Adds a `markCommentAsSeen` mutation to the `Mutators` list

## How do I test this PR?

- Create the indexes listed in the deploy notes below
- Visit the stream as a logged in user and see that you can key through or refresh the stream and have comments go yellow to white
- Load up on your phone, another tab/browser and sign in as the same user, see that seen state is persisted to your user account
- Check your mongo for records in the `seenComments` collection
- Modify your `EXPIRE_SEEN_COMMENTS_OLDER_THAN` env var to make it recent enough to delete the seen state of the comments you just looked at
- Watch for a job to run that deletes the records from `seenComments`
    - modify the `SEEN_COMMENTS_CLEANUP_INTERVAL` interval to speed this up so you don't have to wait forever, it uses a standard cron timing
 
## How do we deploy this PR?

Create the following indexes in Mongo:

```
db.seenComments.createIndex({ tenantID: 1, storyID: 1, userID: 1 });
db.seenComments.createIndex({ tenantID: 1, storyID: 1, userID: 1, lastSeenAt: 1 });
```

2021-12-16 19:27 UTC, wyattjoh commented on src/core/server/cron/seenCommentsCleanup.ts
> +const cleanupSeenComments: ScheduledJobCommand<Options> = async ({
Why not instead utilize a TTL index in MongoDB?

https://docs.mongodb.com/manual/core/index-ttl/

It's designed to do this automatically.

2022-01-10 15:02 UTC, kabeaty requested changes
Looks good overall! I left a few comments. Also, it looks like the `CommentContainer` styles for the logged-out state are missing some padding now. Can you take a look at this?

2022-01-10 15:02 UTC, kabeaty commented on src/core/server/models/comment/comment.ts
> +  seen?: boolean;
Can you add a comment here for `seen`?

2022-01-10 15:02 UTC, kabeaty commented on src/core/server/models/seenComments/seenComments.ts
> +export interface SeenComments extends TenantResource {
What do you think about adding some comments here for `lastSeenAt`, `isDeleting`, `comments` etc.?

2022-01-10 15:02 UTC, kabeaty commented on src/core/server/models/seenComments/seenComments.ts
> +export async function retrieveSeenCommentsForDeletion(
Can this be removed now?

2022-01-10 15:02 UTC, kabeaty commented on src/core/client/stream/tabs/Comments/Comment/CommentContainer.tsx
> +      data-not-seen={commentSeenEnabled ? !comment.seen : false}
I think this needs to be something like `commentSeenEnabled && comment.seen ? undefined : true`. 

In `KeyboardShortcuts`, in `toKeyStop`, it's just checking whether `data-not-seen` is there or not. So, setting it to `false` here is making it pass the check as not seen, and the `Z` key shortcut therefore isn't working as expected.

2022-01-14 16:25 UTC, nick-funk commented on src/core/server/models/seenComments/seenComments.ts
> +export async function retrieveSeenCommentsForDeletion(
Yup! Removed it!

2022-01-14 16:25 UTC, nick-funk commented on src/core/server/models/seenComments/seenComments.ts
> +export interface SeenComments extends TenantResource {
Comments have been added!

2022-01-14 16:25 UTC, nick-funk commented on src/core/server/models/comment/comment.ts
> +  seen?: boolean;
Yup! Added!

2022-01-14 16:47 UTC, nick-funk commented on src/core/client/stream/tabs/Comments/Comment/CommentContainer.tsx
> +      data-not-seen={commentSeenEnabled ? !comment.seen : false}
I inverted it to be `commentSeenEnabled && !comment.seen ? true : undefined` to make it more in-line with the fact the tag is `data-not-seen`. Other than that, updated and good catch!

2022-01-14 17:56 UTC, nick-funk commented
> Looks good overall! I left a few comments. Also, it looks like the `CommentContainer` styles for the logged-out state are missing some padding now. Can you take a look at this?

I have no idea what's going on with the padding, but it's happening on develop. Logging a bug ticket.

2022-01-15 00:30 UTC, nick-funk commented
> > Looks good overall! I left a few comments. Also, it looks like the `CommentContainer` styles for the logged-out state are missing some padding now. Can you take a look at this?
> 
> I have no idea what's going on with the padding, but it's happening on develop. Logging a bug ticket.

Found it, also found more bugs in traversal. All should be fixed up now. I noticed it seems to not want to let Z key do anything unless signed in, we might want to revisit this behaviour, but at least this no longer breaks existing padding/traversal flow now!

2022-01-18 14:33 UTC, kabeaty approved these changes
Looks great! Thanks for making the updates.

2022-01-20 16:06 UTC, merged