move notifications to parent
coralproject/talk pull request #387
Opened 2017-03-06 18:17 UTC by riley

## What does this PR do?

We were having issues with the notifications not always showing up or showing up in weird places. This is due to how `position: fixed` interacts with the parent page in different browsers. This PR skirts the problem by moving the notification view code up to the parent embed script, so the notification is just a DOM element that is drawn on the parent. pym is used to send messages.

Pertinent Chrome WontFix bug:
http://stackoverflow.com/questions/8304148/positionfixed-inside-of-an-iframe

## Caveats
The styles for the notification cannot live in `default.css` since those are the styles for the iframe. I ended up inlining the styles in js, **which is gross**. If anyone has better ideas, please let me know and I'll update the PR.

## How do I test this PR?

- post a comment when mod: 'POST'. View the notification
- change settings in the embed on the Configure Stream tab. notifications should appear

2017-03-06 19:01 UTC, davidgljay requested changes
Notifications appear when mod='PRE', but not when mod='POST' (as per testing instructions).

2017-03-06 19:09 UTC, riley commented
Whoops, @davidgljay that was a typo. It's supposed to be `PRE`

2017-03-06 19:24 UTC, okbel requested changes

2017-03-06 19:24 UTC, okbel commented on client/coral-framework/reducers/notification.js
> -  switch (action.type) {
Why did we delete the reducer?

2017-03-06 19:33 UTC, riley commented on client/coral-framework/reducers/notification.js
> -  switch (action.type) {
it's not being used anywhere. I deleted the `<Notification>` component, so nothing was reading its state.

2017-03-06 19:38 UTC, okbel commented on client/coral-framework/reducers/notification.js
> -  switch (action.type) {
Hm. It used to be... but not with this refactor.

2017-03-07 17:45 UTC, davidgljay approved these changes

2017-03-07 19:21 UTC, okbel approved these changes

2017-03-07 19:30 UTC, merged