Fix/corl 2556 focus states
coralproject/talk pull request #4097
Opened 2022-11-22 23:07 UTC by marcushaddon

## What does this PR do?
This PR assigns focus state in such a 

## These changes will impact:

- [x] commenters
- [ ] moderators
- [ ] admins
- [ ] developers

## What changes to the GraphQL/Database Schema does this PR introduce?
None.

## Does this PR introduce any new environment variables or feature flags? 
No.

## If any indexes were added, were they added to `INDEXES.md`?
n/a

## How do I test this PR?
### Add a Comment button
1. Enable alternate oldest first view
2. In the stream, set the view to "Oldest first"
3. Click on the "Add a Comment" button at the top
4. Observe that after scrolling to the bottom of the page, the focus is now in the text box of the comment form.
 
 
## How do we deploy this PR?
No special considerations should be required.

2022-12-09 17:52 UTC, nick-funk requested changes
These fixes make sense, much improved usability here!

I found  a few discrepancies, likely easy fixes though!

* Add a Comment button as a mouse user
    * this works if I am logged in
    * Does not work if I am not signed in (probably just another `forwardRef` + scroll for the non-signed in version of post comment form?)
* Add a Comment button as a keyboard/screen reader user
    * works only if logged in, likely same issue as previous
* Change Password input as a mouse user
    * keyboard focus doesn't seem to be set into the first text field
    * off topic: also the colours are wrong for the focus on this field (admin green instead of stream blue)
* Change Password input as a keyboard user
     * also not working, likely same issue as mouse user for password

2022-12-09 17:52 UTC, nick-funk commented on src/core/client/stream/tabs/Comments/Stream/AddACommentButton.tsx
> +    // TODO for MARCUS: clean this up
is this TODO still valid?

2022-12-13 18:56 UTC, marcushaddon commented on src/core/client/stream/tabs/Comments/Stream/AddACommentButton.tsx
> +    // TODO for MARCUS: clean this up
✅

2022-12-14 21:17 UTC, marcushaddon commented
> These fixes make sense, much improved usability here!
> 
> I found a few discrepancies, likely easy fixes though!
> 
> * Add a Comment button as a mouse user
>   
>   * this works if I am logged in
>   * Does not work if I am not signed in (probably just another `forwardRef` + scroll for the non-signed in version of post comment form?)
> * Add a Comment button as a keyboard/screen reader user
>   
>   * works only if logged in, likely same issue as previous
> * Change Password input as a mouse user
>   
>   * keyboard focus doesn't seem to be set into the first text field
>   * off topic: also the colours are wrong for the focus on this field (admin green instead of stream blue)
> * Change Password input as a keyboard user
>   
>   * also not working, likely same issue as mouse user for password

Update password input should now be receiving focus, as well as the correct highlight color. As for the post log in focus on RTE, it's a bit more involved because even when not logged in, we *are* focusing on the RTE after clicking on "Add a Comment", its just after clicking the "Sign in and join the conversation button" that we "fail" to re-focus on the RTE.

I think it is possible to transmit the intention to refocus on a certain element after a call to `initLocalState`, but I think that feature is outside the scope of this ticket as it is worded, since we have successfully focused on the RTE after "Add a Comment".

2023-01-04 16:11 UTC, nick-funk commented on src/core/client/stream/tabs/Comments/Stream/AddACommentButton.tsx
> +  );
Not bashing you for having to do this as Kathryn has had to do similar in the past to make keyboard shortcuts work... but it makes me sad that React has made us come to this. 😢

2023-01-04 16:12 UTC, nick-funk approved these changes

2023-01-06 14:41 UTC, merged