[CORL-2729] Moderation Queue Focus
coralproject/talk pull request #4158
Opened 2023-02-17 00:21 UTC by marcushaddon

## What does this PR do?
This PR fixes a bug in which upon navigating to `/admin/moderate`, focus immediately shifts to the first moderation card, which is an anti-pattern for accessibility. 

## These changes will impact:

- [ ] commenters
- [x] moderators
- [x] admins
- [ ] developers

## What changes to the GraphQL/Database Schema does this PR introduce?
None.

## Does this PR introduce any new environment variables or feature flags? 
No.

## If any indexes were added, were they added to `INDEXES.md`?
n/a

## How do I test this PR?
1. Ensure that there are multiple comments in the moderation queue
2. As an admin or moderator, navigate to `/admin/moderate`
3. Press the tab key
4. Observe that the focus begins at the first element on the page (the nav at the top) and cycles through the different nav options, rather than skipping them and jumping to the beginning of the mod queue
5. Observe that using the "j" and "k" keys still cycles through mod cards
 
 
## How do we deploy this PR?
No special considerations should be necessary

2023-02-21 16:18 UTC, nick-funk requested changes

2023-02-21 16:18 UTC, nick-funk commented on src/core/client/admin/routes/Moderate/Queue/Queue.tsx
> +    // key(HOTKEYS.REJECT, QUEUE_HOTKEY_ID, onReject);
are these from past debugging or do they need to be uncommented?

2023-02-21 16:18 UTC, nick-funk commented on src/core/client/admin/routes/Moderate/Queue/Queue.tsx
> +    // key.deleteScope(id);
old debug code?

2023-02-21 21:03 UTC, marcushaddon commented on src/core/client/admin/routes/Moderate/Queue/Queue.tsx
> +    // key.deleteScope(id);
✅

2023-03-08 17:00 UTC, nick-funk approved these changes
Looks good! Nice work!

2023-03-17 12:59 UTC, merged