[CORL-2766] protect common email domains from domain moderation
coralproject/talk pull request #4174
Opened 2023-03-09 21:11 UTC by marcushaddon

## What does this PR do?
This PR creates a hardcoded list of email domains considered to common to be moderated domain-wide.

## These changes will impact:

- [x] commenters
- [x] moderators
- [x] admins
- [ ] developers

## What changes to the GraphQL/Database Schema does this PR introduce?
None.

## Does this PR introduce any new environment variables or feature flags? 
No.

## If any indexes were added, were they added to `INDEXES.md`?
n/a

## How do I test this PR?
1. As an org mod or admin attempt to ban any of the following domains, either through the checkbox presented while managing a user's ban status, or under Configure > Moderation > Email Domain
voxmedia.com
gmail.com
gmail.co.uk
aol.com
att.net
duck.com
verizon.net
yahoo.com
yahoo.co.nz
yahoo.com.au
yahoo.co.za
xtra.co.nz
btinternet.com
yahoo.se
comcast.net
outlook.com
icloud.com
rr.com
hotmail.com
hotmail.co.uk
hotmail.es
hotmail.fr
msn.com
me.com
live.co.uk
live.com
live.co.za
rogers.com
global.co.za
ncacoral.com.au
proton.me
westnet.com.au
laposte.net
free.fr
orange.fr
outlook.fr
yahoo.fr
online.no
live.no
yahoo.no
hotmail.no
2. Observe that the domain is not moderated (in the configure view, you should see a detailed error message. In the user ban status modal, you will not see any indication that the email domain ban failed, which is a preexisting behavior and is out of the scope of this ticket).
 
## How do we deploy this PR?
No special considerations should be necessary.

2023-03-10 17:45 UTC, nick-funk commented
How do we feel about adding `fastmail.com` to this list? I only ask as I see we added `proton.me` to this list already.

2023-03-10 17:58 UTC, nick-funk approved these changes
Works as labelled! Ship it!

2023-03-10 18:15 UTC, kabeaty requested changes
Looks good overall! Left a small comment. Also, I'm seeing an error thrown when testing out using the user ban status modal to apply a common email ban that I think we will need to handle? And are you able to add a quick test for these common email domains not being able to be banned, as well?

2023-03-10 18:15 UTC, kabeaty commented on src/core/server/services/tenant/tenant.ts
> +import { PROTECTED_EMAIL_DOMAINS } from "coral-common/constants";
Can you move these imports up?

2023-03-13 17:17 UTC, marcushaddon commented on src/core/server/services/tenant/tenant.ts
> +import { PROTECTED_EMAIL_DOMAINS } from "coral-common/constants";
✅

2023-03-14 14:36 UTC, kabeaty approved these changes
Looks good, thanks for the updates! Just one more small comment, but approving!

2023-03-14 14:36 UTC, kabeaty commented on src/core/server/services/tenant/tenant.ts
> +import { ERROR_CODES } from "coral-common/errors";
one more import to move up :)

2023-03-20 17:44 UTC, marcushaddon commented on src/core/server/services/tenant/tenant.ts
> +import { ERROR_CODES } from "coral-common/errors";
✅

2023-03-20 18:14 UTC, merged