Update settings in ui
coralproject/talk pull request #42
Opened 2016-11-08 23:26 UTC by riley

## What does this PR do?

You can update moderation pre/post in coral-admin!

## How do I test this PR?

- `npm run build`
- go to `/configure`
- click the `Enable pre moderation checkbox`
- click Save
- wow

@coralproject/tech

2016-11-08 23:46 UTC, wyattjoh requested changes

2016-11-08 23:46 UTC, wyattjoh commented on .eslintrc.json
> +    },
These global's aren't necessary. Right now, the `client` folder isn't linted. When it is, we can specify `browser: true` in the `env` object which will enable these globals automatically.

Recommended action, remove the `globals` object.

2016-11-09 19:24 UTC, jde commented
The settings aren't saving. When I save the endpoint replies with a null.  Refreshing the page, the setting is not loaded.

2016-11-09 22:35 UTC, wyattjoh approved these changes

2016-11-09 22:35 UTC, merged