[CORL-2856] Single site ban options
coralproject/talk pull request #4285
Opened 2023-07-05 18:16 UTC by marcushaddon

## What does this PR do?
This PR addresses a bug in which options specific to multi site tenenants were displayed for single site tenants when managing a user's ban status.

## These changes will impact:

- [ ] commenters
- [x] moderators
- [x] admins
- [ ] developers

## What changes to the GraphQL/Database Schema does this PR introduce?
None.

## Does this PR introduce any new environment variables or feature flags?
No.

## If any indexes were added, were they added to `INDEXES.md`?
n/a
-->

## How do I test this PR?
On a single site tenant, as a user with ban management privileges, navigate to the community page, and click to manage a user's ban status. Observe that no radio buttons related to "All sites", "Specific sites" or "No sites" are displayed.

## Where any tests migrated to React Testing Library?
No.

## How do we deploy this PR?
No special considerations should be required

2023-07-07 13:16 UTC, kabeaty requested changes
Looks good! Just a few small comments.

2023-07-07 13:16 UTC, kabeaty commented on src/core/client/admin/test/community/banUser.spec.tsx
> +it.only("displays limited options for single site tenants", async () => {
Yay, thanks for adding this test! It does look like an `only` snuck in here...can you please remove? :)

2023-07-07 13:16 UTC, kabeaty commented on src/core/client/admin/test/community/banUser.spec.tsx
> +  // MARCUS: why is this passing?
Can you remove this comment? Is it resolved?

2023-07-07 13:16 UTC, kabeaty commented on src/core/client/admin/test/community/banUser.spec.tsx
> +  expect(
Seems like we only find this text with `queryByLabelText`? And above we expected to find it? I just want to make sure I understand why we're also checking that it's not in the document here.

2023-07-11 16:24 UTC, marcushaddon commented on src/core/client/admin/test/community/banUser.spec.tsx
> +  // MARCUS: why is this passing?
✅

2023-07-11 16:57 UTC, marcushaddon commented on src/core/client/admin/test/community/banUser.spec.tsx
> +it.only("displays limited options for single site tenants", async () => {
✅

2023-07-11 17:42 UTC, marcushaddon commented on src/core/client/admin/test/community/banUser.spec.tsx
> +  // MARCUS: why is this passing?
✅

2023-07-11 17:42 UTC, marcushaddon commented on src/core/client/admin/test/community/banUser.spec.tsx
> +  expect(
✅

2023-07-11 18:21 UTC, kabeaty approved these changes

2023-07-19 21:19 UTC, nick-funk approved these changes

2023-07-24 21:16 UTC, merged