[CORL-2835] Reject all comments in queue
coralproject/talk pull request #4291
Opened 2023-07-10 19:55 UTC by marcushaddon

## What does this PR do?
This PR implements a feature in which selecting to reject all comments from a user while banning them will cause those comments to disappear from the moderation queue.

## These changes will impact:

- [ ] commenters
- [x] moderators
- [x] admins
- [ ] developers

## What changes to the GraphQL/Database Schema does this PR introduce?
The `User` type has been extended on the frontend to include a boolean flag for `allCommentsRejected`

## Does this PR introduce any new environment variables or feature flags?
No.

## If any indexes were added, were they added to `INDEXES.md`?
n/a

## How do I test this PR?
1. As a user with moderation privileges, navigate to the moderation queue.
2. Use the "b" key to open the ban modal for one of the comments' authors
3. Check the box for "reject all comments by this user"
4. Ban the user
5. Observe that any other comments by that user currently in the moderation queue should disappear.

## Where any tests migrated to React Testing Library?
No.

## How do we deploy this PR?
No special considerations should be required.

2023-07-11 22:20 UTC, marcushaddon commented on src/core/client/admin/test/moderate/regularQueue.spec.tsx
> +  act(() => {
I timeboxed my attempt to open the ban modal via keyboard shortcut, but if anyone has done this successfully, let me know!

2023-07-13 14:11 UTC, kabeaty requested changes
This works well for the case where a user is banned across all sites via the ban modal. Should it also work when a user is banned across specific sites and has all comments rejected for the corresponding site(s)?

Also, I think it could be possible for the ban to send back an error but the comments to still be set to be filtered out in the mod queue. Would it be better to set the `allCommentsRejected` to true after the ban/rejection has successfully gone through?

2023-07-13 14:11 UTC, kabeaty commented on src/core/client/admin/local/local.graphql
> +  allCommentsRejected: Boolean
Could you please add a comment explaining this field and what it's used for, for future reference?

2023-07-13 14:11 UTC, kabeaty commented on src/core/client/admin/test/moderate/regularQueue.spec.tsx
> +import { commitLocalUpdate } from "relay-runtime";
Can you please move this import up into the correct section of imports?

2023-07-13 14:11 UTC, kabeaty commented on buildlog
> +> @coralproject/talk@8.2.3 build:development
Looks like this file accidentally got added?

2023-07-14 17:50 UTC, marcushaddon commented on src/core/client/admin/local/local.graphql
> +  allCommentsRejected: Boolean
✅

2023-07-14 17:51 UTC, marcushaddon commented on src/core/client/admin/test/moderate/regularQueue.spec.tsx
> +import { commitLocalUpdate } from "relay-runtime";
✅

2023-07-24 22:59 UTC, marcushaddon commented on buildlog
> +> @coralproject/talk@8.2.3 build:development
✅

2023-07-27 17:22 UTC, kabeaty requested changes
Thanks for the updates! It looks like it's still not working though when a user is banned across specific sites and has all comments rejected for the corresponding site(s). I think it's because `rejectExistingComments` isn't being passed through to the `updateUserBan` in `BanModal.tsx`. Looks like this was for some reason removed [here in this PR](https://github.com/coralproject/talk/pull/4127/files#diff-386f7d575ccfab29137cf084cb57b883484db9cc4b2fb9478addad6504299ffbR207). Can you take a look and add it back in?

2023-08-03 18:59 UTC, kabeaty approved these changes

2023-08-18 14:52 UTC, merged