Auto close comment toggle
coralproject/talk pull request #441
Opened 2017-03-24 16:44 UTC by riley

## What does this PR do?

Default to not auto-closing a comment stream after 2 weeks.

## How do I test this PR?

- create a new asset
- check the db to make sure there's no `closedAt` date set on the record.

2017-03-24 17:14 UTC, wyattjoh requested changes

2017-03-24 17:14 UTC, wyattjoh commented on services/assets.js
> +          $setOnInsert: setOnInsert,
This isn't valid, you need to include this in the second parameter to `findOneAndUpdate`, not in the options (this third parameter)

2017-03-27 12:04 UTC, kgardnr commented
This LGTM! Just want to check if @wyattjoh's good with it and we can demo and merge today.

2017-03-27 13:40 UTC, wyattjoh approved these changes

2017-03-27 15:07 UTC, merged