Plugin Architecture [WIP]
coralproject/talk pull request #455
Opened 2017-03-30 16:10 UTC by okbel

Submiting a PR so the team can take a look at the code while I'm building plugins

2017-03-31 04:43 UTC, wyattjoh commented on .eslintrc.json
> +    "parser": "babel-eslint",
Modifications to the project wide `.eslintrc.json` file will affect server side code too. We should not be applying linting rules to the server that are reflective of client side concerns, such as `parserOptions.sourceType = module`, which the server does not support.

2017-04-03 12:38 UTC, cvle commented on client/coral-embed-stream/src/Comment.js
> +        <div id="Comment.InfoBar">
Why is the `id` needed?

2017-04-03 12:42 UTC, cvle commented on plugins/coral-plugin-love/client/config.json
> +  "slot": "Comment.Detail"
I'm not sure about this naming convention. We probably need to talk with everyone and agree on a naming scheme. I personally prefer something like `comment.detail` and `comment.infoBar`.

2017-04-03 12:47 UTC, cvle commented on plugins/coral-plugin-respect/client/style.css
> +.Respect {
Why naming the class with a initial capital letter?

2017-04-03 12:49 UTC, okbel commented on plugins/coral-plugin-love/client/config.json
> +  "slot": "Comment.Detail"
Comment is a Class and a Component, that's the reason behind it. Not strongly against it either. We can change it.

2017-04-03 12:50 UTC, cvle commented on plugins/coral-plugin-respect/client/style.css
> +    button {
This should be a top-level class.

2017-04-03 12:50 UTC, cvle commented on plugins/coral-plugin-respect/client/style.css
> +    .respected {
This should be a top-level class.

2017-04-03 12:51 UTC, cvle commented on plugins/coral-plugin-respect/client/style.css
> +        i {
This should be a top-level class.

2017-04-03 12:51 UTC, cvle commented on plugins/coral-plugin-respect/client/style.css
> +    i {
This should be a top-level class.

2017-04-03 12:55 UTC, cvle commented on plugins/coral-plugin-respect/client/style.css
> +    button {
The reasons for this is, that we want to isolate the styles for this Component and don't leak out styles that might affect other components.

2017-04-03 14:07 UTC, cvle commented
Note: Sometimes we use the term `mutators` and sometimes `mutations` for the same thing. We should pick one and use it consequently.

2017-04-03 14:11 UTC, jde commented on plugins/coral-plugin-love/client/config.json
> +  "slot": "Comment.Detail"
I like the idea of sticking to a simple convention like camelCase unless there's an already established convention in the community. I know that the variables themselves are traditionally capitalized, but these strings are grey area. I would probably default to camel case here to keep the concept simple.

2017-04-03 14:34 UTC, wyattjoh commented on .gitignore
> +# plugins.json
We should not exclude these from git, instead you should write as such:

```
plugins
!plugins/core-coral-plugin-1
!plugins/core-coral-plugin-2
```

2017-04-06 21:02 UTC, riley requested changes

2017-04-06 21:02 UTC, riley commented on client/coral-framework/helpers/plugins.js
> +import plugins from 'pluginsConfig';
Why does this need an alias? Can't we just import the `plugins.json` file?

2017-04-06 21:02 UTC, riley commented on client/coral-framework/index.js
> +  ...actions
This is going to confuse people. Could you add a comment here to explain what's going on?

2017-04-06 21:02 UTC, riley commented on client/coral-framework/components/Slot.js
> +
could we get some `PropTypes` here? Also, this component would be a great place to add a ton of comments to help guide contributors trying to create their own plugin.

2017-04-06 21:02 UTC, riley commented on client/coral-framework/loaders/plugins-loader.js
> + * Executes `source` to retrieve plugins configuration
what is `source`?

2017-04-06 21:02 UTC, riley commented on client/coral-framework/loaders/plugins-loader.js
> +  plugins.forEach(plugin => {
this could just be a `map` on the plugins list.

2017-04-06 21:02 UTC, riley commented on client/coral-framework/utils/index.js
> +export const getActionSummary = (type, comment) => comment.action_summaries
this is a long expression without an explanation. probably need a comment here.

2017-04-06 21:02 UTC, riley commented on plugins/coral-plugin-respect/client/.eslintrc.json
> +  "parserOptions": {
I think this needs `ecmaVersion: 8` to work properly with async/await keywords.

2017-04-06 21:02 UTC, riley commented on plugins/coral-plugin-respect/client/components/RespectButton.js
> +
need some `PropTypes` all up in here.

2017-04-06 21:02 UTC, riley commented on plugins/coral-plugin-respect/client/components/RespectButton.js
> +      const offset = document.getElementById(`c_${commentId}`).getBoundingClientRect().top - 75;
this probably needs to be wrapped in a `try / catch` since we're calling a method after querying the DOM.

2017-04-06 21:02 UTC, riley commented on test/server/graph/context.js
> +const User = require('../../../models/user');
this might be dumb, but is there a way to not have all these horrible relative paths in require statements in node?

2017-04-06 21:06 UTC, okbel commented on plugins/coral-plugin-respect/client/.eslintrc.json
> +  "parserOptions": {
That's specific for each plugin.

2017-04-06 21:07 UTC, riley commented on plugins/coral-plugin-respect/client/.eslintrc.json
> +  "parserOptions": {
oh right. carry on.

2017-04-06 21:10 UTC, okbel commented on client/coral-framework/index.js
> +  ...actions
This is a hack that we are going to address in another PR. Right now this is needed. (It's about our legacy code)

2017-04-06 21:10 UTC, okbel commented on client/coral-framework/loaders/plugins-loader.js
> + * Executes `source` to retrieve plugins configuration
The plugins path

2017-04-06 21:10 UTC, okbel commented on client/coral-framework/utils/index.js
> +export const getActionSummary = (type, comment) => comment.action_summaries
👍

2017-04-06 21:12 UTC, cvle commented on client/coral-framework/loaders/plugins-loader.js
> + * Executes `source` to retrieve plugins configuration
The output of the `loader` before this one, which currently is the `json-loader`.

2017-04-06 21:13 UTC, cvle commented on client/coral-framework/utils/index.js
> +export const getActionSummary = (type, comment) => comment.action_summaries
Not used.

2017-04-06 21:15 UTC, cvle commented on client/coral-framework/loaders/plugins-loader.js
> +  plugins.forEach(plugin => {
Not sure what you mean. The result is javascript code btw. for anyone who never wrote a webpack loader.

2017-04-06 21:22 UTC, riley commented on client/coral-framework/loaders/plugins-loader.js
> +  plugins.forEach(plugin => {
sorry, I didn't mean a `Map`, I meant `Array.prototype.map`

2017-04-06 21:22 UTC, riley commented on client/coral-framework/index.js
> +  ...actions
maybe just a `//TODO` then for now

2017-04-06 21:42 UTC, okbel commented on client/coral-framework/helpers/plugins.js
> +import plugins from 'pluginsConfig';
We are using an alias because otherwise we would end up with `../../../../`etc

2017-04-06 21:56 UTC, wyattjoh submitted a review, later dismissed
Putting this here to stop merge before some validation fixes get in

2017-04-06 23:49 UTC, riley approved these changes

2017-04-07 01:12 UTC, merged

2017-04-07 01:35 UTC, marcosnils commented
this is awesome, congrats! :tada: . No official docs for the client side plugins besides this PR comments?

2017-04-07 03:43 UTC, okbel commented
@marcosnils We are working on the FE docs, examples with simple to complex plugins (with uptimistic updates) and also tutorials! 🎉

2017-04-07 09:51 UTC, cvle commented on client/coral-framework/index.js
> +  ...actions
I don't think this is used anywhere bel, correct me if I'm wrong.

2017-04-07 09:51 UTC, cvle commented on client/coral-framework/utils/index.js
> +export const getActionSummary = (type, comment) =>
This is also not used anywhere, as we rely on graphQL to get the correct type.

2017-04-07 10:46 UTC, cvle commented on test/server/graph/context.js
> +const User = require('../../../models/user');
It's possible to use `https://www.npmjs.com/package/babel-plugin-module-alias` or `https://www.npmjs.com/package/babel-plugin-webpack-alias` which would require `babel-node`.