Clicking '# comments' tab refresh all the comments back
coralproject/talk pull request #485
Opened 2017-04-11 22:06 UTC by gabelula

## What does this PR do?

It resolves story https://www.pivotaltracker.com/story/show/143520139

It adds an action to the tab "# Comments". Now it is clickable and bring back all the comments.

## How do I test this PR?

- Go to a permalink
- Click on the tab "# comments"
- Check that you get all the comments back

2017-04-11 22:13 UTC, wyattjoh requested changes

2017-04-11 22:13 UTC, wyattjoh commented on client/coral-embed-stream/src/Embed.js
> +                this.props.data.refetch();
Can you move this to a class method instead?

2017-04-11 23:13 UTC, okbel commented on client/coral-embed-stream/src/Embed.js
> +                this.props.data.refetch();
Agreed.

2017-04-11 23:13 UTC, okbel commented on client/coral-plugin-comment-count/CommentCount.js
> +  return <div className={`${name}-text`} onClick={() => onClick()}>
change the name to `handleClick` and pass it without wrapping it into another function if possible

2017-04-12 00:58 UTC, gabelula commented on client/coral-embed-stream/src/Embed.js
> +                this.props.data.refetch();
Agree. Done.

2017-04-12 00:59 UTC, gabelula commented on client/coral-plugin-comment-count/CommentCount.js
> +  return <div className={`${name}-text`} onClick={() => onClick()}>
Done.

2017-04-12 11:20 UTC, cvle commented on client/coral-embed-stream/src/Embed.js
> +      false, activeReplyBox: ''
`false` seems to be on the wrong line

2017-04-12 11:20 UTC, cvle commented on client/coral-embed-stream/src/Embed.js
> +    this.handleClick = this.handleClick.bind(this);
See below

2017-04-12 11:29 UTC, cvle commented on client/coral-embed-stream/src/Embed.js
> +  handleClick() {
You can just do `handleClick = () => {` to have it automatically bound to `this`.

2017-04-12 11:36 UTC, cvle commented on client/coral-embed-stream/src/Embed.js
> +              handleClick={this.handleClick}/>
I think the `refetching` logic should be in `changeTab` and not on a clickable `Count`.
There is already a logic that was wrongly changed to only `refetch` for admins. 
You should remove that check and add your logic to show all comments.

2017-04-12 11:37 UTC, cvle commented on client/coral-plugin-comment-count/CommentCount.js
> +const CommentCount = ({count, handleClick}) => {
See above

2017-04-12 17:10 UTC, gabelula commented on client/coral-embed-stream/src/Embed.js
> +              handleClick={this.handleClick}/>
That is refactoring of the code, can we leave that for a refactoring story/PR ?

2017-04-12 17:19 UTC, gabelula commented on client/coral-embed-stream/src/Embed.js
> +              handleClick={this.handleClick}/>
The issue is that this logic is also used by the Show all comments button. 

And I agree about the issue on isAdmin only refetching data. Let's work that out in other story.

2017-04-12 17:33 UTC, cvle commented on client/coral-embed-stream/src/Embed.js
> +              handleClick={this.handleClick}/>
No it's perfect there. The `isAdmin` was a merge mistake. It should never have been there. 
Just remove the  `isAdmin` and put the `his.props.viewAllComments();` over `refetch` and everything should work.

2017-04-12 17:36 UTC, cvle commented on client/coral-embed-stream/src/Embed.js
> +              handleClick={this.handleClick}/>
Also we already have  `changeTab` for tab changing logic and we shouldn't spread these into different callbacks.

2017-04-12 17:38 UTC, gabelula commented on client/coral-embed-stream/src/Embed.js
> +              handleClick={this.handleClick}/>
Yes. I see that. The issue is that each time it comes from other tab by click '# comments' it will refetch twice.

2017-04-12 18:11 UTC, wyattjoh approved these changes

2017-04-12 18:43 UTC, alinhle requested changes

2017-04-12 18:43 UTC, cvle commented on client/coral-plugin-comment-count/CommentCount.js
> +const CommentCount = ({count, handleClick}) => {
You still need to remove the `handleClick` stuff

2017-04-12 18:57 UTC, cvle commented on client/coral-embed-stream/src/Embed.js
> +  }
This also needs to be removed

2017-04-12 18:57 UTC, alinhle approved these changes

2017-04-12 18:57 UTC, cvle commented on client/coral-embed-stream/src/Embed.js
> +              handleClick={this.handleClick}/>
And the `handleClick` here :-)

2017-04-12 18:58 UTC, cvle commented
I removed my merge block (because I will go to sleep), so once you applied the last suggestions, this is good to go.

2017-04-12 19:11 UTC, merged