User detail ui
coralproject/talk pull request #564
Opened 2017-05-04 17:22 UTC by riley

## What does this PR do?

## How do I test this PR?

- click a button
- view the cat
- see the cat meow

2017-05-05 14:02 UTC, wyattjoh requested changes

2017-05-05 14:02 UTC, wyattjoh commented on client/coral-admin/src/containers/ModerationQueue/UserDetail.js
> +    const facebookProfile = user.profiles.find(p => p.provider === 'facebook');
This should not reference plugins content. We should instead utilize slots to inject Facebook details into the user detail pane.

2017-05-17 20:40 UTC, kgardnr approved these changes

2017-05-17 20:40 UTC, wyattjoh approved these changes

2017-05-17 20:41 UTC, merged