Multiple roles
coralproject/talk pull request #585
Opened 2017-05-12 15:59 UTC by riley

## What does this PR do?

## How do I test this PR?

- click a button
- view the cat
- see the cat meow

2017-05-12 20:07 UTC, wyattjoh requested changes

2017-05-12 20:07 UTC, wyattjoh commented on models/user.js
> +  return !!intersection(['ADMIN', 'MODERATOR'], this.roles).length;
Just leaving a note about pulling these functions out before it's merged :)

2017-05-18 20:18 UTC, wyattjoh requested changes

2017-05-18 20:18 UTC, wyattjoh commented on models/user.js
> +  return !!intersection(['ADMIN', 'MODERATOR', 'STAFF'], this.roles).length;
Replace logical comparison with:

```diff
- return !!intersection(['ADMIN', 'MODERATOR', 'STAFF'], this.roles).length;
+ return intersection(['ADMIN', 'MODERATOR', 'STAFF'], this.roles).length !== 0;
```

2017-05-18 20:18 UTC, wyattjoh commented on perms/mutationReducer.js
> +const check = (user, roles) => {
Abstract the `check` function into a util.js file in perms that is imported.

2017-05-18 20:18 UTC, wyattjoh commented on perms/queryReducer.js
> +const check = (user, roles) => {
Abstract the `check` function into a util.js file in perms that is imported.

2017-05-18 20:18 UTC, wyattjoh commented on perms/rootReducer.js
> +  DUMMY_ROLE: 'DUMMY_ROLE',
Remove `DUMMY_ROLE`

2017-05-18 20:18 UTC, wyattjoh commented on perms/rootReducer.js
> +    switch (perm) {
Remove empty switch statement.

2017-05-18 20:18 UTC, wyattjoh commented on services/users.js
> +    return UserModel.update({id}, {$set: {roles: [role]}});
Remove comment.

2017-05-18 20:35 UTC, wyattjoh approved these changes

2017-05-19 13:51 UTC, alinhle requested changes
Don't get me wrong, this all looks great 👍  Just want to sync with Riley about handling suspended and banned users before we merge this.

2017-05-19 16:26 UTC, alinhle approved these changes

2017-05-19 19:12 UTC, merged