Refactor i18n
coralproject/talk pull request #586
Opened 2017-05-12 20:06 UTC by gabelula

## What does this PR do?

- Moves i18n module from framework to its own coral-i18n
- Moves translations to YAML file

## How do I test this PR?

- Run the server and check that everything is working

## To Do

- Merge translations.json into YAML files for es and en

2017-05-16 15:48 UTC, cvle commented on plugins/coral-plugin-love/client/components/LoveIcon.js
> +import React from 'react';
This file looks like a merge error.

2017-05-16 15:48 UTC, cvle commented on plugins/coral-plugin-love/client/components/style.css
> +.love {
This file looks like a merge error.

2017-05-16 15:48 UTC, cvle commented on plugins/coral-plugin-love/client/containers/LoveIcon.js
> +import {compose, gql, graphql} from 'react-apollo';
This file looks like a merge error.

2017-05-16 15:57 UTC, alinhle requested changes
1. Locale data is one of the biggest contributor to bundle sizes. We don't want to include all translations of all targets and all embeds into every bundle.

2. The spanish translation for the `timeago.js` has been removed with these changes without providing an alternative solution. Ideally we want to integrate `timeago.js` into our translation framework.

2017-05-16 17:25 UTC, gabelula commented on plugins/coral-plugin-love/client/containers/LoveIcon.js
> +import {compose, gql, graphql} from 'react-apollo';
Yes. I'm taking a look at which files came from that merge.

2017-05-16 17:28 UTC, gabelula commented
1. Yes. I'm concern about this but not sure how it would be resolved.

2. Let me look into that. It may be also related to the merge.

2017-05-19 12:31 UTC, cvle commented on plugins/coral-plugin-love/client/index.js
> +Promise.all([loadTranslations(translations)]);
We shouldn't need a promise here, as loading translations is synchronous.

2017-05-19 12:32 UTC, cvle commented on plugins/coral-plugin-like/client/index.js
> +Promise.all([loadTranslations(translations)]);
We shouldn't need a promise here, as loading translations is synchronous.

2017-05-19 12:37 UTC, cvle commented on client/coral-i18n/services/i18n.js
> +const time = require('timeago.js');
We should use es6 modules rather than a mix of nodejs require style and es6.

2017-05-19 12:39 UTC, cvle commented on client/coral-i18n/services/i18n.js
> +  translations = require(`json-loader!yaml-loader!../locales/${locale}.yml`)[locale];
This has no benefit over just importing all our current locals with simple static import statements. The fetchTranslations function shouldn't be needed as all translations should come from the bundle.

2017-05-19 16:14 UTC, kgardnr commented
Two things to address @gabelula:

- [ ] Move the locales to the projects top level

- [ ] Avoid creating another folder `coral-i18n` in the `client` folder. I believe that each folder should have a clear role and from my understanding `coral-framework` should contain all the shared logic between all our different targets and embeds and is the correct place to put our translation service. 

@cvle let me know if I missed anything here!

2017-05-19 16:57 UTC, cvle commented
That looks file Kim. Plus the comments from my review.

2017-05-19 17:24 UTC, gabelula commented on plugins/coral-plugin-love/client/index.js
> +Promise.all([loadTranslations(translations)]);
Yes. I was going to remove that and then I forgot when everything was working fine :/

2017-05-19 17:28 UTC, gabelula commented
The locales are being used by the i18n service. We move the i18n service to the top level OR we move it into the framework. They should all be in the same place.

2017-05-23 15:52 UTC, cvle commented on plugins/coral-plugin-love/client/components/style.css
> +.love {
This file should be removed, it doesn't exist in master (merge error).

2017-05-23 15:52 UTC, cvle commented on plugins/coral-plugin-love/client/containers/LoveIcon.js
> +import {compose, gql, graphql} from 'react-apollo';
This file should be removed, it doesn't exist in master (merge error).

2017-05-23 15:52 UTC, cvle commented on plugins/coral-plugin-love/client/components/LoveIcon.js
> +import React from 'react';
This file should be removed, it doesn't exist in master (merge error).

2017-05-23 15:55 UTC, cvle commented on plugins/coral-plugin-love/client/index.js
> +Promise.all([loadTranslations(translations)]);
This promise looks obsolete

2017-05-23 15:59 UTC, cvle commented on client/coral-embed-stream/src/index.js
> +loadTranslations();
Why do we need to explicitly `loadTranslations`? All translations are already in the bundle.

2017-05-23 15:59 UTC, cvle commented on client/coral-framework/index.js
> +loadTranslations();
See above

2017-05-23 16:02 UTC, cvle commented on client/coral-framework/services/i18n.js
> +  translations = require(`json-loader!yaml-loader!../locales/${locale}.yml`)[locale];
Webpack statically analyses all required files and put them in the bundle, it is not necessary to `fetchTranslations`.

2017-05-23 16:03 UTC, cvle commented on client/coral-framework/services/i18n.js
> +const time = require('timeago.js');
Our goal is to use es6 modules whenever we can. All nodejs `require` code should be changed to es6 modules.

2017-05-23 16:06 UTC, cvle commented on client/coral-framework/services/i18n.js
> +const time = require('timeago.js');
es6 modules are better statically analysable and enables advanced features like tree-shaking.

2017-05-23 16:25 UTC, cvle commented on plugins/coral-plugin-like/client/index.js
> +Promise.all([loadTranslations(translations)]);
Another Promise here.

2017-05-23 18:48 UTC, cvle commented
![image](https://cloud.githubusercontent.com/assets/14221600/26370782/11e32300-4023-11e7-9dd8-fef4af5dfc09.png)
Some more missing keys. This needs thorough testing, to catch all missing keys.

2017-05-24 07:30 UTC, cvle commented on client/coral-admin/src/containers/ModerationQueue/helpers/moderationQueueActionsMap.js
> +  'FLAGGED': {status: 'FLAGGED', text: 'rlag', icon: 'flag', filter: 'Untouched'},
I think this should be `flag`, also there seems to be no translation.

2017-05-24 07:52 UTC, cvle commented on client/coral-admin/src/containers/ModerationQueue/helpers/moderationQueueActionsMap.js
> +  'BAN': {status: 'BANNED', text: 'ban_user', icon: 'not interested'},
Do we need a translation for this?

2017-05-24 09:24 UTC, cvle commented
![image](https://cloud.githubusercontent.com/assets/14221600/26396429/712376d8-409d-11e7-8d30-ea18b72a9566.png)
Still some missing keys

2017-05-24 15:32 UTC, gabelula commented on client/coral-admin/src/containers/ModerationQueue/helpers/moderationQueueActionsMap.js
> +  'BAN': {status: 'BANNED', text: 'ban_user', icon: 'not interested'},
Done

2017-05-24 15:32 UTC, gabelula commented
Added translation keys.

2017-05-24 16:11 UTC, cvle commented
Did you forget to push?

2017-05-24 16:17 UTC, cvle commented
I still have these warnings:
![image](https://cloud.githubusercontent.com/assets/14221600/26413729/118eb16c-40d7-11e7-9716-7df9b09a2a5d.png)

2017-05-24 16:30 UTC, gabelula commented
Can you pull again? That commit is already pushed with all those strings.

2017-05-24 16:33 UTC, cvle commented
I am testing on the newest commit. They appear when I go to the Community view in admin.

2017-05-25 13:02 UTC, cvle commented
![screen shot 2017-05-25 at 19 56 38](https://cloud.githubusercontent.com/assets/14221600/26451138/f58db02c-4184-11e7-8807-e092b5cc2e94.png)
![screen shot 2017-05-25 at 19 59 50](https://cloud.githubusercontent.com/assets/14221600/26451139/f5c4613a-4184-11e7-9318-a98fd25abbd1.png)
![screen shot 2017-05-25 at 19 55 54](https://cloud.githubusercontent.com/assets/14221600/26451140/f5d850dc-4184-11e7-9bb2-002356cff7a6.png)
![screen shot 2017-05-25 at 20 00 11](https://cloud.githubusercontent.com/assets/14221600/26451141/f5d95a04-4184-11e7-8750-4455c13d51fe.png)
![image](https://cloud.githubusercontent.com/assets/14221600/26451161/0f3fb1fa-4185-11e7-8ad1-ef8a91ffccb3.png)

Still a bunch of missing keys

2017-05-25 17:15 UTC, cvle commented
Some of the above keys are still missing..
![image](https://cloud.githubusercontent.com/assets/14221600/26461678/31940cba-41a8-11e7-85a8-d495b0f52438.png)
![image](https://cloud.githubusercontent.com/assets/14221600/26461689/3a73d0cc-41a8-11e7-8acd-765ac05abfd7.png)
![image](https://cloud.githubusercontent.com/assets/14221600/26461700/43ed791e-41a8-11e7-80df-6075aefa10f5.png)

2017-05-25 20:27 UTC, alinhle approved these changes

2017-05-25 20:27 UTC, cvle commented
Approving everything but my own commits as usual :-)

2017-05-29 14:59 UTC, merged