Look for tokens passed through embed and handle them
coralproject/talk pull request #624
Opened 2017-05-31 21:23 UTC by jde

## What does this PR do?

Allows auth tokens to be passed in through the embed string and used in all requests.

## How do I test this PR?

- Generate a token
- Pass it into the embed via the authToken param
- If the server accepts the token, you should be logged in like magic

2017-06-01 09:50 UTC, cvle commented on views/article.ejs
> +        authToken: '',
Should this be camelCase or snake_case?

2017-06-01 09:54 UTC, cvle commented on client/coral-embed-stream/src/actions/config.js
> +    handleAuthToken(config.authToken);
To conform with the rest of the application, this should be dispatched.

2017-06-01 19:07 UTC, alinhle requested changes
I think we should avoid persisting the third party token. This token is generated and passed by the host site and usually it is already persistent somewhere, where the host site has access. This avoids having the token persisted at several places which is good for security. I'm  open for discussion.

2017-06-02 18:23 UTC, jde commented
Closing in favor of approach here: https://github.com/coralproject/talk/pull/638

2017-06-02 18:23 UTC, closed without merging