Auth - [DONT MERGE]
coralproject/talk pull request #64
Opened 2016-11-14 19:29 UTC by okbel

Wip

2016-11-17 17:06 UTC, okbel commented
@wyattjoh @impronunciable Can you take a look at this PR? :) Let me know what you think!

2016-11-17 17:12 UTC, wyattjoh requested changes

2016-11-17 17:12 UTC, wyattjoh commented on redis.js
> +    if (options.error.code === 'ECONNREFUSED') {
Change this line to:

```
if (options.error && options.error.code === 'ECONNREFUSED') {
```

2016-11-17 17:12 UTC, wyattjoh commented on redis.js
> +// });
Delete this commented out code.

2016-11-17 18:49 UTC, gabelula commented on client/coral-framework/helpers/error.js
> +  password: 'Password must be at least 8 characters',
we are not translating these?

2016-11-17 19:27 UTC, gabelula requested changes

2016-11-17 19:27 UTC, gabelula commented on client/coral-plugin-commentbox/CommentBox.js
>      // How to handle language in plugins? Should we have a dependency on our central translation file?
let's remove this comment.

2016-11-17 19:54 UTC, gabelula approved these changes

2016-11-17 20:14 UTC, gabelula commented
There is still a file that miss the change from i18n to modules.  The file `client/coral-admin/src/containers/Community/NoResults.js

2016-11-17 21:12 UTC, wyattjoh approved these changes

2016-11-18 10:43 UTC, okbel commented
@wyattjoh @gabelula All changes applied. Thank you both. Email Availability has been removed :(
Feel free to test and merge! 👍

2016-11-18 11:40 UTC, gabelula approved these changes

2016-11-18 11:41 UTC, merged