Highlighting Links and New plugin: coral-plugin-comment-content
coralproject/talk pull request #675
Opened 2017-06-12 22:20 UTC by okbel

# Highlighting Links and New plugin: coral-plugin-comment-content

## What does this PR do?
This PR adds `coral-plugin-comment-content`.

- Enables full customization of the comment body/content.
- Enables highlighting for links in comments.

## How to test this PR?

- Add `coral-plugin-comment-content` to you plugins.json within `client`
- Post a comment with a link on it.
- Click it
- Check that everything is working as expected.

_Note: We will be migrating all the `coral-plugin-*` in the `client` folder to plugins._

2017-06-13 16:31 UTC, cvle commented
Interesting, I just realised that what we discussed last time doesn't work in React, which was using Components in a nested way to allow multiple plugins altering the body. We should have a quick talk about this with @jde to see if this is enough to satisfy the requirements.

2017-06-13 16:37 UTC, alinhle requested changes
I found several cases where link detection failed:
![image](https://user-images.githubusercontent.com/14221600/27093445-e8d53222-5090-11e7-8b8a-51a3a2641c23.png).

I suggest rather than rolling our own solution here, we should use a tiny library like ~https://github.com/alexcorvi/anchorme.js~ to do it for us in combination with ~`dangerouslySetInnerHTML`~.

2017-06-13 17:01 UTC, cvle commented
Just realised that `dangerouslySetInnerHTML` is a very bad idea security wise... we can use a solution like https://github.com/tasti/react-linkify that uses a tokenizer from markdown-it (https://github.com/markdown-it/linkify-it) to do it.

2017-06-13 18:15 UTC, okbel commented
ready to test @cvle :)

2017-06-13 18:22 UTC, cvle commented on plugins/coral-plugin-comment-content/client/components/CommentContent.js
> +            <Linkify>
Missing something like `properties={{target: '_parent'}}`, so the links work inside the iframe.

2017-06-13 18:31 UTC, cvle commented
Awesome! We'll talk with @jde if this satisfies the requirements, other than that the code looks great!

2017-06-14 14:42 UTC, jde commented
When I run the server without `coral-plugin-comment-content`, however, the body of the comments isn't rendered:

![screenshot 2017-06-14 10 39 01](https://user-images.githubusercontent.com/259957/27138235-0c7f679e-50ee-11e7-884f-fe1a0e8341fe.png)

If no plugin is present for this slot the content should be rendered as is from state.

2017-06-14 18:32 UTC, alinhle approved these changes
I added a few small changes:
- Switch reaction plugins to components/ui
- Only create Slot elements once
- Support Class Components as defaultComponent

2017-06-14 19:06 UTC, merged