New Slot: commentAuthorName
coralproject/talk pull request #868
Opened 2017-08-21 15:23 UTC by okbel

## What does this PR do?
- Adds a new Slot `commentAuthorName`
- Removes old code
- New Recipe: Author Name Recipe: **Member Since**
  https://www.pivotaltracker.com/story/show/150178457

### Author Name Recipe: **Member Since** - Preview
<img width="315" alt="screen shot 2017-08-21 at 12 15 26 pm" src="https://user-images.githubusercontent.com/1401559/29526181-5700aa64-866b-11e7-95f5-967230eba9d2.png">

2017-08-21 16:34 UTC, cvle commented on client/coral-embed-stream/style/default.css
> +.talk-stream-comment-header {
Avoid adding styles to `default.css` as it is deprecated.

2017-08-21 16:34 UTC, cvle commented on plugins/talk-plugin-featured-comments/client/components/Comment.js
> +            comment={comment}
Slot Requirements:
- The slot component needs the queryData `{root, comment, asset}`
- The slot fragments needs to be added to the fragments tree.
- Current workaround also requires `data={data}` to be passed to the Slot.
- A default component also needs to be added

2017-08-21 16:34 UTC, alinhle requested changes
See above

2017-08-21 17:27 UTC, okbel commented on client/coral-embed-stream/style/default.css
> +.talk-stream-comment-header {
Got it. I didn't know about this. 👍

2017-08-21 17:55 UTC, okbel commented
Changes added.

I've noticed this: 
<img width="984" alt="screen shot 2017-08-21 at 2 52 49 pm" src="https://user-images.githubusercontent.com/1401559/29531833-b8a172de-8680-11e7-86ed-9a39cf8609e9.png">

Shouldn't `withFragments` also extend the update fields too?

2017-08-22 07:58 UTC, cvle commented
I guess you are right, the comments fragment from the embed stream should be added to the post comment mutation.

2017-08-23 10:05 UTC, cvle commented
@okbel I couldn't reproduce the fragments warning and these also seem like an older issue that has been already resolved. How did you get these warnings?

2017-08-23 12:55 UTC, okbel commented
I'm still getting that warning. Maybe because I'm running an older version of Apollo? @cvle

2017-08-23 15:42 UTC, cvle commented
I added the slot to the featured comments fragments

2017-08-23 15:42 UTC, alinhle approved these changes

2017-08-23 17:20 UTC, merged