In-Stream Moderation Updates
coralproject/talk pull request #942
Opened 2017-09-11 17:09 UTC by okbel

## What does this PR do?
- Adds modifications to In-Stream Moderation such as:
  - Naming conventions
  - Updating the cache
  - Adding a reducer for the Moderation Tooltip

2017-09-11 17:20 UTC, cvle commented on plugins/talk-plugin-moderation-actions/client/containers/ApproveCommentAction.js
> -      notify('error', getErrorMessages(err));
The framework doesn't automatically fire notifications to notice the user about the error, so this line is still needed. Also `notify` is a redux action and need to be connected.

2017-09-11 17:20 UTC, cvle commented on plugins/talk-plugin-moderation-actions/client/containers/RejectCommentAction.js
> -      notify('error', getErrorMessages(err));
The framework doesn't automatically fire notifications to notice the user about the error, so this line is still needed. Also `notify` is a redux action and need to be connected.

2017-09-11 17:23 UTC, cvle commented on plugins/talk-plugin-moderation-actions/client/containers/ModerationActions.js
> +    if (this.props.showTooltipForComment === this.props.comment.id) {
We should probably extract this logic into something like
```js
isTooltipVisible: (props = this.props) => props.showTooltipForComment === props.comment.id
```

2017-09-11 17:39 UTC, cvle commented on plugins/talk-plugin-moderation-actions/client/actions.js
> +import {OPEN_TOOLTIP, CLOSE_TOOLTIP} from './constants';
According to wikipedia, a `tooltip `is sth that shows when hovering over it, so I don't think this is the correct term here. I'd just call it _menu_.

2017-09-11 17:40 UTC, cvle commented on plugins/talk-plugin-moderation-actions/client/constants.js
> +export const OPEN_TOOLTIP = `${prefix}_OPEN_TOOLTIP`;
According to wikipedia, a `tooltip `is sth that shows when hovering over it, so I don't think this is the correct term here. I'd just call it _menu_.

2017-09-11 17:41 UTC, cvle commented on plugins/talk-plugin-moderation-actions/client/containers/ModerationActions.js
> +    if (this.props.showTooltipForComment === this.props.comment.id) {
Following my other comments this should rather be sth like `isMenuVisibile`

2017-09-11 17:43 UTC, alinhle requested changes
Great job so far! Besides the above comments, we also identified two changes:

![image](https://user-images.githubusercontent.com/14221600/30288283-7f9d24fc-9728-11e7-8380-53198cb46218.png)

1. The `approved` button should not have a hover styling, so that it does not suggest that it's clickable, as it does nothing when clicking on it.

2. After performing an action, the menu should hide.

2017-09-11 18:42 UTC, okbel commented
All the issues above solved, but one. When you feature a comment the Menu is not closing. I need a clean way to pass `hideMenu` to the Slot. Any thoughts?

2017-09-11 18:44 UTC, okbel commented
_Note: Since I can't just import the action from a plugin that the user might not even have._

I tried to pass that to the _<Slot>_ . It doesn't look very clean.

2017-09-12 08:36 UTC, cvle commented
Just connect the action using redux

2017-09-12 15:29 UTC, cvle commented on plugins/talk-plugin-featured-comments/client/index.js
> +        if (name !== 'FEATURED') {
Where does the variable `name` come from?

2017-09-12 15:29 UTC, cvle commented on plugins/talk-plugin-featured-comments/client/index.js
> +          fragment Talk_ModerationActions_addTag on Comment {
This should be something with `FeaturedComments`

2017-09-12 15:31 UTC, cvle commented on plugins/talk-plugin-featured-comments/client/index.js
>            }
Line 63-73 needs to be removed as it is replaced with the new `update` below.
https://github.com/coralproject/talk/pull/942/files#diff-8103bea6e6543f80c7f897579ce2dcbeL63

2017-09-12 15:52 UTC, cvle commented
- Approved button still shows a pointer cursor when hovering it and clicking on it causes the menu hide and send a mutation to the server. Approved button shouldn't perform any action and it's styling shouldn't suggest that it's clickable.

![image](https://user-images.githubusercontent.com/14221600/30334824-f86f9b90-97e0-11e7-8440-c2e400b7a42b.png)

- Another bug I found is when I feature a comment, the button doesn't change its text to `un-feature` unless I leave and rehover with the mouse. So the text remains `feature` and clicking it will _unfeature_ the comment.

![image](https://user-images.githubusercontent.com/14221600/30335517-e6d01b38-97e2-11e7-95ba-57fe66755682.png)

2017-09-12 15:55 UTC, okbel commented
Thanks for reporting them! I will be working on them.

2017-09-12 16:43 UTC, okbel commented
All the issues have been addressed. Ready to be checked. @cvle

2017-09-12 16:56 UTC, alinhle requested changes

2017-09-12 16:56 UTC, cvle commented on plugins/talk-plugin-moderation-actions/client/containers/RejectCommentAction.js
> -  rejectComment = async () => {
Need `async` otherwise `try` `catch` doesn't work.

2017-09-12 16:56 UTC, cvle commented on plugins/talk-plugin-moderation-actions/client/containers/RejectCommentAction.js
> -      const result = await setCommentStatus({
Need `await` otherwise `try` `catch` doesn't work.

2017-09-12 16:56 UTC, cvle commented on plugins/talk-plugin-moderation-actions/client/containers/RejectCommentAction.js
> +    const {setCommentStatus, closeMenu, comment} = this.props;
Need to get `notify` from props, otherwise its unbounded to the store.

2017-09-12 16:56 UTC, cvle commented on plugins/talk-plugin-moderation-actions/client/containers/ApproveCommentAction.js
> +    const {setCommentStatus, closeMenu, comment} = this.props;
Need to get `notify` from props, otherwise its unbounded to the store.

2017-09-12 16:56 UTC, cvle commented on plugins/talk-plugin-moderation-actions/client/containers/ApproveCommentAction.js
> -  approveComment = async () => {
Need `async` otherwise `try` `catch` doesn't work.

2017-09-12 16:56 UTC, cvle commented on plugins/talk-plugin-moderation-actions/client/containers/ApproveCommentAction.js
> -      const result = await setCommentStatus({
Need `await` otherwise `try` `catch` doesn't work.

2017-09-13 12:11 UTC, alinhle approved these changes
Looks good!

2017-09-13 12:18 UTC, merged